keel-redis/src/main/kotlin/com/netflix/spinnaker/keel/redis/RedisIntentActivityRepository.kt
keel-redis/src/main/kotlin/com/netflix/spinnaker/keel/redis/RedisTraceRepository.kt
keel-redis/src/test/groovy/com/netflix/spinnaker/keel/redis/RedisIntentActivityRepositorySpec.groovy

feat(redis): adding redis-backed intent repository

---

keel-core/keel-core.gradle
keel-core/src/main/kotlin/com/netflix/spinnaker/config/KeelConfiguration.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/Intent.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/IntentLauncher.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/IntentPolicy.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/IntentPriority.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/IntentSpec.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/PolicyRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/matcher/Matcher.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/memory/MemoryPolicyRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/policy/policies.kt
keel-core/src/test/groovy/com/netflix/spinnaker/keel/dryrun/DryRunIntentLauncherSpec.groovy
keel-core/src/test/groovy/com/netflix/spinnaker/keel/matcher/PriorityMatcherSpec.groovy
keel-intents/src/main/kotlin/com/netflix/spinnaker/keel/intents/ParrotIntent.kt
keel-intents/src/main/kotlin/com/netflix/spinnaker/keel/intents/SecurityGroupIntent.kt
keel-intents/src/main/kotlin/com/netflix/spinnaker/keel/intents/processors/ParrotIntentProcessor.kt
keel-intents/src/test/groovy/com/netflix/spinnaker/keel/intents/processors/ApplicationIntentProcessorSpec.groovy
keel-redis/src/test/groovy/com/netflix/spinnaker/keel/redis/RedisTraceRepositorySpec.groovy
keel-test/src/main/kotlin/com/netflix/spinnaker/keel/test/TestIntent.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/controllers/v1/admin/PolicyController.kt

cc @emjburns @robfletcher @cfieber @jeyrschabu

feat(core): Policies

---

keel-front50/src/main/kotlin/com/netflix/spinnaker/keel/front50/annotations/Computed.kt
keel-front50/src/main/kotlin/com/netflix/spinnaker/keel/front50/model/Application.kt
keel-intents/src/main/kotlin/com/netflix/spinnaker/keel/intents/ApplicationIntent.kt
keel-intents/src/main/kotlin/com/netflix/spinnaker/keel/intents/processors/ApplicationIntentProcessor.kt
keel-intents/src/main/kotlin/com/netflix/spinnaker/keel/intents/processors/converters/ApplicationConverter.kt
keel-intents/src/test/groovy/com/netflix/spinnaker/keel/intents/processors/ApplicationIntentProcessorSpec.groovy
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/controllers/v1/IntentController.kt

* Add annotation for computed parameters
* Ignore annotated parameters when comparing state
* Start of an application converter

feat(intents): compare actual vs desired state before updating

---

keel-core/src/main/kotlin/com/netflix/spinnaker/config/KeelConfiguration.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/IntentRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/memory/MemoryIntentRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/objectMapperUtil.kt
keel-front50/src/main/kotlin/com/netflix/spinnaker/keel/front50/Front50IntentRepository.kt
keel-front50/src/main/kotlin/com/netflix/spinnaker/keel/front50/Front50Service.kt
keel-intents/src/main/kotlin/com/netflix/spinnaker/config/IntentConfiguration.kt
keel-intents/src/main/kotlin/com/netflix/spinnaker/keel/intents/SecurityGroupIntent.kt
keel-intents/src/main/kotlin/com/netflix/spinnaker/keel/intents/processors/SecurityGroupIntentProcessor.kt
keel-intents/src/main/kotlin/com/netflix/spinnaker/keel/intents/processors/converters/SecurityGroupConverter.kt
keel-intents/src/test/kotlin/com/netflix/spinnaker/keel/intents/processors/SecurityGroupIntentProcessorTest.kt
keel-intents/src/test/kotlin/com/netflix/spinnaker/keel/intents/processors/converters/SecurityGroupConverterTest.kt
keel-orca/src/main/kotlin/com/netflix/spinnaker/keel/orca/OrcaIntentLauncher.kt
keel-scheduler/src/test/kotlin/com/netflix/spinnaker/keel/scheduler/handler/ConvergeIntentHandlerTest.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/controllers/v1/IntentController.kt

Not all-inclusive, but a start with the most common case.

feat(intent): Security group ingress rule support

---

keel-web/src/main/kotlin/com/netflix/spinnaker/keel/controllers/v1/IntentController.kt

Now the format returned by this API is the same for dry run vs no dry run: List<Map>

feat(controller): normal upsert response format matchs dry run

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/memory/MemoryIntentRepository.kt
keel-front50/src/main/kotlin/com/netflix/spinnaker/keel/front50/Front50IntentRepository.kt

Little quality of life thing in local development: Create/update/delete intents without affecting a remote environment.

feat(front50): Flag to disable front50 intent repository

---

build.gradle
gradle/kotlin.gradle
keel-clouddriver/dependencies.lock
keel-core/dependencies.lock
keel-core/src/main/kotlin/com/netflix/spinnaker/config/KeelConfiguration.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/memory/MemoryIntentActivityRepository.kt
keel-echo/dependencies.lock
keel-echo/src/main/kotlin/com/netflix/spinnaker/config/EchoConfiguration.kt
keel-eureka/dependencies.lock
keel-front50/dependencies.lock
keel-front50/src/main/kotlin/com/netflix/spinnaker/config/Front50Configuration.kt
keel-intent-aws/dependencies.lock
keel-intent/dependencies.lock
keel-intent/src/main/kotlin/com/netflix/spinnaker/config/IntentConfiguration.kt
keel-orca/dependencies.lock
keel-redis/dependencies.lock
keel-redis/src/main/kotlin/com/netflix/spinnaker/config/DynomiteConfiguration.kt
keel-redis/src/main/kotlin/com/netflix/spinnaker/config/JedisConfiguration.kt
keel-retrofit/dependencies.lock
keel-retrofit/src/main/kotlin/com/netflix/spinnaker/keel/retrofit/RetrofitConfiguration.kt
keel-scheduler/dependencies.lock
keel-scheduler/keel-scheduler.gradle
keel-scheduler/src/main/kotlin/com/netflix/spinnaker/config/SchedulerConfiguration.kt
keel-scheduler/src/main/kotlin/com/netflix/spinnaker/keel/scheduler/messages.kt
keel-test/dependencies.lock
keel-web/dependencies.lock
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/Main.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/controllers/v1/IntentController.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/controllers/v1/SchemaController.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/web/config/WebConfiguration.kt

chore(*): Dependency updates

---

keel-front50/src/main/kotlin/com/netflix/spinnaker/config/Front50Configuration.kt
keel-front50/src/main/kotlin/com/netflix/spinnaker/config/Front50RateLimitProperties.kt
keel-front50/src/main/kotlin/com/netflix/spinnaker/keel/front50/Front50IntentRepository.kt

While I'm working through https://github.com/spinnaker/keiko/pull/15, adding this so we don't thrash front50 as much. Nice insurance to have anyhow.

feat(front50): Adding internal rate limiter

---

keel-clouddriver/src/test/kotlin/com/netflix/spinnaker/keel/clouddriver/model/BaseModelParsingTest.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/config/KeelConfiguration.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/model/OrchestrationRequest.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/objectMapperUtil.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/dryrun/DryRunIntentLauncherTest.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/model/OrchestrationRequestTest.kt
keel-front50/src/main/kotlin/com/netflix/spinnaker/keel/front50/Front50Service.kt
keel-front50/src/main/kotlin/com/netflix/spinnaker/keel/front50/model/Application.kt
keel-front50/src/main/kotlin/com/netflix/spinnaker/keel/front50/model/PipelineConfig.kt
keel-intent/src/main/kotlin/com/netflix/spinnaker/config/IntentConfiguration.kt
keel-intent/src/main/kotlin/com/netflix/spinnaker/keel/intent/PipelineIntent.kt
keel-intent/src/main/kotlin/com/netflix/spinnaker/keel/intent/processor/ParrotIntentProcessor.kt
keel-intent/src/main/kotlin/com/netflix/spinnaker/keel/intent/processor/PipelineIntentProcessor.kt
keel-intent/src/main/kotlin/com/netflix/spinnaker/keel/intent/processor/SecurityGroupIntentProcessor.kt
keel-intent/src/main/kotlin/com/netflix/spinnaker/keel/intent/processor/converter/PipelineConverter.kt
keel-intent/src/test/kotlin/com/netflix/spinnaker/keel/intent/AvailabilityZoneConfigTest.kt
keel-intent/src/test/kotlin/com/netflix/spinnaker/keel/intent/LoadBalancerIntentTest.kt
keel-intent/src/test/kotlin/com/netflix/spinnaker/keel/intent/PipelineIntentTest.kt
keel-intent/src/test/kotlin/com/netflix/spinnaker/keel/intent/processor/PipelineIntentProcessorTest.kt
keel-intent/src/test/kotlin/com/netflix/spinnaker/keel/intent/processor/converter/PipelineConverterTest.kt
keel-redis/src/test/kotlin/com/netflix/spinnaker/keel/redis/RedisIntentActivityRepositoryTest.kt

Converter isn't working because I need to update to the latest keiko again. Will submit that in a different PR this time.

feat(intent): Pipeline intent processing

---

keel-core/src/main/kotlin/com/netflix/spinnaker/config/IntentGuardConfiguration.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/config/KeelConfiguration.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/guards.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/WhitelistingIntentGuardTest.kt
keel-intent/src/main/kotlin/com/netflix/spinnaker/keel/intent/ApplicationIntent.kt
keel-intent/src/test/kotlin/com/netflix/spinnaker/keel/intent/processor/ApplicationIntentProcessorTest.kt

Sometimes (often) I don't understand Spring.

fix(core): Spring config wiring fixes

---

keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/model/Subnet.kt
keel-clouddriver/src/test/kotlin/com/netflix/spinnaker/keel/clouddriver/MemoryCloudDriverCacheTest.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/Intent.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/filter/ExecutionWindowFilter.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/memory/MemoryIntentRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/memory/MemoryTraceRepository.kt
keel-echo/src/main/kotlin/com/netflix/spinnaker/keel/echo/EventNotificationListener.kt
keel-intent-aws/src/main/kotlin/com/netflix/spinnaker/keel/intent/aws/loadbalancer/ClassicLoadBalancerConverter.kt
keel-intent-aws/src/main/kotlin/com/netflix/spinnaker/keel/intent/aws/loadbalancer/ClassicLoadBalancerIntent.kt
keel-intent-aws/src/main/kotlin/com/netflix/spinnaker/keel/intent/aws/loadbalancer/ClassicLoadBalancerIntentProcessor.kt
keel-intent-aws/src/main/kotlin/com/netflix/spinnaker/keel/intent/aws/securitygroup/AmazonSecurityGroupIntentListener.kt
keel-intent-aws/src/main/kotlin/com/netflix/spinnaker/keel/intent/aws/securitygroup/AmazonSecurityGroupIntentProcessor.kt
keel-intent-aws/src/test/kotlin/com/netflix/spinnaker/keel/intent/aws/loadbalancer/ClassicLoadBalancerConverterTest.kt
keel-intent-aws/src/test/kotlin/com/netflix/spinnaker/keel/intent/aws/loadbalancer/ClassicLoadBalancerIntentTest.kt
keel-intent/src/main/kotlin/com/netflix/spinnaker/keel/intent/processor/ApplicationIntentProcessor.kt
keel-intent/src/main/kotlin/com/netflix/spinnaker/keel/intent/processor/ParrotIntentProcessor.kt
keel-intent/src/main/kotlin/com/netflix/spinnaker/keel/intent/processor/PipelineIntentProcessor.kt
keel-orca/src/main/kotlin/com/netflix/spinnaker/keel/orca/OrcaIntentLauncher.kt
keel-redis/src/main/kotlin/com/netflix/spinnaker/keel/redis/RedisTraceRepository.kt
keel-scheduler/src/main/kotlin/com/netflix/spinnaker/keel/scheduler/handler/ConvergeIntentHandler.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/controllers/v1/IntentController.kt

* Updated CLB to support VPCs
* Updated Intent ID to include the region
* Fixed healthcheck serialization issue (overriding Kotlin toString is a no-no)

feat(aws): Complete classic load balancer intent

---

keel-api/src/main/proto/Asset.proto
keel-api/src/main/proto/AssetPlugin.proto
keel-api/src/test/kotlin/com/netflix/spinnaker/keel/api/TestAssetPlugin.kt
keel-api/src/test/kotlin/com/netflix/spinnaker/keel/api/TestAssetPluginSpec.kt
keel-aws/src/main/kotlin/com/netflix/spinnaker/keel/aws/AmazonAssetPlugin.kt
keel-aws/src/test/kotlin/com/netflix/spinnaker/keel/aws/AmazonAssetPluginSpec.kt
keel-rule-engine/src/main/kotlin/com/netflix/spinnaker/keel/grpc/Glue.kt
keel-rule-engine/src/main/kotlin/com/netflix/spinnaker/keel/model/Asset.kt
keel-rule-engine/src/main/kotlin/com/netflix/spinnaker/keel/persistence/AssetRepository.kt
keel-rule-engine/src/main/kotlin/com/netflix/spinnaker/keel/persistence/InMemoryAssetRepository.kt
keel-rule-engine/src/main/kotlin/com/netflix/spinnaker/keel/processing/AssetService.kt
keel-rule-engine/src/main/kotlin/com/netflix/spinnaker/keel/processing/ConvergeAssetHandler.kt
keel-rule-engine/src/main/kotlin/com/netflix/spinnaker/keel/processing/GrpcAssetService.kt
keel-rule-engine/src/main/kotlin/com/netflix/spinnaker/keel/processing/ValidateAssetTreeHandler.kt
keel-rule-engine/src/main/kotlin/com/netflix/spinnaker/keel/processing/VetoService.kt
keel-rule-engine/src/test/kotlin/com/netflix/spinnaker/keel/model/AssetTests.kt
keel-rule-engine/src/test/kotlin/com/netflix/spinnaker/keel/processing/ConvergeAssetHandlerSpec.kt
keel-rule-engine/src/test/kotlin/com/netflix/spinnaker/keel/processing/GrpcAssetServiceTests.kt
keel-rule-engine/src/test/kotlin/com/netflix/spinnaker/keel/processing/ValidateAssetTreeHandlerSpec.kt

Will allow for stuff like security group rules to be defined separately from the root security group.

Adding asset containers & partials

---

keel-rule-engine/src/main/kotlin/com/netflix/spinnaker/keel/grpc/Glue.kt
keel-rule-engine/src/main/kotlin/com/netflix/spinnaker/keel/model/Asset.kt
keel-rule-engine/src/main/kotlin/com/netflix/spinnaker/keel/persistence/AssetRepository.kt
keel-rule-engine/src/main/kotlin/com/netflix/spinnaker/keel/persistence/InMemoryAssetRepository.kt
keel-rule-engine/src/main/kotlin/com/netflix/spinnaker/keel/processing/ConvergeAssetHandler.kt
keel-rule-engine/src/main/kotlin/com/netflix/spinnaker/keel/processing/ValidateAssetTreeHandler.kt
keel-rule-engine/src/test/kotlin/com/netflix/spinnaker/keel/processing/ConvergeAssetHandlerSpec.kt

We prefer small, well tested pull requests.
Please refer to [Contributing to Spinnaker](https://spinnaker.io/community/contributing/).
When filling out a pull request, please consider the following:
* Follow the commit message conventions [found here](http://www.spinnaker.io/v1.0/docs/how-to-submit-a-patch).
* Provide a descriptive summary for your changes.
* If it fixes a bug or resolves a feature request, be sure to link to that issue.
* Add inline code comments to changes that might not be obvious.
* Squash your commits as you keep adding changes.
* Add a comment to @spinnaker/reviewers for review if your issue has been outstanding for more than 3 days.
Note that we are unlikely to accept pull requests that add features without prior discussion. The best way to propose a feature is to …

Change AssetContainer to be nullable instead of wrapped asset

---

keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/ec2/SecurityGroup.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/api/ec2/SecurityGroupTests.kt

Ignore security group description when diffing

---

keel-plugin/src/main/kotlin/com/netflix/spinnaker/keel/plugin/ResourceHandler.kt
keel-plugin/src/main/kotlin/com/netflix/spinnaker/keel/plugin/ResourceNormalizer.kt

missed a method renaming is hard

chore(normalizer): rename method as well:

---

keel-sqs/src/main/kotlin/com/netflix/spinnaker/config/SqsProperties.kt
keel-sqs/src/main/kotlin/com/netflix/spinnaker/keel/sqs/SqsResourceCheckListener.kt
keel-sqs/src/test/kotlin/com/netflix/spinnaker/keel/sqs/SqsResourceCheckListenerTests.kt

Took some tips from https://jivimberg.io/blog/2019/02/23/sqs-consumer-using-kotlin-coroutines/

Better coroutine usage in SQS listener

---

gradle/junit5.gradle
keel-api/src/test/kotlin/com/netflix/spinnaker/keel/rest/ResourceControllerTests.kt
keel-clouddriver/src/test/kotlin/com/netflix/spinnaker/keel/clouddriver/MemoryCloudDriverCacheTest.kt
keel-core-test/keel-core-test.gradle
keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ResourceRepositoryTests.kt
keel-deliveryconfig-plugin/src/test/kotlin/com/netflix/spinnaker/keel/deliveryconfig/resource/DeliveryConfigHandlerTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandlerTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/SecurityGroupHandlerTests.kt
keel-plugin/keel-plugin.gradle
keel-plugin/src/test/kotlin/com/netflix/spinnaker/keel/annealing/ResourceActuatorTests.kt
keel-plugin/src/test/kotlin/com/netflix/spinnaker/keel/annealing/spring/SpringBasedResourceCheckQueueTests.kt
keel-spring-test-support/keel-spring-test-support.gradle
keel-spring-test-support/src/main/kotlin/com/netflix/spinnaker/keel/redis/spring/MockEurekaConfiguration.kt
keel-sqs/src/test/kotlin/com/netflix/spinnaker/keel/sqs/SqsResourceCheckListenerTests.kt
keel-veto/src/test/kotlin/com/netflix/spinnaker/keel/api/SimpleVetoPluginTests.kt

Weekend experiment since people kept saying I should try this lib.
I think the DSL is a little more consistent than the Mockito one. ¯\_(ツ)_/¯

chore(tests): Mockito -> MockK

---

keel-actuator/keel-actuator.gradle.kts
keel-actuator/src/main/kotlin/com/netflix/spinnaker/keel/actuation/ResourceActuator.kt
keel-actuator/src/main/kotlin/com/netflix/spinnaker/keel/actuation/ResourceCheckScheduler.kt
keel-actuator/src/test/kotlin/com/netflix/spinnaker/keel/actuation/ResourceActuatorTests.kt
keel-actuator/src/test/kotlin/com/netflix/spinnaker/keel/actuation/ResourceCheckSchedulerTests.kt
keel-actuator/src/test/kotlin/com/netflix/spinnaker/keel/actuation/ResourcePersisterTests.kt
keel-api/keel-api.gradle.kts
keel-api/src/test/kotlin/com/netflix/spinnaker/keel/integration/AuthPropagationTests.kt
keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/keel/bakery/resource/ImageHandler.kt
keel-bakery-plugin/src/test/kotlin/com/netflix/spinnaker/keel/bakery/resource/ImageHandlerTests.kt
keel-deliveryconfig-plugin/src/main/kotlin/com/netflix/spinnaker/keel/deliveryconfig/resource/DeliveryConfigHandler.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClassicLoadBalancerHandler.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandler.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/NamedImageHandler.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/SecurityGroupHandler.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClassicLoadBalancerModelHandlerTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandlerTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/SecurityGroupHandlerTests.kt
keel-plugin/src/main/kotlin/com/netflix/spinnaker/keel/plugin/ResolvableResourceHandler.kt
keel-plugin/src/main/kotlin/com/netflix/spinnaker/keel/plugin/ResourceHandler.kt
keel-retrofit/src/main/kotlin/com/netflix/spinnaker/keel/retrofit/KeelRetrofitConfiguration.kt
keel-retrofit/src/main/kotlin/com/netflix/spinnaker/keel/retrofit/KeelRetrofitProperties.kt

Fix auth propagation when using coroutines with Retrofit

---

keel-tagging-plugin/src/main/kotlin/com/netflix/spinnaker/keel/tagging/ResourceTagger.kt
keel-tagging-plugin/src/test/kotlin/com/netflix/spinnaker/keel/tagging/ResourceTaggerTests.kt

We only want to tag resources that we create, not things that we use internally like images or tags.

fix(tagging): only tag real resources

---

keel-tagging-plugin/src/main/kotlin/com/netflix/spinnaker/keel/tagging/KeelTagSpec.kt
keel-tagging-plugin/src/main/kotlin/com/netflix/spinnaker/keel/tagging/TagStateDeserializer.kt

We were having trouble deserializing things after pulling them from sql because of type erasure.

fix(tags): provide serialization info

---

gradle.properties
keel-actuator/keel-actuator.gradle.kts
keel-bakery-plugin/keel-bakery-plugin.gradle.kts
keel-core/keel-core.gradle.kts

cleans up a couple transitive dependencies that were inherited from random bits of kork in advance
of a cleanup refactor I'm working on over there

chore(dependencies): latest kork version and some explicit dependencies

---

keel-api/keel-api.gradle.kts
keel-api/src/main/kotlin/com/netflix/spinnaker/config/DefaultConfiguration.kt
keel-api/src/test/kotlin/com/netflix/spinnaker/keel/integration/SpringStartupTests.kt
keel-plugin/src/main/kotlin/com/netflix/spinnaker/keel/plugin/ResolvableResourceHandler.kt

We prefer small, well tested pull requests.
Please refer to [Contributing to Spinnaker](https://spinnaker.io/community/contributing/).
When filling out a pull request, please consider the following:
* Follow the commit message conventions [found here](http://www.spinnaker.io/v1.0/docs/how-to-submit-a-patch).
* Provide a descriptive summary for your changes.
* If it fixes a bug or resolves a feature request, be sure to link to that issue.
* Add inline code comments to changes that might not be obvious.
* Squash your commits as you keep adding changes.
* Add a comment to @spinnaker/reviewers for review if your issue has been outstanding for more than 3 days.
Note that we are unlikely to accept pull requests that add features without prior discussion. The best way to propose a feature is to …

fix(spring): break circular dependency in beans

---

keel-artifact/src/main/kotlin/com/netflix/spinnaker/keel/artifact/ArtifactListener.kt

I think I accidentally backed this out by screwing up a merge / rebase.

Only look at artifact events we support

---

keel-actuator/src/main/kotlin/com/netflix/spinnaker/keel/actuation/ResourcePersister.kt
keel-actuator/src/test/kotlin/com/netflix/spinnaker/keel/actuation/ResourcePersisterTests.kt
keel-api/src/test/kotlin/com/netflix/spinnaker/keel/rest/DeliveryConfigControllerTests.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/api/DeliveryConfig.kt

Previously we weren't allowing constraints to be submitted. This fixes that.

fix(configs): allow constraints to be persisted

---

keel-actuator/src/main/kotlin/com/netflix/spinnaker/keel/actuation/EnvironmentPromotionChecker.kt
keel-actuator/src/test/kotlin/com/netflix/spinnaker/keel/actuation/EnvironmentPromotionCheckerTests.kt

Previously if no version met the constraints we'd throw an exception trying to get the `.first`

fix(envs): don't fail when no version is ok

---

keel-api/src/main/kotlin/com/netflix/spinnaker/config/DefaultConfiguration.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/memory/InMemoryApplicationVetoRepository.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/config/SqlConfiguration.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlApplicationVetoRepository.kt
keel-veto/src/main/kotlin/com/netflix/spinnaker/keel/veto/application/ApplicationVeto.kt

Forgot to use the sql database :D

fix(veto): wire in sql repo

---

keel-tagging-plugin/src/main/kotlin/com/netflix/spinnaker/keel/tagging/ResourceTagger.kt
keel-tagging-plugin/src/test/kotlin/com/netflix/spinnaker/keel/tagging/ResourceTaggerTests.kt

At some point we changed to kebab and forgot to update the tagger :D

fix(tags): securityGroup -> security-group

---

keel-actuator/src/test/kotlin/com/netflix/spinnaker/keel/actuation/ResourcePersisterTests.kt
keel-api/src/main/kotlin/com/netflix/spinnaker/keel/rest/ResourceController.kt
keel-api/src/test/kotlin/com/netflix/spinnaker/keel/rest/DeliveryConfigControllerTests.kt
keel-api/src/test/kotlin/com/netflix/spinnaker/keel/rest/ResourceControllerTests.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/api/Resource.kt
keel-plugin/src/main/kotlin/com/netflix/spinnaker/keel/plugin/ResolvableResourceHandler.kt
keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/tx/DeliveryConfigTransactionTests.kt
keel-tagging-plugin/src/main/kotlin/com/netflix/spinnaker/keel/tagging/ResourceTagger.kt

Preserve non-reserved metadata

---

keel-api/src/main/kotlin/com/netflix/spinnaker/keel/rest/ArtifactController.kt
keel-artifact/src/main/kotlin/com/netflix/spinnaker/keel/artifact/ArtifactListener.kt

Ignore all non-artifact events.

fix(artifact): don't get releaseStatus for rando events

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/diff/ResourceDiff.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/diff/ResourceDiffTests.kt

don't treat different map types as inherently different

---

keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/CloudDriverCache.kt
keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/MemoryCloudDriverCache.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/ec2/ClusterSpec.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandler.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/api/ec2/ClusterSpecTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandlerTests.kt

Assign AZs to clusters automatically if not specified

---

README.md

@robfletcher moving your architecture document to the readme

feat(docs): update readme with architecture overview

---

keel-actuator/src/main/kotlin/com/netflix/spinnaker/keel/diff/AdHocDiffer.kt
keel-actuator/src/main/kotlin/com/netflix/spinnaker/keel/diff/DiffResult.kt
keel-actuator/src/main/kotlin/com/netflix/spinnaker/keel/diff/DiffStatus.kt
keel-actuator/src/test/kotlin/com/netflix/spinnaker/keel/diff/AdHocDifferTests.kt
keel-api/src/main/kotlin/com/netflix/spinnaker/keel/rest/ResourceController.kt
keel-api/src/test/kotlin/com/netflix/spinnaker/keel/rest/ResourceControllerTests.kt
keel-test/src/main/kotlin/com/netflix/spinnaker/keel/test/Resources.kt

An endpoint to generate and ad hoc diff. First step in https://github.com/spinnaker/keel/issues/508.

feat(diff): diff endpoint

---

keel-actuator/src/main/kotlin/com/netflix/spinnaker/keel/diff/AdHocDiffer.kt
keel-actuator/src/main/kotlin/com/netflix/spinnaker/keel/diff/DiffResult.kt
keel-actuator/src/test/kotlin/com/netflix/spinnaker/keel/diff/AdHocDifferTests.kt
keel-api/src/main/kotlin/com/netflix/spinnaker/keel/rest/DeliveryConfigController.kt

Ad-hoc diffing for delivery configs. I return a list of diffs for each environment.

feat(diff): ad hoc delivery config diffing

---

keel-api/src/main/kotlin/com/netflix/spinnaker/keel/Main.kt
keel-api/src/test/kotlin/com/netflix/spinnaker/keel/rest/ConvertExampleFilesTest.kt
keel-api/src/test/resources/examples/simple-titus-cluster-example.yml
keel-api/src/test/resources/examples/titus-cluster-example.yml
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/api/Resource.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/serialization/SubmittedResourceDeserializer.kt
keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/titus/cluster/TitusClusterHandler.kt
keel-titus-plugin/src/test/kotlin/com/netflix/spinnaker/keel/titus/resource/TitusClusterHandlerTests.kt

The size of this PR is not reflective of how much of a pain in the arse it was to implement.
Fixes #527

Kind not required to be globally unique

---

keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/keel/bakery/resource/ImageHandler.kt
keel-bakery-plugin/src/test/kotlin/com/netflix/spinnaker/keel/bakery/resource/ImageHandlerTests.kt

It was worth a shot. It was not the right move.

fix(bakery): don't rebake. bakery can't handle

---

keel-actuator/src/main/kotlin/com/netflix/spinnaker/keel/actuation/CheckScheduler.kt
keel-actuator/src/main/kotlin/com/netflix/spinnaker/keel/actuation/ResourceActuator.kt
keel-actuator/src/test/kotlin/com/netflix/spinnaker/keel/actuation/CheckSchedulerTests.kt
keel-actuator/src/test/kotlin/com/netflix/spinnaker/keel/actuation/ResourceActuatorTests.kt
keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/keel/bakery/resource/ImageHandler.kt
keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ResourceRepositoryPeriodicallyCheckedTests.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ResourceRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/memory/InMemoryResourceRepository.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ApplicationLoadBalancerHandler.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClassicLoadBalancerHandler.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandler.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/SecurityGroupHandler.kt
keel-plugin/src/main/kotlin/com/netflix/spinnaker/keel/plugin/ResourceHandler.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlResourceRepository.kt
keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/SqlResourceRepositoryPeriodicallyCheckedTests.kt
keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/titus/cluster/TitusClusterHandler.kt

- fixes https://github.com/spinnaker/keel/issues/595

fix(actuation): correctly detect active actuations for multi-region resources

---

keel-actuator/src/main/kotlin/com/netflix/spinnaker/keel/diff/AdHocDiffer.kt
keel-actuator/src/test/kotlin/com/netflix/spinnaker/keel/diff/AdHocDifferTests.kt
keel-api/src/main/kotlin/com/netflix/spinnaker/keel/rest/ResourceController.kt

This endpoint was really slow. I was doing coroutines wrong. But, now, this is speedy.

fix(diff): do coroutines right

---

keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/ImageService.kt
keel-clouddriver/src/test/resources/named-images.json

The one where an an accidental comparison of `packageName` to itself results in incorrect baking.

fix(bake): correctly compare package name

---

keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/CloudDriverCache.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/api/Locatable.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/ec2/ClusterSpec.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/ec2/Health.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/ec2/LaunchConfiguration.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resolvers/NetworkResolver.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ApplicationLoadBalancerHandler.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClassicLoadBalancerHandler.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandler.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/SecurityGroupHandler.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resolvers/NetworkResolverTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandlerTests.kt

Closes #581 (maybe). See discussion below for implementation details.

fix(export): Omit fields with default values in cluster spec

---

keel-actuator/src/main/kotlin/com/netflix/spinnaker/keel/actuation/EnvironmentPromotionChecker.kt
keel-actuator/src/test/kotlin/com/netflix/spinnaker/keel/actuation/EnvironmentPromotionCheckerTests.kt
keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/DeliveryConfigRepositoryTests.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/api/Constraint.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/api/ConstraintState.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/constraints/AllowedTimesConstraintEvaluator.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/constraints/ConstraintEvaluator.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/constraints/DependsOnConstraintEvaluator.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/constraints/ManualJudgementConstraintEvaluator.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/DeliveryConfigRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/memory/InMemoryDeliveryConfigRepository.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/constraints/AllowedTimesConstraintEvaluatorTests.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/constraints/DependsOnConstraintEvaluatorTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resolvers/ImageResolverTests.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlDeliveryConfigRepository.kt
keel-sql/src/main/resources/db/changelog/20191108-environment-artifact-constraint.yml

- with a manual-judgement reference implementation

feat(constraints): initial stateful constraint support

---

keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/model/ActiveServerGroup.kt
keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/model/NamedImage.kt
keel-clouddriver/src/test/kotlin/com/netflix/spinnaker/keel/clouddriver/model/ActiveServerGroupTest.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/ec2/ClusterSpec.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/ec2/LaunchConfiguration.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resolvers/ImageResolver.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandler.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/api/ec2/ClusterSpecTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/api/ec2/ServerGroupDiffTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/image/CurrentlyDeployedImageApproverTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resolvers/ImageResolverTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandlerTests.kt

make base AMI version show up in cluster diffs

---

keel-sql/src/main/resources/db/changelog/20191123-rename-resource-check-pending-event.yml
keel-sql/src/main/resources/db/databaseChangeLog.yml

I changed the event name here: dad8110ebaa2ed99701f291ca71c4e9b38e4eddf

migrate event name properly

---

keel-actuator/src/main/kotlin/com/netflix/spinnaker/keel/pause/ResourcePauser.kt
keel-actuator/src/test/kotlin/com/netflix/spinnaker/keel/actuation/ResourceActuatorTests.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/ResourceController.kt

missed this endpoint, and a todo for making this easier in the future.

fix(status): show individual paused status

---

keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/ResourceController.kt

Deprecating individual resource creation/deletion because of https://github.com/spinnaker/keel/issues/660

chore(resource): Deprecate submitting individual resources

---

keel-core/src/test/kotlin/com/netflix/spinnaker/keel/model/MonikerTests.kt
keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/titus/cluster/TitusClusterSpec.kt

also fixing a moniker test which was giving me some typing trouble when compiling via the command line

fix(titus): enforce titus resource min and max

---

keel-sql/src/main/resources/db/changelog/20191218-add-status-to-environment-artifact-versions.yml
keel-sql/src/main/resources/db/changelog/20200107-default-promotion-status.yml
keel-sql/src/main/resources/db/databaseChangeLog.yml

Fix for #696 where I added a new column but didn't set a default value.

default the value for promotion status

---

keel-actuator/src/main/kotlin/com/netflix/spinnaker/keel/actuation/ResourceActuator.kt
keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/keel/bakery/resource/ImageHandler.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ApplicationLoadBalancerHandler.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClassicLoadBalancerHandler.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandler.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/SecurityGroupHandler.kt
keel-plugin/src/main/kotlin/com/netflix/spinnaker/keel/plugin/ResourceHandler.kt
keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/titus/cluster/TitusClusterHandler.kt

I noticed this one method signature didn't align with the generic type on the handler class itself.

bring actuationInProgress method signature in line

---

keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlArtifactRepository.kt
keel-sql/src/main/resources/db/changelog/20200110-artifact-fingerprint-unique.yml
keel-sql/src/main/resources/db/databaseChangeLog.yml

Now that the artifact fingerprint is calculated, make it unique. 
~@asher I also want to make the fingerprint column non-null. Do I use [addNotNullConstraint](https://www.liquibase.org/documentation/changes/add_not_null_constraint.html) or change data type? Or is there a better way to do this?~
Removed `computeFingerprints` and added the not-null constraint.

fix(artifact): make fingerprint unique

---

keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/keel/bakery/resource/ImageHandler.kt
keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/ImageService.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/api/DeliveryArtifact.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/events/ResourceEvent.kt

- Adding some debugging for images.
- Removing a no longer relevant todo.
- Fixing the formatting for debians when they are returned from the api.

chore(deb): add debug logs

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/events/ArtifactVersionDeployed.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/image/CurrentlyDeployedImageApprover.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandler.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/image/CurrentlyDeployedImageApproverTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandlerTests.kt

Mark artifacts as successfully deployed if they're using a reference provider

fix(promotion): mark reference artifacts deployed

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/api/DeliveryConfig.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/image/CurrentlyDeployedImageApprover.kt
keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/titus/cluster/TitusClusterHandler.kt
keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/titus/image/CurrentlyDeployedDockerImageApprover.kt
keel-titus-plugin/src/test/kotlin/com/netflix/spinnaker/keel/titus/image/CurrentlyDeployedDockerImageApproverTests.kt
keel-titus-plugin/src/test/kotlin/com/netflix/spinnaker/keel/titus/resource/TitusClusterHandlerTests.kt

Closes https://github.com/spinnaker/keel/issues/712.
While I was fixing the bug I created for ec2 reference artifact promotion I also implemented titus support.

feat(titus): depends-on constratint support

---

keel-orca/src/main/kotlin/com/netflix/spinnaker/keel/orca/OrcaTaskMonitorAgent.kt
keel-orca/src/test/kotlin/com/netflix/spinnaker/keel/orca/OrcaTaskMonitorAgentTests.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/config/SqlConfiguration.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlAgentLockRepository.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlTaskTrackingRepository.kt
keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/SqlTaskTrackingRepositoryTests.kt

fix(retrySupport): Adding retry support to taskTracking and AgentLock repo

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/exceptions/ExportError.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/plugin/ResourceSpecExportHelper.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/ec2/ClusterSpec.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/ec2/Health.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandler.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/api/ec2/export/ClusterExportTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandlerTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/TestUtils.kt
keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/titus/cluster/TitusClusterHandler.kt
keel-titus-plugin/src/test/kotlin/com/netflix/spinnaker/keel/titus/resource/TestUtils.kt
keel-titus-plugin/src/test/kotlin/com/netflix/spinnaker/keel/titus/resource/TitusClusterExportTests.kt
keel-titus-plugin/src/test/kotlin/com/netflix/spinnaker/keel/titus/resource/TitusClusterHandlerTests.kt

I screwed up https://github.com/spinnaker/keel/pull/784.
This is a new PR with the same commit.

fix(export): export less & more correct

---

gradle.properties

This cuts the build time from ~4:30 to ~2:55 on my machine

enable gradle parallel mode

---

keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/titus/cluster/TitusClusterHandler.kt

This prevented clusters from being marked as "deployed" and therefore prevented the promotion flow from working.

fix(titus): publish events for all tags

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/actuation/ResourcePersister.kt

this should fix the error message so that it's correct. thanks for the spot!

fix(dupes): build the correct error message

---

keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlResourceRepository.kt

fix(resource): deleting also deletes last diff fingerprint

---

keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/docs/Description.kt
keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/docs/Optional.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/core/api/SubmittedDeliveryConfig.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/core/api/SubmittedResource.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/ec2/ClusterSpec.kt
keel-web/keel-web.gradle.kts
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/apidocs/AbstractSchemaCustomizer.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/apidocs/ApiAnnotationModelConverter.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/apidocs/DeliveryArtifactModelConverter.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/apidocs/JavaTimePropertyCustomizer.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/apidocs/KotlinOptionalPropertyConverter.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/apidocs/SubtypesModelConverter.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/apidocs/_apidocs.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/DeliveryConfigController.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/apidocs/ApiDocTests.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/apidocs/ApiTests.kt

- marked all properties as `nullable:  true/false` based on Kotlin data type.

Misc improvements to OpenAPI rendering

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/memory/InMemoryArtifactRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/memory/InMemoryDeliveryConfigRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/memory/InMemoryResourceRepository.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/ApplicationController.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/services/ApplicationService.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/ApplicationControllerTests.kt

fix(api): Make application API backwards-compatible again

---

keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/Environment.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/actuation/EnvironmentPromotionChecker.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/constraints/ConstraintState.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/CombinedRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/DeliveryConfigRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/KeelRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/memory/InMemoryDeliveryConfigRepository.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/actuation/EnvironmentPromotionCheckerTests.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlArtifactRepository.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlDeliveryConfigRepository.kt
keel-sql/src/main/resources/db/changelog/20200226-env-artifact-constraint-index.yml
keel-sql/src/main/resources/db/databaseChangeLog.yml

Fixes #858 
Fixes #859 
Fixes #860

fix(constraints): process old pending constraints, fix concurrency bug

---

keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlArtifactRepository.kt

fix(sql): Fix SQL query in artifact repository

---

.github/workflows/pr.yml

trying to debug our flakey test, so adding some gradle options for pr builds

chore(builds): add debug and stacktrace options

---

keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/UnhappyVetoRepositoryTests.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/UnhappyVetoRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/memory/InMemoryUnhappyVetoRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/veto/unhappy/UnhappyVeto.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/veto/UnhappyVetoTests.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlUnhappyVetoRepository.kt

fix(veto): fix for initial veto creation bug

---

.github/workflows/pr.yml

reverting debug logs for prs because I think I fixed the flakey test... 🤞

fix(build): turn off stacktrace logging

---

keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/keel/bakery/api/ImageSpec.kt

Rebaking is extremely unlikely to fix any bake problems. Let's not rebake unless the diff changes.
This pr uses some unhappy controls that asher put into place.
Alternatively to not rebaking, I could change this to rebake every day or every 6 hours instead. Thoughts?

fix(bake): let's not keep rebaking forever.

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/actuation/CheckScheduler.kt

...so that failing parallel coroutines under the same scope do not interrupt their siblings, which can cause unexpected side-effects like downstream requests killed mid-flight that we get no exception information for in the logs. Using `supervisorScope` ensures that the exception causing failure can be caught and logged.

fix(core): Add supervisorScope around coroutines in CheckScheduler

---

.github/workflows/release.yml

feat(coverage): Publish codecov metrics from release build

---

keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/keel/bakery/artifact/ImageHandler.kt
keel-bakery-plugin/src/test/kotlin/com/netflix/spinnaker/keel/bakery/artifact/ImageHandlerTests.kt

Previously I was trying to compare the base AMI version from the current application AMI to the base AMI _name_ from `BaseImageCache` resulting in infinite rebaking.

Compare base AMI versions properly

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/actuation/ResourceActuator.kt

With the recent changes to coroutine logging, the logs reveal that, for issue #951, the code is timing out in the [resolve](https://github.com/spinnaker/keel/blob/87028e7638fefcdd9dfbee0c449042f932b6970f/keel-core/src/main/kotlin/com/netflix/spinnaker/keel/actuation/ResourceActuator.kt#L177) function:
<details><summary>stack trace</summary>
```
kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 120000 ms
at (Coroutine boundary.()
at kotlinx.coroutines.DeferredCoroutine.await$suspendImpl(Builders.common.kt:99)
at com.netflix.spinnaker.keel.actuation.ResourceActuator$resolve$2.invokeSuspend(ResourceActuator.kt:195)
at com.netflix.spinnaker.keel.actuation.ResourceActuator$checkResource$2.invokeSuspend(ResourceActuator.kt:75)
at …
```

fix(resource): tweak thread model, add more debug logging

---

keel-retrofit/src/main/kotlin/com/netflix/spinnaker/keel/retrofit/AuthorizationHeadersInterceptor.kt

Adding `AuthenticatedRequest.propagate` to interceptor. This command will propagate a bunch of headers, but also automates creation of a request ID. Also added a user origin, which is somewhat important as well - if left unset, the rest of Spinnaker will assume this is a gate API-originating request, which it isn't.

fix(retrofit): Call propagate to get request ID, set user origin

---

keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/ExceptionHandler.kt

I noticed that the format of our custom error responses was different from the standard format used by Spring, which, in turn, required custom parsing in clients (e.g. in the `ImportDeliveryConfigTask` in orca).
This PR adds the missing fields in the response to look exactly like the standard Spring format.
Before:
```yaml
message: "Access denied. Please make sure you have access to the service account specified\
\ in your delivery config. If you do have access, check that the service account\
\ has access to this application along with all the cloud accounts included in the\
\ delivery config."
```
After:
```yaml
message: "Access denied. Please make sure you have access to the service account specified\
\ in your delivery config. If you do have access, check that the service account\
\ …
```

fix(errors): Replicate Spring's default error format for API errors

---

gradle.properties
keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/DeliveryConfig.kt
keel-bakery-plugin/src/test/kotlin/com/netflix/spinnaker/keel/bakery/artifact/ImageHandlerTests.kt
keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/CombinedRepositoryTests.kt
keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ResourceRepositoryTests.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/core/api/SubmittedDeliveryConfig.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlDeliveryConfigRepository.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/DeliveryConfigControllerTests.kt
keel-web/src/test/resources/examples/delivery-config-example.yml

default delivery config name

---

keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/ExceptionHandler.kt

Make authorization error messages as detailed as possible.

fix(errors): Improve authorization error messages further

---

keel-api/keel-api.gradle.kts

fix(build): Add missing kork-exceptions version

---

keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/Resource.kt
keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/CloudDriverService.kt
keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/model/AmazonLoadBalancer.kt
keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/model/ApplicationLoadBalancerModel.kt
keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/model/ClassicLoadBalancerModel.kt
keel-clouddriver/src/test/kotlin/com/netflix/spinnaker/keel/clouddriver/CloudDriverServiceTests.kt
keel-clouddriver/src/test/resources/loadBalancers.json
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/veto/Veto.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/veto/VetoEnforcer.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/veto/unhappy/UnhappyVeto.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/actuation/ResourceActuatorTests.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/veto/DummyVeto.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/veto/UnhappyVetoTests.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/veto/VetoEnforcerTests.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/ec2/ClusterDependencyContainer.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/ec2/ClusterSpec.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/vetos/RequiredLoadBalancerVeto.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/vetos/RequiredSecurityGroupVeto.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/ApplicationLoadBalancerHandlerTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClassicLoadBalancerHandlerTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/vetos/RequiredLoadBalancerVetoTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/vetos/RequiredSecurityGroupVetoTests.kt

Vetos for ensuring dependent security groups / load balancers exist

---

README.md
keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/CloudDriverService.kt
keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/MemoryCloudDriverCache.kt
keel-clouddriver/src/test/kotlin/com/netflix/spinnaker/keel/clouddriver/MemoryCloudDriverCacheTest.kt

fix(performance): Avoid retrieving all SGs when looking for one (reintroduced)

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/actuation/ResourceActuator.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/events/ResourceEvent.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/exceptions/InvalidRegexException.kt

Closes #1089 and adds other small improvements to logs for error conditions. More details in inline comments.

fix(logs): Improve logging of error conditions

---

keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/AdminController.kt

fix(admin): correctly grab url param

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/events/ResourceEvent.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/events/ResourceEventSerializationTests.kt

Fixes #1107 by reverting related changes in `ResourceCheckError`.
Added serialization/deserialization tests for all sub-classes of `ResourceEvent` to prevent future regressions.

fix(events): Fix deserialization of ResourceCheckError

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/actuation/ResourceActuator.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/actuation/IntermittentFailureTests.kt

Fixes https://github.com/spinnaker/keel/issues/1090
When I first created the diff fingerprinting, I wasn't sure if we'd need to clear it ever. Now I definitely feel we need to clear it. This pr is a very small fix plus a specific test reproducing the problem.

fix(veto): check again if previously was happy

---

keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/ec2/ApplicationLoadBalancerSpec.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/ec2/ClassicLoadBalancerSpec.kt

I feel like we shouldn't keep trying with load balancers if we can't fix the diff. Thoughts?

feat(lb): don't keep trying to fix a load balancer

---

keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlResourceRepository.kt

Event persistence is handled asynchronously, so when storing a resource for the first time, and attempting to persist the corresponding `ResourceCreated` event, there's a race condition to read the `resource` record from the DB.
This fixes that by introducing retries.

fix(db): Fix race condition for resource record

---

keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlResourceRepository.kt

Missed a little something (retries don't just happen automagically, you need an exception).

fix(db): Force retry of resource uid lookup

---

keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ResourceRepositoryTests.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlResourceRepository.kt
keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/SqlResourceRepositoryTests.kt

Complement to #1138.
See also #1189.

test(sql): Test retries around race condition storing/reading resource

---

keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/keel/bakery/constraint/ImageExistsConstraintEvaluator.kt

Everything is great, nothing to see here.

fix(constraint): make image exists a component

---

keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/titus/cluster/TitusClusterHandler.kt
keel-titus-plugin/src/test/kotlin/com/netflix/spinnaker/keel/titus/resource/TitusClusterExportTests.kt

Fixing titus export where we don't correctly export the container resource section.

fix(titus): export container resources

---

build.gradle.kts

Oops (not sure why this broke, but oh well).

fix(build): Fix build repos for jacoco tasks

---

keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ApplicationLoadBalancerHandler.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClassicLoadBalancerHandler.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandler.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/SecurityGroupHandler.kt
keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/titus/cluster/TitusClusterHandler.kt

chore(messages): User-friendly task descriptions

---

gradle.properties
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/ExceptionHandler.kt

fixes breakage from ResourceType enum -> class change
closes #1338

chore(dependencies): fiat 1.21.0

---

keel-sql/keel-sql.gradle.kts

Previous updates were blocked by ayedo/jooq-modelator#16

Update JOOQ Modelator plugin

---

gradle.properties
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/apidocs/AbstractSchemaCustomizer.kt

Apparently behavior around boolean properties in API docs changed

Upgrade kork, and fix stuff it breaks

---

keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/jackson/ClusterSpecDeserializer.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/api/ec2/ClusterSpecTests.kt

Using a custom deserializer for `ClusterSpec` broke assignment of `locations` based on the environment.

Fix environment level locations for clusters

---

gradle.properties
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/info/InstanceIdSupplier.kt
keel-eureka/keel-eureka.gradle.kts
keel-eureka/src/main/kotlin/com/netflix/spinnaker/config/EurekaConfiguration.kt
keel-eureka/src/main/kotlin/com/netflix/spinnaker/config/EurekaDisabledConfiguration.kt
keel-eureka/src/main/kotlin/com/netflix/spinnaker/keel/eureka/DiscoveryActivator.kt
keel-eureka/src/main/kotlin/com/netflix/spinnaker/keel/eureka/EurekaInstanceIdSupplier.kt
keel-eureka/src/main/kotlin/com/netflix/spinnaker/keel/eureka/LocalInstanceIdSupplier.kt
keel-web/keel-web.gradle.kts
keel-web/src/main/kotlin/com/netflix/spinnaker/config/KeelConfigurationFinalizer.kt
settings.gradle.kts

We've been having issues with keel in prestaging which we suspect is related to a recent bump in kork. Reverting kork version to the last known good one where keel was healthy.

fix(deps): revert kork

---

keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/ArtifactController.kt

It's hard to troubleshoot things without logs...

debug(artifacts): Add more debug logs

---

keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/events/artifacts.kt
keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/plugins/ArtifactSupplier.kt

fix(artifacts): Fix artifact event publishing

---

keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/plugins/ResourceHandler.kt

refactor(plugins): Annotate default ResourceHandler methods with @JvmDefault

---

keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/ExtensionsController.kt

Useful to see if plugins are installed among other things

Endpoint to list supported extensions

---

.github/workflows/build.yml
.github/workflows/pr.yml
.github/workflows/release.yml
.mergify.yml
keel-core-test/src/main/kotlin/com/netflix/spinnaker/time/MutableClock.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/DiffFingerprintRepository.kt

Fixes a couple of things that didn't work with Java 11, and makes GH Actions use Java 11.

Java 11 Compatibility

---

keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/plugins/Resolver.kt

So the instance profiles plugin can use the proper pf4j mechanism

Make Resolver a SpinnakerExtensionPoint

---

keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/plugins/KeelServiceSdk.kt

fix(plugins): Add marker interface for KeelServiceSdk

---

keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/constraints/ConstraintState.kt
keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/DeliveryConfigRepositoryTests.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/DeliveryConfigRepository.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlDeliveryConfigRepository.kt

Follow-up to #1414. This should do it.

fix(constraints): Fix the fix for reading/updating constraints

---

keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/Environment.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/actuation/EnvironmentConstraintRunner.kt

Just adding some more logs to key spots in the artifact approval flow to help troubleshoot issues.

chore(logs): Improve logging for artifact approval flow

---

build.gradle.kts
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/ExceptionHandler.kt

Kotlin 1.4

---

keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/titus/cluster/TitusClusterHandler.kt

Follow-up to #1448. Determining current state was failing when there's no existing server group (when clouddriver returns 404).

fix(titus): Handle 404s when getting server groups

---

keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/persistence/KeelReadOnlyRepository.kt
keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ArtifactRepositoryTests.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ArtifactRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/CombinedRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/services/ApplicationService.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/services/ApplicationServiceTests.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlArtifactRepository.kt

Fixes exceptions retrieving artifact summaries.

fix(artifacts): Fix for exceptions retrieving new artifact metadata

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/artifacts/NetflixSemVerVersioningStrategy.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/artifacts/NetflixSemverVersioningStrategyTests.kt

Fixes issues parsing variants of semantic version strings used at Netflix.

fix(artifacts): Fix parsing of Netflix semantic versions

---

keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlArtifactRepository.kt

Add debug statements to help us debug an issue where the database does not seem to be getting updated.

fix(db): add logging statements for debugging

---

build.gradle.kts

Kotlin 1.4.10

---

keel-igor/src/main/kotlin/com/netflix/spinnaker/keel/services/ArtifactMetadataService.kt

As per https://github.com/resilience4j/resilience4j/issues/688 and many other open issues against resilience4j, it doesn't handle Kotlin exceptions properly. This is an attempt to work around it or at least get better debug logs.

fix(artifacts): Workaround for resilience4j bug around coroutines

---

keel-sql/keel-sql.gradle.kts

Fixes Gradle build so that `jooqGenerate` only runs when necessary

Jooq incremental build

---

keel-schema-generator/src/main/kotlin/com/netflix/spinnaker/keel/schema/Generator.kt
keel-schema-generator/src/main/kotlin/com/netflix/spinnaker/keel/schema/TagVersionStrategySchemaCustomizer.kt
keel-schema-generator/src/test/kotlin/com/netflix/spinnaker/keel/schema/GeneratorTests.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/config/DefaultConfiguration.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/apidocs/ApiDocCompatibilityTests.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/ConvertExampleFilesTest.kt
keel-web/src/test/resources/examples/alb-example.yml
keel-web/src/test/resources/examples/clb-example.yml
keel-web/src/test/resources/examples/cluster-example.yml
keel-web/src/test/resources/examples/ec2-cluster-with-autoscaling-example.yml
keel-web/src/test/resources/examples/minimal.yml
keel-web/src/test/resources/examples/security-group-example.yml
keel-web/src/test/resources/examples/simple-titus-cluster-example.yml
keel-web/src/test/resources/examples/titus-cluster-example.yml
keel-web/src/test/resources/examples/titus-cluster-with-artifact-example.yml

Pulled and anonymized some example data from the real database as some of our examples were a little stale.

more test cases for schema validation

---

keel-echo/src/main/kotlin/com/netflix/spinnaker/keel/echo/ManualJudgementNotifier.kt
keel-echo/src/test/kotlin/com/netflix/spinnaker/keel/echo/ManualJudgementNotifierTests.kt

Follow-up to #1522. Forgot the commit message... 🤦‍♂️

feat(notifications): Add commit message to Slack notifications

---

keel-schema-generator/src/main/kotlin/com/netflix/spinnaker/keel/schema/Generator.kt
keel-schema-generator/src/main/kotlin/com/netflix/spinnaker/keel/schema/Schema.kt
keel-schema-generator/src/test/kotlin/com/netflix/spinnaker/keel/schema/GeneratorTests.kt

D'oh, missed this in #1538 
Also added some more tests.

should be able to specify additionalProperties: false on root

---

keel-igor/src/main/kotlin/com/netflix/spinnaker/keel/services/ArtifactMetadataService.kt

Doubles the number of retries for artifact metadata and spaces them out over a longer period to improve our chances. Also logs retries dues to empty results from Igor/Rocket.

fix(artifacts): Increase number/duration of retries for artifact metadata

---

keel-clouddriver/keel-clouddriver.gradle.kts
keel-orca/keel-orca.gradle.kts
keel-sql/src/main/resources/jooqConfig.xml

Now we're running on Java 11 we can have JOOQ add the @Generated annotation to generated source files

JOOQ @Generated annotation

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/events/ResourceHealthEvent.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandler.kt
keel-echo/src/main/kotlin/com/netflix/spinnaker/keel/echo/UnhealthyNotificationListener.kt
keel-echo/src/test/kotlin/com/netflix/spinnaker/keel/echo/UnhealthyNotificationListenerTests.kt
keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/titus/TitusClusterHandler.kt
keel-titus-plugin/src/test/kotlin/com/netflix/spinnaker/keel/titus/resource/TitusClusterHandlerTests.kt

Updating the subject of the notification to have a list of regions

feat(notifications): add region to unhealthy

---

keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/plugins/ResourceHandler.kt

Adding this annotation so plugins get the default value

fix(handlers): add jvmdefault annotation to new method

---

keel-schema-generator/keel-schema-generator.gradle.kts

fix(build): java-library plugin seems to be required for publishing

---

keel-echo/src/main/kotlin/com/netflix/spinnaker/config/UnhealthyNotificationConfig.kt
keel-echo/src/test/kotlin/com/netflix/spinnaker/keel/echo/UnhealthyNotificationListenerTests.kt

5 minutes is too short to recover from chaos monkey

chore(unhealthy): up timeout because lots of unactionable notifications

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/actuation/ResourceActuator.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/actuation/ResourceActuatorTests.kt

Ran into this bug with Ludo's app because the plugin does not override the `willTakeAction` method (yet), and was returning an empty list of tasks since there was nothing to do, but keel didn't check if the list was empty. We ended up recording 5 "actuations" and vetoing the resource for no reason.

fix(actuation): Fix handling of empty actuation task list

---

keel-cli/src/main/kotlin/com/netflix/spinnaker/config/KeelCliConfiguration.kt
keel-ec2-api/src/main/kotlin/com/netflix/spinnaker/keel/api/ec2/ec2.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/migrators/ApplicationLoadBalancerV1ToV1_1Migrator.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/migrators/ClusterV1ToV1_1Migrator.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/api/ec2/export/ClusterExportTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resolvers/ImageResolverTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandlerTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/LaunchConfigTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/vetos/RequiredSecurityGroupVetoTests.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/ConvertExampleFilesTest.kt

Mostly old references in tests

update remaining references to ec2/cluster@v1

---

keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/jackson/SecurityGroupSpecDeserializer.kt

Jackson's fun API strikes again

fix(deserialization): fix NPE in nested deserialization

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/actuation/EnvironmentPromotionChecker.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/telemetry/TelemetryEvent.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/telemetry/TelemetryListener.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/actuation/EnvironmentPromotionCheckerTests.kt

To help us pin down problematic apps.

Graph time spent doing environment check by app

---

Dockerfile.compile

Fixing the typo in the compile script
@plumpy

fix(compile): fixing gradle property for Dockerfile.compile

---

keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/UnhappyVetoRepositoryTests.kt
keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/UnhealthyRepositoryTests.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/UnhappyVetoRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/UnhealthyRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/veto/unhappy/UnhappyVeto.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/actuation/IntermittentFailureTests.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/veto/UnhappyVetoTests.kt
keel-echo/src/main/kotlin/com/netflix/spinnaker/keel/echo/UnhealthyNotificationListener.kt
keel-echo/src/test/kotlin/com/netflix/spinnaker/keel/echo/UnhealthyNotificationListenerTests.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlArtifactRepository.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlDeliveryConfigRepository.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlResourceRepository.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlUnhappyVetoRepository.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlUnhealthyRepository.kt
keel-sql/src/main/resources/db/changelog/20201116-foreign-keys.yml
keel-sql/src/main/resources/db/databaseChangeLog.yml
keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/SqlUnhappyVetoRepositoryTests.kt
keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/SqlUnhealthyRepositoryTests.kt

Added foreign keys for tables that don't need schema changes in order to accommodate them.
Still to-do (because they need changes to the table structure):

Foreign keys

---

keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/tx/DeliveryConfigDeletionTests.kt

Luis pointed out in a comment on #1660 that there wasn't a test to confirm cascade delete behavior. I had thought there was but when I went looking I couldn't find it. This PR adds one.

test for cascading deletes from delivery config

---

keel-sql/src/main/resources/db/changelog/20201120-foreign-keys-for-verification-table.yml
keel-sql/src/main/resources/db/databaseChangeLog.yml

I hadn't merged the PR for adding the `verification_state` table before opening #1660 so I missed these

foreign keys for verification_state table

---

keel-web/config/keel.yml

fix(config): add fake baseUrl

---

keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/DeliveryConfigRepositoryTests.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/events/ApplicationEvent.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/events/PersistentEvent.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/events/ResourceEvent.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlDeliveryConfigRepository.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlResourceRepository.kt
keel-sql/src/main/resources/db/changelog/20201203-cleanup-event-and-paused-orhpans.yml
keel-sql/src/main/resources/db/databaseChangeLog.yml
keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/SqlDeliveryConfigRepositoryTests.kt

Complements #1660 to close #1467.

fix(sql): Cascade deletion of delivery config to event and paused records

---

keel-igor/src/main/kotlin/com/netflix/spinnaker/keel/igor/BuildLifecycleMonitor.kt

fix(buildLifecycle): use completed at time for ending time

---

keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/artifacts/BuildMetadata.kt

fix(build): FAILED -> FAILURE

---

keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/LifecycleEventRepositoryTests.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlLifecycleEventRepository.kt

We've been creating build time events with a `RUNNING` status after a `SUCCEEDED` status. I think this is because the API we're hitting doesn't update right away so we could be querying for the status of the build when it has finished but the API doesn't reflect it yet.
To deal with this data I'm looking specifically for "completed" events (like succeeded, failed, etc) to use as the terminal event when calculating text / time / status.

fix(build): out of order timestamps

---

build.gradle.kts

Updates Kotlin Gradle plugins to match version from Kork

update Kotlin Gradle plugin to match version in Kork

---

keel-sql/src/main/kotlin/com/netflix/spinnaker/config/SqlConfiguration.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/jooq/jsonConverters.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/ArtifactUtils.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlArtifactRepository.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlDeliveryConfigRepository.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlLifecycleEventRepository.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlLifecycleMonitorRepository.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlResourceRepository.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/deliveryconfigs/deliveryconfigs.kt
keel-sql/src/main/resources/jooqConfig.xml
keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/SqlLifecycleEventRepositoryTests.kt
keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/SqlLifecycleMonitorRepositoryTests.kt

I didn't do all the columns as some are more complex than others, but this is a start.

parse/convert some JSON columns automatically

---

gradle.properties
keel-sql/keel-sql.gradle.kts
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlArtifactRepository.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlDeliveryConfigRepository.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlLifecycleMonitorRepository.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlResourceRepository.kt

Had to make the Gradle plugin use the same version of JOOQ as Kork. Also JOOQ has added `@Nullable` and `@NotNull` annotations to method signatures so there were a couple of minor updates required.

Fixed JOOQ bump from Kork

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/jackson/KeelApiModule.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/jackson/mixins/VerificationMixin.kt
keel-titus-api/src/main/kotlin/com/netflix/spinnaker/keel/api/titus/TestContainerVerification.kt
keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/titus/verification/TestContainerVerificationEvaluator.kt
keel-titus-plugin/src/test/kotlin/com/netflix/spinnaker/keel/titus/verification/TestContainerVerificationEvaluatorTests.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/config/KeelConfigurationFinalizer.kt

wiring to support parsing verification sub-types

---

keel-web/src/test/kotlin/com/netflix/spinnaker/keel/apidocs/ApiDocCompatibilityTests.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/apidocs/ApiDocTests.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/integration/AuthPropagationTests.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/integration/SchedulingResilienceTests.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/integration/SpringStartupTests.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/AdminControllerTests.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/ApplicationControllerTests.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/ApplicationEventTests.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/ErrorSimulationControllerTests.kt

Just tidying up some test annotations

chore(tests): fixed some unnecessary complexity in test annotations

---

keel-sql/src/main/resources/db/changelog/20201218-add-environment-verify-with.yml

fix(verifications): correct dumb mistake in liquibase update

---

keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlVerificationRepository.kt

Not clear why this doesn't happen in tests using MySQL testcontainer. It seems like an insert statement that does not set the required column `started_at` is rejected. Even though in practice if we weren't setting `started_at` we'd always be falling back to the `on duplicate key update` clause.

fix insert statement that doesn't always set required column

---

keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/titus/verification/TestContainerVerificationEvaluator.kt

Useful and consistent with deploy tasks

Add artifact version to verification task name

---

gradle.properties
keel-sql/keel-sql.gradle.kts
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlArtifactRepository.kt

Fix autobumped kork version

---

keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/verification/VerificationRepository.kt
keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/VerificationRepositoryTests.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlVerificationRepository.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/VerificationController.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/VerificationControllerTests.kt

Similar to the endpoint for constraints

add endpoint to override verification status

---

gradle.properties
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/actuation/ResourceActuatorTests.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/telemetry/TelemetryListenerTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/api/ec2/constraints/Ec2CanaryConstraintDeployHandlerTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/ApplicationLoadBalancerHandlerTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClassicLoadBalancerHandlerTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandlerTests.kt
keel-titus-plugin/src/test/kotlin/com/netflix/spinnaker/keel/titus/resource/TitusClusterHandlerTests.kt

Had to make some changes around the use of MockK's `capture` method. Fixes #1745

Fixed Kork bump

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/actuation/CheckScheduler.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/actuation/CheckSchedulerTests.kt

Fast property-ing the minimum age for checking things. This metric controls how often we check the resource, artifact, or environment. I'm adding a fast property so that we can experiment with a smaller duration between checks (60s -> 30s) and have a way to quickly roll back changes.
Note: we use the `resource` specific config for all entities we check. I'm not changing that in this PR. I can change it in the future if we decide we need to tune each entity separately.

chore(config): fast property-ing min age duration

---

keel-orca/src/main/kotlin/com/netflix/spinnaker/keel/orca/ClusterExportHelper.kt

a user hit an NPE here, so making it more safe

fix(export): handle nulls

---

.github/workflows/periodic_release.yml

Maybe I should just trigger this on some other event to test... 😅

chore(release): Change cron schedule to test weekly release

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/services/ApplicationService.kt

My PR #1783 broke the API called by the environments view. The code is behind a feature toggle, `keel.verifications.summary.enabled` but even with that toggle disabled, the code was still throwing exceptions.
Quick change to broaden the scope of that feature toggle to cover the code throwing the exception. This puts the master branch back in a good state while I debug this properly.

fix(api): increase scope of verify api feature toggle

---

gradle.properties
keel-ec2-plugin/keel-ec2-plugin.gradle.kts
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/api/ec2/ClusterSpecTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/api/ec2/SecurityGroupRuleTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resolvers/ImageResolverTests.kt
keel-retrofit-test-support/keel-retrofit-test-support.gradle.kts
keel-retrofit-test-support/src/main/kotlin/com/netflix/spinnaker/keel/retrofit/model/ModelParsingTestSupport.kt

Fix kork bump

---

keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/DeliveryConfigRepositoryTests.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlDeliveryConfigRepository.kt

Follow up to https://github.com/spinnaker/keel/pull/1795 because my git was wonky and I couldn't add this commit to that PR.

fix(pr): avoid a race condition

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/services/ApplicationService.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/services/ApplicationServiceTests.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/services/ComparableLinksTests.kt

feat(metrics): adding some timing

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/CombinedRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/KeelRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ResourceRepository.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlDeliveryConfigRepository.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlResourceRepository.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlUnhappyVetoRepository.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlUnhealthyRepository.kt
keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/SqlDeliveryConfigRepositoryPeriodicallyCheckedTests.kt
keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/SqlNotificationRepositoryTests.kt

fix sub-queries that assume resource id is unique

---

keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/VerificationController.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/VerificationControllerTests.kt

make verification control URLs consistent with other things

---

keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ResourceRepositoryTests.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlResourceRepository.kt

Because of the recent change to versioned resources (see #1811) the history of events for a resource may include events with more than one resource UID. This PR ensures we include all events in a resource's history, not just those for the latest version.

resource history should include events for all versions

---

keel-slack/src/main/kotlin/com/netflix/spinnaker/keel/slack/SlackService.kt

Trying to debug slack not sending messages. Adding a metric so we can see failure trends

chore(slack): get some better detail on error

---

keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/Environment.kt
keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/artifacts/PublishedArtifact.kt
keel-artifact/src/test/kotlin/com/netflix/spinnaker/keel/artifacts/DockerArtifactSupplierTests.kt
keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ArtifactRepositoryTests.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ArtifactRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/CombinedRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/KeelRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/services/ApplicationService.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/services/EnvironmentService.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/artifacts/NetflixVersionsTests.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/services/ApplicationServiceTests.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/services/ComparableLinksTests.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlArtifactRepository.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/EnvironmentController.kt

A new api for returning the resources and current artifacts for an application, by environment.

feat(api): add basic environments api

---

keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/verification/VerificationRepository.kt
keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/VerificationRepositoryTests.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/actuation/EnvironmentConstraintRunner.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/constraints/PendingVerificationsConstraintEvaluator.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/core/api/PendingVerificationsConstraint.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/verification/VerificationRunner.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/constraints/PendingVerificationsConstraintEvaluatorTests.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/verification/VerificationRunnerTests.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlVerificationRepository.kt

Re-introducing pending verifications constraint

Constraint to prevent deployment if verifications are pending

---

keel-slack/src/main/kotlin/com/netflix/spinnaker/keel/slack/callbacks/ManualJudgmentCallbackHandler.kt
keel-slack/src/main/kotlin/com/netflix/spinnaker/keel/slack/handlers/ArtifactDeploymentNotificationHandler.kt
keel-slack/src/main/kotlin/com/netflix/spinnaker/keel/slack/handlers/LifecycleEventNotificationHandler.kt
keel-slack/src/main/kotlin/com/netflix/spinnaker/keel/slack/handlers/MarkAsBadNotificationHandler.kt
keel-slack/src/main/kotlin/com/netflix/spinnaker/keel/slack/handlers/PausedNotificationHandler.kt
keel-slack/src/main/kotlin/com/netflix/spinnaker/keel/slack/handlers/PinnedNotificationHandler.kt
keel-slack/src/main/kotlin/com/netflix/spinnaker/keel/slack/handlers/UnpinnedNotificationHandler.kt
keel-slack/src/main/kotlin/com/netflix/spinnaker/keel/slack/handlers/VerificationCompletedNotificationHandler.kt

Updating to the new icons that greg designed

feat(notifications): new slack icons

---

keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlArtifactRepository.kt

Came across this race condition when trying to reproduce an issue with @ranihorev's test app:
```
2021-03-09 17:29:58.317 ERROR 6793 --- [   event-pool-1] .e.DefaultThreadUncaughtExceptionHandler : [] Uncaught exception in thread
com.netflix.spinnaker.keel.persistence.NoSuchArtifactException: No docker artifact named rhorev/dashboard is registered
at com.netflix.spinnaker.keel.sql.SqlArtifactRepository.versions(SqlArtifactRepository.kt:206)
at com.netflix.spinnaker.keel.persistence.CombinedRepository.artifactVersions(CombinedRepository.kt:353)
at com.netflix.spinnaker.keel.persistence.CombinedRepository$$FastClassBySpringCGLIB$$9cfcaa57.invoke(<generated>)
at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
at …
```

fix(artifacts): Retry the artifact registered check on delivery config upsert

---

keel-slack/src/main/kotlin/com/netflix/spinnaker/keel/slack/callbacks/ManualJudgmentCallbackHandler.kt

fix(slack): approved -> approve

---

keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/DeliveryConfigController.kt

unfortunately this is sending too many notifications right now, so adding a fast property control to switch it off while I investigate

chore(notif): add fast prop control to config changed

---

docs/database.md
docs/environment-exclusion/metrics.md
docs/verifications/links.md
keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/Verification.kt
keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/plugins/VerificationEvaluator.kt
keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/verification/VerificationRepository.kt
keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/VerificationRepositoryTests.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/core/api/ArtifactSummary.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/CombinedRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/KeelRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/verification/VerificationRunner.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/verification/VerificationRunnerTests.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlVerificationRepository.kt
keel-sql/src/main/resources/db/changelog/20210409-add-verif-link-column.yml
keel-sql/src/main/resources/db/databaseChangeLog.yml
keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/titus/verification/LinkStrategy.kt
keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/titus/verification/TestContainerVerificationEvaluator.kt
keel-titus-plugin/src/test/kotlin/com/netflix/spinnaker/keel/titus/verification/TestContainerVerificationEvaluatorTests.kt

Support for adding a link associated with a test container verification.

feat(verif): provide verification link in API

---

keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlDeliveryConfigRepository.kt
keel-sql/src/main/resources/db/changelog/20210419-actually-no-environment-features-per-version.yml
keel-sql/src/main/resources/db/databaseChangeLog.yml
keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/EnvironmentVersioningTests.kt

It doesn't actually provide any value to do this.

Undo versioning of environment config

---

keel-titus-api/src/main/kotlin/com/netflix/spinnaker/keel/api/titus/TestContainerVerification.kt
keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/titus/ContainerRunner.kt
keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/titus/verification/TestContainerVerificationEvaluator.kt

Allow user to specify an entrypoint on a test container verification.

feat(verif): add optional entrypoint

---

.gitignore

chore(git): Fix typo in .gitignore

---

build.gradle
gradle.properties

Attempt to fix missing `publishToNexus` task.

fix(build): Fix nexus publishing

---

keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/ArtifactInEnvironmentContext.kt
keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/persistence/KeelReadOnlyRepository.kt
keel-core/keel-core.gradle
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/CombinedRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/services/ApplicationService.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/services/ApplicationServiceTests.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/VerificationController.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/dgs/ActionsDataLoader.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/dgs/Mutations.kt
keel-web/src/main/resources/schema/schema.graphql

Upstreaming latest changes from Netflix.

chore(code): Upstream changes from Netflix

---

.gitignore
build.gradle
gradle/wrapper/gradle-wrapper.properties
keel-web/keel-web.gradle

Fixes an issue with DGS auto-configuration that was preventing keel from starting.

fix(graphql): Bump version of DGS to work around configuration issue

---

keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/ImageTagger.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/ImageTaggerTests.kt

wait until all verifications complete, don't tag with id
(cherry picked from commit 1980ef705345655a8bad4da88dac2ae3a7845246)

fix(tags): wait until all verifications complete, don't tag with id

---

keel-web/keel-web.gradle

bump com.netflix.graphql.dgs:graphql-dgs-platform-dependencies to a non-rc version

chore(gradle): bump lib version

---

keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/actuation/Job.kt
keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/model/TitusActiveServerGroup.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/jackson/PropertyNamePolymorphicDeserializer.kt
keel-ec2-api/src/main/kotlin/com/netflix/spinnaker/keel/api/ec2/Scaling.kt
keel-titus-api/src/main/kotlin/com/netflix/spinnaker/keel/api/titus/TitusClusterSpec.kt
keel-titus-api/src/main/kotlin/com/netflix/spinnaker/keel/api/titus/TitusServerGroup.kt
keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/titus/TitusClusterHandler.kt
keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/titus/_titusClusters.kt
keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/titus/jackson/KeelTitusApiModule.kt
keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/titus/jackson/TitusScalingPolicyDescriptorDeserializer.kt
keel-titus-plugin/src/test/kotlin/com/netflix/spinnaker/keel/titus/jackson/TitusActiveServerGroupDeserializationTests.kt
keel-titus-plugin/src/test/kotlin/com/netflix/spinnaker/keel/titus/resource/TestUtils.kt
keel-titus-plugin/src/test/kotlin/com/netflix/spinnaker/keel/titus/resource/TitusClusterScalingPolicyTests.kt
keel-titus-plugin/src/test/resources/titus-active-server-group-with-complex-scaling.json
keel-titus-plugin/src/test/resources/titus-active-server-group-with-scaling.json

Add support for Titus scaling policies
(cherry picked from commit 6ef9820e2479d78ef8b41aa688fdf6b295f88048)

feature(titus): scaling policies support

---

keel-notifications/src/main/kotlin/com/netflix/spinnaker/keel/notifications/slack/handlers/ArtifactDeploymentNotificationHandler.kt
keel-notifications/src/main/kotlin/com/netflix/spinnaker/keel/notifications/slack/handlers/DeliveryConfigNotificationHandler.kt
keel-notifications/src/main/kotlin/com/netflix/spinnaker/keel/notifications/slack/handlers/GitDataGenerator.kt
keel-notifications/src/main/kotlin/com/netflix/spinnaker/keel/notifications/slack/handlers/LifecycleEventNotificationHandler.kt
keel-notifications/src/main/kotlin/com/netflix/spinnaker/keel/notifications/slack/handlers/ManualJudgementUpdateHandler.kt
keel-notifications/src/main/kotlin/com/netflix/spinnaker/keel/notifications/slack/handlers/ManualJudgmentNotificationHandler.kt
keel-notifications/src/main/kotlin/com/netflix/spinnaker/keel/notifications/slack/handlers/MarkAsBadNotificationHandler.kt
keel-notifications/src/main/kotlin/com/netflix/spinnaker/keel/notifications/slack/handlers/PausedNotificationHandler.kt
keel-notifications/src/main/kotlin/com/netflix/spinnaker/keel/notifications/slack/handlers/PinnedNotificationHandler.kt
keel-notifications/src/main/kotlin/com/netflix/spinnaker/keel/notifications/slack/handlers/PluginNotificationHandler.kt
keel-notifications/src/main/kotlin/com/netflix/spinnaker/keel/notifications/slack/handlers/ResumedNotificationHandler.kt
keel-notifications/src/main/kotlin/com/netflix/spinnaker/keel/notifications/slack/handlers/UnpinnedNotificationHandler.kt
keel-notifications/src/main/kotlin/com/netflix/spinnaker/keel/notifications/slack/handlers/VerificationCompletedNotificationHandler.kt
keel-notifications/src/test/kotlin/com/netflix/spinnaker/keel/notifications/slack/handlers/GitDataGeneratorTests.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/SlackAppController.kt

Improved functionality around displaying slack notifications

feat(slack): improve slack notifications

---

keel-titus-api/src/main/kotlin/com/netflix/spinnaker/keel/api/titus/TestContainerVerification.kt

(cherry picked from commit 474729c7087aab22f881a86138b7b952b72851b7)

fix(verifications): avoid excessively long verification ids

---

keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/constraints/StatefulConstraintEvaluator.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/constraints/AllowedTimesConstraintEvaluator.kt

Squashed commit of the following:
commit bfea8ccb70e3c8c25d676ac14a3219a535973286
Author: Emily Burns <emburns@netflix.com>
Date:   Wed Jul 14 09:16:19 2021 -0700
fix(pr): style updates
commit fc9ab9db4733b54ce1347a390762fbd69b3ec338
Author: Emily Burns <emburns@netflix.com>
Date:   Tue Jul 13 09:52:40 2021 -0700
fix(constraints): only call plugin to reevaluate if it wants it
(cherry picked from commit 24c963f62145520b97687be5beff4dc7a7081918)

fix(constraints): only call plugin to reevaluate if it wants it

---

keel-ec2-api/src/main/kotlin/com/netflix/spinnaker/keel/api/ec2/Scaling.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandler.kt
keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/titus/TitusClusterHandler.kt
keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/titus/_titusClusters.kt

(cherry picked from commit 84fd4a3eee9962d08b5869589e05a26e3f6a243e)

fix(titus): add scaleInCooldown and scaleOutCooldown to scaling policy equals/hashCode

---

keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/plugins/PostDeployActionHandler.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/core/api/TagAmiPostDeployAction.kt
keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/titus/ContainerRunner.kt
keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/titus/postdeploy/TagAmiHandler.kt
keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/titus/verification/LinkStrategy.kt
keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/titus/verification/OrcaLinkStrategy.kt
keel-titus-plugin/src/test/kotlin/com/netflix/spinnaker/keel/titus/postdeploy/TagAmiHandlerTests.kt
keel-titus-plugin/src/test/kotlin/com/netflix/spinnaker/keel/titus/verification/OrcaLinkStrategyTests.kt

(cherry picked from commit 6110a6d3139352a6e284a9c18391775f5853501d)

feat(tagging): add a post deploy tag-ami option

---

keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/dgs/ApplicationFetcher.kt

(cherry picked from commit 4982fc9802e8db3c9a9742e77e37222796dcd6a6)

fix(config): fetch the config from stash if it was sent by orca

---

.github/workflows/build.yml
.github/workflows/periodic_release.yml
.github/workflows/pr.yml
.github/workflows/release.yml

closes: spinnaker/spinnaker#6611

chore(ci): update setup-java GHA to v2

---

keel-core/src/test/kotlin/com/netflix/spinnaker/keel/services/ComparableLinksTests.kt

Fixes #2026 by normalizing all sources to proper "links" with protocol prefixes before they are used by the gitMetadata mock generator.

fix(artifacts): add missing protocol prefixes for mocks

---

gradle/kotlin.gradle

follow up to https://github.com/spinnaker/keel/pull/2103

chore(dependency): update kotlin language version as leftover during upgrade kotlin from 1.5.32 to 1.6.21

---

gradle.properties
keel-ec2-plugin/keel-ec2-plugin.gradle
keel-web/keel-web.gradle

Refer to https://github.com/spinnaker/kork/pull/1198

fix(openapi): Migrate to openapi from kork
