spinnaker/keel

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/IntentProcessor.kt
keel-core/src/test/groovy/com/netflix/spinnaker/keel/dryrun/DryRunIntentLauncherSpec.groovy
keel-intents/src/main/kotlin/com/netflix/spinnaker/keel/intents/processors/ApplicationIntentProcessor.kt
keel-intents/src/main/kotlin/com/netflix/spinnaker/keel/intents/processors/ParrotIntentProcessor.kt
keel-intents/src/main/kotlin/com/netflix/spinnaker/keel/intents/processors/SecurityGroupIntentProcessor.kt

I didn't like that the dry-run functionality had empty reasons. I want to avoid the whole Orca "No reason provided" fiasco in keel outputs. Future refactoring will be done to give additional context around actual operations that are performed (rather than just outputting the name of the affected app). Dry run is still pretty useless:
```json
[
{
"reason": "System state does not match desired state",
"steps": [
{
"name": "Upsert security group",
"description": "Converging on desired security group state",
"operations": [
"keel"
]
}
]
},
{
"reason": "Application does not exist",
"steps": [
{
"name": "Create application",
"description": "Converging on desired application state",
"operations": [
"keel"
]
}
]
}
]
```

fix(dryrun): Require converge reason

---

keel-front50/src/main/kotlin/com/netflix/spinnaker/keel/front50/model/Application.kt
keel-intents/src/main/kotlin/com/netflix/spinnaker/keel/intents/ApplicationIntent.kt
keel-intents/src/main/kotlin/com/netflix/spinnaker/keel/intents/processors/ApplicationIntentProcessor.kt
keel-intents/src/test/groovy/com/netflix/spinnaker/keel/intents/processors/ApplicationIntentProcessorSpec.groovy
keel-orca/src/main/kotlin/com/netflix/spinnaker/keel/orca/OrcaIntentLauncher.kt
keel-orca/src/main/kotlin/com/netflix/spinnaker/keel/orca/OrcaService.kt

Actually fixes a few issues.
* Fixes ops endpoint headers
* Application orchestration wrapper
* Improves logging of orchestrations
* Scaffold diffing for ApplicationIntent
* Correctly marking optional NetflixApplicationIntentSpec fields.

fix(orca): Fix ops endpoint

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/Intent.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/IntentRepository.kt
keel-front50/src/main/kotlin/com/netflix/spinnaker/config/Front50Configuration.kt
keel-front50/src/main/kotlin/com/netflix/spinnaker/keel/front50/Front50IntentRepository.kt
keel-front50/src/main/kotlin/com/netflix/spinnaker/keel/front50/Front50Service.kt
keel-scheduler/src/main/kotlin/com/netflix/spinnaker/keel/scheduler/handler/ScheduleConvergeHandler.kt
keel-test/src/main/kotlin/com/netflix/spinnaker/keel/test/TestIntent.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/controllers/v1/IntentController.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/model/UpsertIntentRequest.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/web/config/WebConfiguration.kt

- Adding support for front50
- changing get by status API to use parameter `status` instead of `statuses` for filtering by status. still is a list.

feat(front50): adding front50 support for intents

---

keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/config/ClouddriverConfiguration.kt
keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/ClouddriverService.kt
keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/model/Credential.kt
keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/model/Network.kt
keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/okhttp/AccountProvidingNetworkInterceptor.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/config/KeelConfiguration.kt
keel-intents/src/main/kotlin/com/netflix/spinnaker/keel/intents/SecurityGroupIntent.kt
keel-intents/src/main/kotlin/com/netflix/spinnaker/keel/intents/processors/SecurityGroupIntentProcessor.kt
keel-intents/src/main/kotlin/com/netflix/spinnaker/keel/intents/processors/converters/SecurityGroupConverter.kt
keel-intents/src/main/kotlin/com/netflix/spinnaker/keel/intents/processors/converters/SpecConverter.kt
keel-intents/src/test/groovy/com/netflix/spinnaker/keel/intents/processors/SecurityGroupIntentProcessorSpec.groovy
keel-intents/src/test/groovy/com/netflix/spinnaker/keel/intents/processors/converters/SecurityGroupConverterSpec.groovy
keel-retrofit/src/main/kotlin/com/netflix/spinnaker/keel/retrofit/RetrofitConfiguration.kt

Includes a naive authorization strategy for protected clouddriver
accounts. More work will be necessary via Fiat, but this gets us
started.
I still need to work on getting ingress rules working, but want to keep my PRs somewhat smaller.

feat(intent): Basic security group intent convergence

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/attribute/attributes.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/filter/ExecutionWindowFilter.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/policy/Policy.kt
keel-core/src/test/groovy/com/netflix/spinnaker/keel/filter/ExecutionWindowFilterSpec.groovy
keel-redis/src/test/groovy/com/netflix/spinnaker/keel/redis/RedisTraceRepositorySpec.groovy
keel-test/src/main/kotlin/com/netflix/spinnaker/keel/test/TestIntent.kt

We support execution windows in Orca at the stage-level, but not at the entire orchestration/pipeline level. This adds support for execution windows around converge times, which can be helpful for ensuring deployments or infrastructure changes don't occur in peak times.
Primarily a showcase for how Attributes & Filters work.
cc @emjburns @robfletcher

feat(core): Intent-level execution window support

---

keel-core/keel-core.gradle
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/filter/ExecutionWindowFilter.kt
keel-intents/src/main/kotlin/com/netflix/spinnaker/keel/intents/processors/ApplicationIntentProcessor.kt
keel-intents/src/main/kotlin/com/netflix/spinnaker/keel/intents/processors/SecurityGroupIntentProcessor.kt
keel-orca/src/main/kotlin/com/netflix/spinnaker/keel/orca/OrcaIntentLauncher.kt
keel-scheduler/src/main/kotlin/com/netflix/spinnaker/keel/scheduler/handler/ConvergeIntentHandler.kt
keel-web/keel-web.gradle

FYI @robfletcher @emjburns -- Any logs you do from here on out, structured. `value("intent", intentId)` should be used any place that you're logging about a specific intent (should make tracing intent behavior in logs pretty clear). Prefer the intent ID over `kind`, since the ID will include the intent kind anyway.

chore(*): Converting to structured logs where applicable

---

keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/model/SecurityGroup.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/annotation/Computed.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/state/ComputedPropertyProvider.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/state/StateInspector.kt
keel-front50/src/main/kotlin/com/netflix/spinnaker/keel/front50/model/Application.kt
keel-intent/src/main/kotlin/com/netflix/spinnaker/keel/intent/ApplicationIntent.kt
keel-intent/src/main/kotlin/com/netflix/spinnaker/keel/intent/processor/ApplicationIntentProcessor.kt
keel-intent/src/main/kotlin/com/netflix/spinnaker/keel/intent/processor/SecurityGroupIntentProcessor.kt
keel-intent/src/main/kotlin/com/netflix/spinnaker/keel/intent/processor/converter/SecurityGroupConverter.kt
keel-intent/src/test/kotlin/com/netflix/spinnaker/keel/intent/processor/ApplicationIntentProcessorTest.kt
keel-intent/src/test/kotlin/com/netflix/spinnaker/keel/intent/processor/SecurityGroupIntentProcessorTest.kt
keel-intent/src/test/kotlin/com/netflix/spinnaker/keel/intent/processor/converter/SecurityGroupConverterTest.kt

Builds on the work that @emjburns did for the `@Computed` annotation, moving some of the functionality into a utility `StateInspector` class and implemented for both `ApplicationIntent` and `SecurityGroupIntent`.
While it all works, I don't think it's as good as it could be. I'm running into some type erasure issues (and fun reified generics issues) that prevent me from runtime processing the computed annotations on Specs, so I created an interface that provides additional ignoreable fields. I'd really like to get rid of this, since it'll make auto-generating API docs / json schemas substantially more difficult.

feat(core): Generic computed functionality; security group diffing support

---

keel-clouddriver/dependencies.lock
keel-clouddriver/keel-clouddriver.gradle
keel-core/dependencies.lock
keel-core/keel-core.gradle
keel-eureka/dependencies.lock
keel-front50/dependencies.lock
keel-intent-aws/dependencies.lock
keel-orca/dependencies.lock
keel-redis/dependencies.lock
keel-retrofit/dependencies.lock
keel-retrofit/keel-retrofit.gradle
keel-scheduler/dependencies.lock
keel-test/dependencies.lock
keel-web/dependencies.lock
keel-web/keel-web.gradle

Attempting to `+` major versions caused some anarchy, so reigned it in a little bit on the versions that we can jump across on.

chore(*): Constrain dependency lock versions

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/IntentActivityRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/memory/MemoryIntentActivityRepository.kt
keel-orca/src/main/kotlin/com/netflix/spinnaker/keel/orca/OrcaExecutionStatus.kt
keel-orca/src/main/kotlin/com/netflix/spinnaker/keel/orca/OrcaService.kt
keel-redis/src/main/kotlin/com/netflix/spinnaker/keel/redis/RedisIntentActivityRepository.kt
keel-scheduler/src/main/kotlin/com/netflix/spinnaker/keel/scheduler/handler/ConvergeIntentHandler.kt
keel-scheduler/src/main/kotlin/com/netflix/spinnaker/keel/scheduler/handler/MonitorOrchestrationsHandler.kt
keel-scheduler/src/main/kotlin/com/netflix/spinnaker/keel/scheduler/messages.kt
keel-scheduler/src/test/kotlin/com/netflix/spinnaker/keel/scheduler/handler/MonitorOrchestrationsHandlerTest.kt

We'd like to track, by intent kind, whether orchestrations for an intent succeed or fail. This is a first pass at that.

feat(activity): monitor and emit metrics on orch status

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/IntentProcessor.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/dryrun/ChangeSummary.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/dryrun/DryRunIntentLauncher.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/dryrun/DryRunIntentLauncherTest.kt
keel-intent/src/main/kotlin/com/netflix/spinnaker/keel/intent/processor/ApplicationIntentProcessor.kt
keel-intent/src/main/kotlin/com/netflix/spinnaker/keel/intent/processor/ParrotIntentProcessor.kt
keel-intent/src/main/kotlin/com/netflix/spinnaker/keel/intent/processor/SecurityGroupIntentProcessor.kt
keel-intent/src/main/kotlin/com/netflix/spinnaker/keel/intent/processor/converter/ApplicationConverter.kt
keel-intent/src/main/kotlin/com/netflix/spinnaker/keel/intent/processor/converter/LoadBalancerConverter.kt
keel-intent/src/main/kotlin/com/netflix/spinnaker/keel/intent/processor/converter/SecurityGroupConverter.kt
keel-intent/src/main/kotlin/com/netflix/spinnaker/keel/intent/processor/converter/SpecConverter.kt
keel-intent/src/test/kotlin/com/netflix/spinnaker/keel/intent/processor/SecurityGroupIntentProcessorTest.kt
keel-intent/src/test/kotlin/com/netflix/spinnaker/keel/intent/processor/converter/SecurityGroupConverterTest.kt
keel-orca/src/main/kotlin/com/netflix/spinnaker/keel/orca/OrcaIntentLauncher.kt
keel-scheduler/src/test/kotlin/com/netflix/spinnaker/keel/scheduler/handler/ConvergeIntentHandlerTest.kt

Trying to improve the messaging around dry run. Have added the type of change to be made, a summary (which I want to act like a list of steps that were taken while putting together the tasks submitted to orca), and the diff. 
My hope is that intent creators will add messaging to the summary so someone who submits this intent will be able to see something like:
```
Generating job for upsertSecurityGroup,
Adding port range support,
Creating dependent security group blah
Generating job for upsertSecurityGroup blah
Adding ingress rules for security group blah
```
along with the diff to tell what the final value of the fields are going to be.
I think this needs to be massaged as we continue development. Suggestions welcome!

feat(dryRun): improve dry run messaging a bit

---

keel-clouddriver/dependencies.lock
keel-core/dependencies.lock
keel-core/keel-core.gradle
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/Intent.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/annotation/Computed.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/attribute/attributes.kt
keel-echo/dependencies.lock
keel-eureka/dependencies.lock
keel-front50/dependencies.lock
keel-intent-aws/dependencies.lock
keel-intent/dependencies.lock
keel-orca/dependencies.lock
keel-redis/dependencies.lock
keel-retrofit/dependencies.lock
keel-scheduler/dependencies.lock
keel-test/dependencies.lock
keel-web/dependencies.lock
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/controllers/v1/SchemaController.kt

Kicking around the idea of exposing model JSON schemas for external client use. This could be handy for people who want to build DSLs / templating around Keel, as well as generate clients.
Very much a WIP, but think this could be a decent way to keep things documented. Still some wonkiness around subtypes (seems to only be direct children that are supported) and inheriting property descriptions, as well as auto-adding schema properties from other annotations (like `@Computed`).

feat(web): API for retrieving JSON schema of models

---

keel-intent/src/main/kotlin/com/netflix/spinnaker/keel/intent/processor/SecurityGroupIntentProcessor.kt

This field is not mutable in clouddriver so we shouldn't consider it in the diff.

fix(securityGroup): sg description is not mutable in clouddriver

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/annotation/ForcesNew.kt
keel-intent/src/main/kotlin/com/netflix/spinnaker/keel/intent/PipelineIntent.kt

I don't really expect we'll be able to get keel to strongly type pipelines this quarter. Still made some schema changes from a keel perspective, however. Namely, boolean flags were thrown into a `flags` bucket, and feature toggles were thrown into a `properties` bucket. I type-casted the few things that I think will be sticking around for quite some time, but otherwise a map seems a good fit in here.

feat(intent): Scaffolding pipeline intent spec

---

keel-clouddriver/dependencies.lock
keel-core/dependencies.lock
keel-core/src/main/kotlin/com/netflix/spinnaker/config/KeelConfiguration.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/config/KeelProperties.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/config/KeelSubTypeLocator.kt
keel-echo/dependencies.lock
keel-eureka/dependencies.lock
keel-front50/dependencies.lock
keel-intent-aws/dependencies.lock
keel-intent/dependencies.lock
keel-intent/src/main/kotlin/com/netflix/spinnaker/config/IntentConfiguration.kt
keel-intent/src/main/kotlin/com/netflix/spinnaker/keel/intent/ParrotIntent.kt
keel-intent/src/main/kotlin/com/netflix/spinnaker/keel/intent/PipelineIntent.kt
keel-orca/dependencies.lock
keel-redis/dependencies.lock
keel-retrofit/dependencies.lock
keel-scheduler/dependencies.lock
keel-scheduler/src/main/kotlin/com/netflix/spinnaker/config/SchedulerConfiguration.kt
keel-test/dependencies.lock
keel-web/dependencies.lock

The upgrade from Keiko 1.x -> 2.x messed up how we handle object mapper subtypes. Originally, keiko didn't care about the subtype information that the rest of Keel uses for saving messages, but now we have to register to both the Keiko ObjectMapper as well as Keel's. I'm not super stoked on having two different ObjectMappers--I'll consolidate in a separate task--I just want things to not be broken.
Additionally, Keiko 2.x introduced a new `SpringObjectMapperConfigurer` for `NamedType` serialization. I'll be lifting that out into Kork so Keel can use that, rather than having two classpath scanning cycles at startup.
cc @emjburns

fix(*): Fixing keiko 2.x upgrade; fumbling around with objectmapper subtypes

---

keel-core/src/main/kotlin/com/netflix/spinnaker/config/KeelConfiguration.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/config/KeelProperties.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/IntentActivityRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/memory/MemoryIntentActivityRepository.kt
keel-intent/src/main/kotlin/com/netflix/spinnaker/keel/intent/processor/ApplicationIntentProcessor.kt
keel-intent/src/main/kotlin/com/netflix/spinnaker/keel/intent/processor/SecurityGroupIntentProcessor.kt
keel-orca/src/main/kotlin/com/netflix/spinnaker/keel/orca/OrcaIntentLauncher.kt
keel-redis/src/main/kotlin/com/netflix/spinnaker/keel/redis/RedisIntentActivityRepository.kt
keel-redis/src/test/kotlin/com/netflix/spinnaker/keel/redis/RedisIntentActivityRepositoryTest.kt
keel-scheduler/src/main/kotlin/com/netflix/spinnaker/keel/scheduler/handler/ConvergeIntentHandler.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/controllers/v1/IntentController.kt

In order to make logging more manageable for each intent for each convergence, I've moved everything but the `com.netflix.spinnaker.q.QueueProcessor   : [] Received message ConvergeIntent(` messages to the intentActivityRepository. 
Hitting `v1/intents/{intentId}/convergenceLog` will give you all the messages for each intent with the format 
```{
"intentId": "Application:emilykeeltest",
"changeType": "NO_CHANGE",
"orchestrations": [],
"messages": [
"System state matches desired state"
],
"diff": [],
"actor": "keel:scheduledConvergence",
"timeMs": 1516214128706
}
```
Each message is identified by its timestamp, which is created when the log message is created in `OrcaIntentLauncher`. This message is created right after orchestrations are launched in orca. …

feat(logging): convergence logging now in intentActivityRepo

---

keel-intent/src/main/kotlin/com/netflix/spinnaker/keel/intent/SecurityGroupIntent.kt
keel-intent/src/main/kotlin/com/netflix/spinnaker/keel/intent/processor/SecurityGroupIntentProcessor.kt
keel-intent/src/main/kotlin/com/netflix/spinnaker/keel/intent/processor/converter/SecurityGroupConverter.kt
keel-intent/src/main/kotlin/com/netflix/spinnaker/keel/intent/processor/converter/SpecConverter.kt
keel-intent/src/test/kotlin/com/netflix/spinnaker/keel/intent/SecurityGroupIntentTest.kt
keel-intent/src/test/kotlin/com/netflix/spinnaker/keel/intent/processor/SecurityGroupIntentProcessorTest.kt
keel-intent/src/test/kotlin/com/netflix/spinnaker/keel/intent/processor/converter/SecurityGroupConverterTest.kt

Refactoring the sg intent to be only a single region. This will allow people to have the same sg in different regions with different rules, etc.

fix(intent): Refactor security group to only map to a single region

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/Intent.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/filter/ExecutionWindowFilter.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/memory/MemoryIntentRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/memory/MemoryTraceRepository.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/dryrun/DryRunIntentLauncherTest.kt
keel-echo/src/main/kotlin/com/netflix/spinnaker/keel/echo/EventNotificationListener.kt
keel-intent-aws/src/main/kotlin/com/netflix/spinnaker/keel/intent/aws/loadbalancer/ClassicLoadBalancerIntentProcessor.kt
keel-intent-aws/src/main/kotlin/com/netflix/spinnaker/keel/intent/aws/securitygroup/AmazonSecurityGroupIntent.kt
keel-intent-aws/src/main/kotlin/com/netflix/spinnaker/keel/intent/aws/securitygroup/AmazonSecurityGroupIntentProcessor.kt
keel-intent/src/main/kotlin/com/netflix/spinnaker/keel/intent/ApplicationIntent.kt
keel-intent/src/main/kotlin/com/netflix/spinnaker/keel/intent/LoadBalancerIntent.kt
keel-intent/src/main/kotlin/com/netflix/spinnaker/keel/intent/ParrotIntent.kt
keel-intent/src/main/kotlin/com/netflix/spinnaker/keel/intent/PipelineIntent.kt
keel-intent/src/main/kotlin/com/netflix/spinnaker/keel/intent/processor/ApplicationIntentProcessor.kt
keel-intent/src/main/kotlin/com/netflix/spinnaker/keel/intent/processor/ParrotIntentProcessor.kt
keel-intent/src/main/kotlin/com/netflix/spinnaker/keel/intent/processor/PipelineIntentProcessor.kt
keel-orca/src/main/kotlin/com/netflix/spinnaker/keel/orca/OrcaIntentLauncher.kt
keel-redis/src/main/kotlin/com/netflix/spinnaker/keel/redis/RedisTraceRepository.kt
keel-scheduler/src/main/kotlin/com/netflix/spinnaker/keel/scheduler/handler/ConvergeIntentHandler.kt
keel-test/src/main/kotlin/com/netflix/spinnaker/keel/test/TestIntent.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/controllers/v1/IntentController.kt

User-defined IDs was providing very little value at the cost of unnecessary confusion.

chore(*): Remove capability to user-define intent ids

---

keel-scheduler/src/main/kotlin/com/netflix/spinnaker/keel/scheduler/ScheduleService.kt
keel-scheduler/src/main/kotlin/com/netflix/spinnaker/keel/scheduler/SchedulerAgent.kt
keel-scheduler/src/main/kotlin/com/netflix/spinnaker/keel/scheduler/handler/ScheduleConvergeHandler.kt
keel-scheduler/src/test/kotlin/com/netflix/spinnaker/keel/scheduler/handler/ScheduleConvergeHandlerTest.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/controllers/v1/IntentController.kt

We don't actually do anything with the results of the converge during upsert, so there's no reason to perform the convergence in a request thread. Instead, this change will schedule convergence immediately and distribute the work onto the queue.

refactor(web): Schedule immediate convergence instead of blocking on upsert

---

keel-core/src/main/kotlin/com/netflix/spinnaker/config/KeelConfiguration.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/IntentActivityRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/event/IntentActivityListener.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/memory/MemoryIntentActivityRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/model/ListCriteria.kt
keel-orca/src/main/kotlin/com/netflix/spinnaker/keel/orca/OrcaIntentLauncher.kt
keel-redis/src/main/kotlin/com/netflix/spinnaker/keel/redis/RedisIntentActivityRepository.kt
keel-redis/src/test/kotlin/com/netflix/spinnaker/keel/redis/RedisIntentActivityRepositoryTest.kt
keel-scheduler/src/main/kotlin/com/netflix/spinnaker/keel/scheduler/handler/ConvergeIntentHandler.kt
keel-scheduler/src/test/kotlin/com/netflix/spinnaker/keel/scheduler/handler/ConvergeIntentHandlerTest.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/controllers/v1/IntentController.kt

I didn't really like how `IntentActivityRepository` was built. Refactored to have a simpler interface, and putting all activity for an intent inside a single log. The read operations are also always paginated. I think I'll probably want to do a little more filtering on convergence events so the log isn't just filled up with `NO_CHANGE` convergence events. It'll probably make more sense to do a lookback on `NO_CHANGE` and validate that the last record was not also a `NO_CHANGE`.
This change will require you to flush the redis database (or at least the `log:*` keys). It is not backwards compat.

refactor(activity): Simplify intent activity, squash history into single log

---

gradle.properties
keel-ec2/keel-ec2.gradle
keel-ec2/src/main/kotlin/com/netflix/spinnaker/keel/ec2/EC2AssetPlugin.kt
keel-ec2/src/main/kotlin/com/netflix/spinnaker/keel/ec2/asset/AmazonSecurityGroupHandler.kt
keel-ec2/src/main/kotlin/com/netflix/spinnaker/keel/ec2/asset/EC2TypeConverter.kt
keel-ec2/src/main/kotlin/com/netflix/spinnaker/keel/ec2/asset/SecurityGroupRuleComparator.kt
keel-ec2/src/test/kotlin/com/netflix/spinnaker/keel/ec2/asset/EC2AssetPluginSpec.kt

Ensures repeated fields in protos coming back from `current` are ordered in the same way so the spec should be directly comparable without having to unpack it.

Canonicalize assets before returning from plugin

---

gradle.properties
keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/model/ClusterActiveServerGroup.kt
keel-clouddriver/src/test/kotlin/com/netflix/spinnaker/keel/clouddriver/ClusterActiveServerGroupTest.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandler.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/SecurityGroupHandler.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandlerTests.kt
keel-file-plugin/src/main/kotlin/com/netflix/spinnaker/keel/file/FileHandler.kt
keel-plugin/keel-plugin.gradle
keel-plugin/src/main/kotlin/com/netflix/spinnaker/keel/plugin/ResourceHandler.kt
keel-plugin/src/main/kotlin/com/netflix/spinnaker/keel/plugin/monitoring/ResourceStateMonitor.kt
keel-plugin/src/test/kotlin/com/netflix/spinnaker/keel/plugin/monitoring/ResourceStateMonitorTests.kt

I built this on top of #201 so you can ignore the first commit for now. It will get rebased out.
I'd like to do some tweaking of the use of the diff library as the method I'm using is designed for comparing new & old versions of the same object. In our case that's not quite valid as either one could be newer (either desired state changed, or actual resource in the cloud changed out of band).
This is a proof-of-concept though so I haven't really tried to be too clean here. I like that the check for what changed is strongly typed rather than just grepping strings or something.

Resize ASG if only diff is capacity

---

keel-api/keel-api.gradle
keel-api/src/main/kotlin/com/netflix/spinnaker/keel/rest/ArtifactController.kt

`details` is an echo thing: https://github.com/spinnaker/echo/blob/master/echo-model/src/main/java/com/netflix/spinnaker/echo/model/Metadata.java
@robfletcher do you think that the information in `Metadata` would be useful in keel, or not needed? The other option is to just accept a list of artifacts w/o additional data.

feat(controller): artifact controller that can receive spinnaker artifacts

---

keel-api/src/main/kotlin/com/netflix/spinnaker/keel/Main.kt
keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/config/ClouddriverConfiguration.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/serialization/ObjectMappers.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/ec2/Cluster.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandler.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterValidationTests.kt
keel-orca/src/main/kotlin/com/netflix/spinnaker/config/OrcaConfiguration.kt
keel-plugin/src/main/kotlin/com/netflix/spinnaker/keel/plugin/ResourceHandler.kt

We should _always_ assign `nf-infrastructure` and `nf-datacenter`, and--if there are no other security group names--an application specific security group.
Closes #213

Handle default security groups

---

keel-ec2-plugin/keel-ec2-plugin.gradle
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/SecurityGroupHandler.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/SecurityGroupHandlerTests.kt

You can't include a self-referential ingress rule when creating a new security group as the referenced group must exist already. Instead I'm now filtering them out on create which means a delta will be detected later and the ingress added.
Fixes #235

2-phase create for security groups with self-ref ingress

---

build.gradle
keel-clouddriver/keel-clouddriver.gradle
keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/config/ClouddriverConfiguration.kt
keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/MemoryCloudDriverCache.kt
keel-deliveryconfig-plugin/keel-deliveryconfig-plugin.gradle
keel-ec2-plugin/keel-ec2-plugin.gradle
keel-front50/keel-front50.gradle
keel-front50/src/main/kotlin/com/netflix/spinnaker/config/Front50Config.kt
keel-orca/keel-orca.gradle
keel-orca/src/main/kotlin/com/netflix/spinnaker/config/OrcaConfiguration.kt
keel-plugin/keel-plugin.gradle
keel-retrofit-test-support/keel-retrofit-test-support.gradle
keel-retrofit-test-support/src/main/kotlin/com/netflix/spinnaker/keel/retrofit/model/ModelParsingTestSupport.kt
keel-retrofit/keel-retrofit.gradle

We were picking up our spring-context/spring-boot-autoconfigure via keel-retrofit exporting
kork-web as an api level dependency. Moved some of keel-retrofit's dependencies to
implementation scope and added explicit dependencies where needed.
Switched use of Guava CacheBuilder to Caffeine CacheBuilder in ClouddriverInMemoryCache.

fix(dependencies): transitive dependency cleanup

---

gradle/wrapper/gradle-wrapper.properties
keel-api/src/main/kotlin/com/netflix/spinnaker/keel/Main.kt
keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/sync/LockTests.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ResourceRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/sync/Lock.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/sync/NoOpLock.kt
keel-plugin/src/main/kotlin/com/netflix/spinnaker/keel/annealing/ResourceCheckScheduler.kt
keel-plugin/src/test/kotlin/com/netflix/spinnaker/keel/annealing/ResourceCheckSchedulerTests.kt
keel-redis/src/main/kotlin/com/netflix/spinnaker/config/RedisConfiguration.kt
keel-redis/src/main/kotlin/com/netflix/spinnaker/keel/redis/RedisLock.kt
keel-redis/src/test/kotlin/com/netflix/spinnaker/keel/redis/RedisLockTests.kt
keel-redis/src/test/kotlin/com/netflix/spinnaker/keel/redis/spring/SpringStartupTests.kt
keel-sql/keel-sql.gradle
keel-sql/src/main/kotlin/com/netflix/spinnaker/config/SqlConfiguration.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/Jooq.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlLock.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlResourceRepository.kt
keel-sql/src/main/resources/db/changelog-master.yml
keel-sql/src/main/resources/db/changelog/20190320-create-lock-table.yml
keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/H2Database.kt
keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/SqlLockTests.kt
keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/SqlResourceRepositoryTests.kt
keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/spring/SpringStartupTests.kt

I looked at the locking stuff in Kork and clouddriver-nflx and it's way more capable than what we need so I cooked up something super-simple.
This should just prevent multiple Keel instances from reading all the resources and scheduling checks at the same time.

Only run the resource check scheduler on a single instance at a time

---

keel-api/keel-api.gradle
keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/CloudDriverService.kt
keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/model/ClusterActiveServerGroup.kt
keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/model/Credential.kt
keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/model/NamedImage.kt
keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ResourceRepositoryTests.kt
keel-deliveryconfig-plugin/src/main/kotlin/com/netflix/spinnaker/config/DeliveryConfigConfig.kt
keel-deliveryconfig-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/deliveryconfig/DeliveryConfig.kt
keel-deliveryconfig-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/deliveryconfig/DeliveryEnvironment.kt
keel-deliveryconfig-plugin/src/main/kotlin/com/netflix/spinnaker/keel/deliveryconfig/resource/DeliveryConfigHandler.kt
keel-deliveryconfig-plugin/src/test/kotlin/com/netflix/spinnaker/keel/deliveryconfig/resource/DeliveryConfigHandlerTests.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/config/EC2Config.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/ec2/Cluster.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/ec2/NamedImage.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandler.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/NamedImageHandler.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/SecurityGroupHandler.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandlerTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/SecurityGroupHandlerTests.kt
keel-plugin/src/main/kotlin/com/netflix/spinnaker/keel/annealing/ResourceActuator.kt
keel-plugin/src/main/kotlin/com/netflix/spinnaker/keel/plugin/ResourceHandler.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlResourceRepository.kt
keel-sql/src/main/resources/db/changelog-master.yml
keel-sql/src/main/resources/db/changelog/20190321-persist-metadata.yml

this "works" in that it will detect a newer image and trigger annealing
of a cluster, however it needs a solid overhaul to handle resource
references, hence the pretty much zero tests currently
this orphans the front50 module currently, but I didn't remove it as
I suspect we may still want that at some point

feat(deliveryConfig): actuating on dynamic image

---

keel-sql/keel-sql.gradle
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlLock.kt
keel-sql/src/main/resources/db/changelog/20190320-create-lock-table.yml
keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/SqlLockTests.kt
keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/SqlResourceRepositoryTests.kt
keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/TestDatabase.kt
keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/spring/SpringStartupTests.kt

Would love any thoughts on this. I ran into a compatibility issue the other day that got me looking at alternatives to using H2 in MySQL "compatibility" mode. This is using `testcontainers` but is considerably faster than the test I wrote for SQS that was using a very large docker image.

Use actual MySQL instead of H2 for SQL tests

---

keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/Dates.kt
keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/ImageService.kt
keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/model/NamedImage.kt
keel-clouddriver/src/test/kotlin/com/netflix/spinnaker/keel/clouddriver/ImageServiceTest.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/api/InvalidPayload.kt
keel-ec2-plugin/keel-ec2-plugin.gradle.kts
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/config/EC2Config.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/ec2/image/ImageProvider.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/ec2/image/ImageProviderDeserializer.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandler.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandlerTests.kt

It's pretty easy to add another ImageProvider. Added a preliminary jenkins one here - it relies on our special netflix "appversion" tag and "build_host" tag that every image gets tagged with when it bakes.
Not loving the way you have to specify this detail (build_host is a full url), but this is good beginning functionality for testing these things out and working with some of our alpha adopters.
This looks like:
```
"launchConfiguration": {
"imageProvider": {
"packageName": "deb-sample-app-server",
"buildHost": "https://my.jenkins.url/",
"buildName": "MY-JENKINS-job-name",
"buildNumber": "92"
},
```

feat(image): provide image with jenkins information

---

build.gradle.kts
gradle.properties
keel-api/src/test/kotlin/com/netflix/spinnaker/keel/integration/AuthPropagationTests.kt
keel-api/src/test/kotlin/com/netflix/spinnaker/keel/integration/SchedulingResilienceTests.kt
keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/keel/bakery/resource/ImageHandler.kt
keel-bakery-plugin/src/test/kotlin/com/netflix/spinnaker/keel/bakery/resource/ImageHandlerTests.kt
keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/config/ClouddriverConfiguration.kt
keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/CloudDriverService.kt
keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/ImageService.kt
keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/MemoryCloudDriverCache.kt
keel-clouddriver/src/test/kotlin/com/netflix/spinnaker/keel/clouddriver/ImageServiceTest.kt
keel-clouddriver/src/test/kotlin/com/netflix/spinnaker/keel/clouddriver/MemoryCloudDriverCacheTest.kt
keel-clouddriver/src/test/kotlin/com/netflix/spinnaker/keel/clouddriver/model/ClusterActiveServerGroupTest.kt
keel-clouddriver/src/test/kotlin/com/netflix/spinnaker/keel/clouddriver/model/SecurityGroupTest.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClassicLoadBalancerHandler.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandler.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/NamedImageHandler.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/SecurityGroupHandler.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClassicLoadBalancerModelHandlerTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandlerTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/SecurityGroupHandlerTests.kt
keel-front50/src/main/kotlin/com/netflix/spinnaker/config/Front50Config.kt
keel-front50/src/main/kotlin/com/netflix/spinnaker/keel/front50/Front50Service.kt
keel-front50/src/test/kotlin/com/netflix/spinnaker/keel/front50/model/DeliveryTest.kt
keel-igor/src/main/kotlin/com/netflix/spinnaker/config/IgorConfiguration.kt
keel-mahe/src/main/kotlin/com/netflix/spinnaker/config/MaheConfiguration.kt
keel-orca/src/main/kotlin/com/netflix/spinnaker/config/OrcaConfiguration.kt
keel-orca/src/main/kotlin/com/netflix/spinnaker/keel/orca/OrcaService.kt
keel-retrofit-test-support/src/main/kotlin/com/netflix/spinnaker/keel/retrofit/model/ModelParsingTestSupport.kt
keel-retrofit/keel-retrofit.gradle.kts

The new coroutine support in Retrofit differs a bit from the call adapter we've been using. Instead of returning `Deferred<*>` the interface methods are just defined as `suspend`.

New coroutines support in Retrofit core lib

---

keel-api/src/test/kotlin/com/netflix/spinnaker/keel/integration/SchedulingResilienceTests.kt
keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/keel/bakery/BaseImageCache.kt
keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/keel/bakery/resource/ImageHandler.kt
keel-bakery-plugin/src/test/kotlin/com/netflix/spinnaker/keel/bakery/BaseImageCacheTests.kt
keel-bakery-plugin/src/test/kotlin/com/netflix/spinnaker/keel/bakery/resource/ImageHandlerTests.kt
keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/ImageService.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClassicLoadBalancerModelHandlerTests.kt
keel-igor/src/main/kotlin/com/netflix/spinnaker/igor/ArtifactService.kt
keel-mahe/src/main/kotlin/com/netflix/spinnaker/keel/mahe/DynamicPropertyService.kt

Damn, missed a couple of services in recent switch over to new coroutine support in Retrofit 2.6.0

Fix coroutine compatibility in Mahe & Igor services

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/tags/EntityTag.kt
keel-tagging-plugin/src/main/kotlin/com/netflix/spinnaker/keel/tagging/KeelTagHandler.kt
keel-tagging-plugin/src/main/kotlin/com/netflix/spinnaker/keel/tagging/ResourceTagger.kt
keel-tagging-plugin/src/test/kotlin/com/netflix/spinnaker/keel/tagging/KeelTagHandlerTests.kt
keel-tagging-plugin/src/test/kotlin/com/netflix/spinnaker/keel/tagging/KeelTagSpecTests.kt
keel-tagging-plugin/src/test/kotlin/com/netflix/spinnaker/keel/tagging/ResourceTaggerTests.kt

Entity tags should pass `account` (with account name) as well as `accountId` (account number) in the account ref. Otherwise, clouddriver sets `account = accountId` and the UI isn't super happy.
Also, transform `*-load-balancer` to `loadbalancer` (what clouddriver expects for load balancer entity tags) so that we can look them up successfully.

fix(tags): add account, correct loadbalancer tag lookup

---

build.gradle.kts
gradle.properties
keel-actuator/src/test/kotlin/com/netflix/spinnaker/keel/actuation/ResourceActuatorTests.kt
keel-actuator/src/test/kotlin/com/netflix/spinnaker/keel/actuation/ResourcePersisterTests.kt
keel-api/keel-api.gradle.kts
keel-api/src/main/kotlin/com/netflix/spinnaker/config/DefaultConfiguration.kt
keel-api/src/main/kotlin/com/netflix/spinnaker/keel/rest/AuthorizationSupport.kt
keel-api/src/main/kotlin/com/netflix/spinnaker/keel/rest/ResourceController.kt
keel-api/src/test/kotlin/com/netflix/spinnaker/keel/rest/EventControllerTests.kt
keel-api/src/test/kotlin/com/netflix/spinnaker/keel/rest/ResourceControllerTests.kt
keel-bakery-plugin/src/test/kotlin/com/netflix/spinnaker/keel/bakery/resource/ImageHandlerTests.kt
keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ResourceRepositoryTests.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/api/Resource.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/events/ResourceEvent.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/api/ResourceMetadataTests.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/events/ResourceEventSerializationTests.kt
keel-deliveryconfig-plugin/src/test/kotlin/com/netflix/spinnaker/keel/deliveryconfig/resource/DeliveryConfigHandlerTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/ApplicationLoadBalancerHandlerTest.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClassicLoadBalancerHandlerTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandlerTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/SecurityGroupHandlerTests.kt
keel-plugin/src/main/kotlin/com/netflix/spinnaker/keel/plugin/ResolvableResourceHandler.kt
keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/SqlResourceRepositoryTests.kt
keel-tagging-plugin/src/main/kotlin/com/netflix/spinnaker/keel/tagging/ResourceTagger.kt
keel-tagging-plugin/src/test/kotlin/com/netflix/spinnaker/keel/tagging/KeelTagHandlerTests.kt
keel-tagging-plugin/src/test/kotlin/com/netflix/spinnaker/keel/tagging/ResourceTaggerTests.kt
keel-veto/src/test/kotlin/com/netflix/spinnaker/keel/api/SimpleVetoPluginTests.kt

* Adding fiat to keel.
* Adding a required new field when submitting resources, `metadata`, which must contain a `securityAccount`. Is this good? Give me opinions. I'm not sure if this should be required.
* Checking when you create/update/delete if you (`X-SPINNAKER-USER`) have access to the service account you specify.
* Adding this service account to the normal metadata for all resources.
TODO: use that service account for actuation.

feat(auth): add required service account for all resources

---

keel-actuator/src/main/kotlin/com/netflix/spinnaker/keel/actuation/ResourcePersister.kt
keel-actuator/src/test/kotlin/com/netflix/spinnaker/keel/actuation/ResourceActuatorTests.kt
keel-actuator/src/test/kotlin/com/netflix/spinnaker/keel/actuation/ResourcePersisterTests.kt
keel-api/src/main/kotlin/com/netflix/spinnaker/keel/rest/ResourceController.kt
keel-api/src/test/kotlin/com/netflix/spinnaker/keel/rest/ResourceControllerTests.kt

This will make sure that we don't get mismatching uids

feat(create): if resource exists, second create is an update

---

keel-actuator/src/main/kotlin/com/netflix/spinnaker/keel/actuation/ResourceActuator.kt
keel-actuator/src/test/kotlin/com/netflix/spinnaker/keel/actuation/ResourceActuatorTests.kt
keel-api/src/test/kotlin/com/netflix/spinnaker/keel/rest/EventControllerTests.kt
keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/keel/bakery/resource/ImageHandler.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/events/ResourceEvent.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ApplicationLoadBalancerHandler.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClassicLoadBalancerHandler.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandler.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/NamedImageHandler.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/SecurityGroupHandler.kt
keel-plugin/src/main/kotlin/com/netflix/spinnaker/keel/plugin/ResolvableResourceHandler.kt
keel-tagging-plugin/src/main/kotlin/com/netflix/spinnaker/keel/tagging/KeelTagHandler.kt

When we launch tasks, save them in the history with an `id` and a `name` instead of the `ref`.

feat(history): task id and name, not ref

---

keel-bakery-plugin/keel-bakery-plugin.gradle.kts
keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/keel/bakery/resource/ImageHandler.kt

The artifact name is not necessarily the app name. For example, the "appVersion" tags for keel are of the form `keel-0.231.0-h146.a7234bf` but my super great sample app has "appVersion" tags the form `deb-sample-app-server-0.0.1~rc.103-h104.72b8e24`. This PR uses frigga to parse the package name so that we correctly get `keel` as well as `deb-sample-app-server`.

fix(artifact): parse artifact correctly

---

keel-tagging-plugin/src/main/kotlin/com/netflix/spinnaker/keel/tagging/ResourceTagger.kt

this was causing the `AuthPropagationTest` to sporadically fail because it was making an unexpected request to clouddriver.

fix(test): delay loading clouddriver creds

---

keel-actuator/src/main/kotlin/com/netflix/spinnaker/keel/telemetry/TelemetryListener.kt

remove call to deprecated Atlas method

---

keel-clouddriver/keel-clouddriver.gradle.kts
keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/ImageService.kt
keel-clouddriver/src/test/kotlin/com/netflix/spinnaker/keel/clouddriver/ImageServiceTests.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/config/EC2Config.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ImageResolver.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/ImageResolverTests.kt

Previously 2 packages starting with the same name could be mistaken for each other, resulting in Keel deploying the wrong thing.
Fixes #403

Make sure we're getting an AMI for the right package

---

keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/ImageService.kt
keel-clouddriver/src/test/kotlin/com/netflix/spinnaker/keel/clouddriver/ImageServiceTests.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/events/ResourceEvent.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ImageResolver.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/ImageResolverTests.kt

I know this should not strictly be necessary but it's pretty easy to make Keel resilient to this case

Handle multiple AMIs for appversion (different AMIs in each region)

---

keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ImageResolver.kt

Artifact versions have ~ in them for dev artifacts, like `keeldemo-0.0.1~dev.1-h2.da2282b`. The corresponding image names replace ~ with an _. This PR replaces any ~s in the artifact version it finds so it can appropriately find the right image.

fix(imageName): replace ~ with _

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/api/ResourceId.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/serialization/ResourceIdDeserializer.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/ec2/InstanceType.kt
keel-tagging-plugin/src/main/kotlin/com/netflix/spinnaker/keel/tagging/KeelTagHandler.kt
keel-tagging-plugin/src/main/kotlin/com/netflix/spinnaker/keel/tagging/KeelTagSpec.kt
keel-tagging-plugin/src/main/kotlin/com/netflix/spinnaker/keel/tagging/ResourceTagger.kt
keel-tagging-plugin/src/test/kotlin/com/netflix/spinnaker/keel/tagging/KeelTagHandlerTests.kt
keel-tagging-plugin/src/test/kotlin/com/netflix/spinnaker/keel/tagging/KeelTagSpecTests.kt
keel-tagging-plugin/src/test/kotlin/com/netflix/spinnaker/keel/tagging/ResourceTaggerTests.kt

Jackson can't handle `inline class` and I keep forgetting. I don't think the advantages are worth the hassle.

Use a data class for ResourceId

---

keel-actuator/src/main/kotlin/com/netflix/spinnaker/keel/actuation/ResourcePersister.kt
keel-actuator/src/test/kotlin/com/netflix/spinnaker/keel/actuation/ResourcePersisterTests.kt
keel-artifact/src/main/kotlin/com/netflix/spinnaker/keel/artifact/ArtifactListener.kt
keel-artifact/src/test/kotlin/com/netflix/spinnaker/keel/artifact/ArtifactListenerTests.kt
keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ArtifactRepositoryTests.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/memory/InMemoryArtifactRepository.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlArtifactRepository.kt
keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/tx/DeliveryConfigTransactionTests.kt

Publish an event for registering artifacts in the delivery config so that we automatically fetch the first version of them in [this function](https://github.com/spinnaker/keel/blob/e713b7281144aaa7a064cf4249804e2754131a08/keel-artifact/src/main/kotlin/com/netflix/spinnaker/keel/artifact/ArtifactListener.kt#L47). This keeps the logic of registering in one place.

fix(deliveryConfig): event for registering artifact

---

keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/keel/bakery/resource/ImageHandler.kt
keel-bakery-plugin/src/test/kotlin/com/netflix/spinnaker/keel/bakery/resource/ImageHandlerTests.kt

If an image exists in more regions than desired, consider the
current state only to contain the regions in the desired state.

fix(imagehandler): exclude unnecessary image regions

---

keel-actuator/src/main/kotlin/com/netflix/spinnaker/keel/actuation/CheckScheduler.kt
keel-actuator/src/test/kotlin/com/netflix/spinnaker/keel/actuation/CheckSchedulerTests.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/config/EC2Config.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/ec2/image/ArtifactAlreadyDeployedEvent.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/ec2/image/CurrentlyDeployedImageApprover.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandler.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/image/CurrentlyDeployedImageApproverTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandlerTests.kt

Current state:
- for artifacts to "progress" through environments, keel has to deploy them (it's not enough that they're already running in that environment)
- this is annoying for testing and annoying for someone switching to declarative
This pr:
- emits an event with the ami deployed to a cluster every time we get the current state of the cluster
- a new listener reacts to those events and checks if the version running has been approved for that env but not deployed
- if so, the listener marks that version as successfully deployed in the environment. 
I also change `keel.resource-check.min-age-minutes` to `keel.resource-check.min-age-duration` (where duration is something like `60s` or `1m`) because that makes it easier to quicken up the checks locally and I'm impatient.

feat(artifact): mark artifact deployed if already out

---

keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/model/ClusterActiveServerGroup.kt
keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/model/Image.kt
keel-clouddriver/src/test/kotlin/com/netflix/spinnaker/keel/clouddriver/model/ClusterActiveServerGroupTest.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/api/InvalidPayload.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/config/EC2Config.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/ec2/cluster/LaunchConfiguration.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/ec2/cluster/LaunchConfigurationSpec.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/actuation/ArtifactPromotionListener.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandler.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ImageResolver.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/api/ec2/ClusterTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/actuation/ArtifactPromotionListenerTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandlerTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/ImageResolverTests.kt
keel-plugin/src/main/kotlin/com/netflix/spinnaker/keel/plugin/CannotResolveCurrentState.kt

This should provide some more informative context in the resource history. It also enables the `ArtifactPromotionListener` to mark a version as deployed without needing to run an AMI lookup on the CloudDriver.

Added appVersion to resolved cluster model

---

keel-api/src/main/kotlin/com/netflix/spinnaker/keel/rest/ArtifactController.kt
keel-api/src/test/kotlin/com/netflix/spinnaker/keel/rest/ArtifactControllerTests.kt
keel-artifact/src/main/kotlin/com/netflix/spinnaker/keel/artifact/ArtifactListener.kt
keel-artifact/src/test/kotlin/com/netflix/spinnaker/keel/artifact/ArtifactListenerTests.kt
keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/keel/bakery/api/ImageSpec.kt
keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/keel/bakery/resource/ImageHandler.kt
keel-bakery-plugin/src/test/kotlin/com/netflix/spinnaker/keel/bakery/resource/ImageHandlerTests.kt
keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ArtifactRepositoryTests.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/api/DeliveryArtifact.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/events/ArtifactEvent.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ArtifactRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/memory/InMemoryArtifactRepository.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/persistence/memory/InMemoryArtifactRepositoryTests.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/ec2/image/ImageProvider.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ImageResolver.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/ImageResolverTests.kt
keel-igor/keel-igor.gradle.kts
keel-igor/src/main/kotlin/com/netflix/spinnaker/igor/ArtifactService.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlArtifactRepository.kt
keel-sql/src/main/resources/db/changelog/20190913-add-status-to-artifact-version.yml
keel-sql/src/main/resources/db/databaseChangeLog.yml
keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/SqlArtifactRepositoryTests.kt

If you only want to bake or deploy an artifact with a certain status, you should be able to do that. 
This PR allows you to optionally add a list of statuses (`FINAL`, `CANDIDATE`, or `SNAPSHOT`) to the `ImageSpec` and the `ArtifactImageProvider` section of the `ClusterSpec`.
I've verified that when you have resources in the database and you upgrade to this version everything serializes with the default value correctly. Until you get new artifacts in the database with status recorded you won't be able to deploy any new versions, but that's expected (we don't know the status of the old versions, so they don't meet the requirement of being `in` the default list of statuses.

feat(artifact): optionally specify status in image and cluster

---

keel-tagging-plugin/src/main/kotlin/com/netflix/spinnaker/keel/tagging/ResourceTagger.kt

We need entity tags to show up on the resource, but it's non-trivial to correctly tag the server group because we don't have the version number.
I think this area needs a little (or a lot) more thought - likely in the `KeelTagHandler` for how to actually tag server groups vs just the cluster.
For now though this should be ok for a server group defined in only one region.

fix(tags): hack to get tags showwing for server groups

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/api/DeliveryArtifact.kt

Turns out some folks use the `FINAL` status, but others use `RELEASE`.
Is this actually as easy as adding a value to an enum? Or am I missing something/everything?
I didn't touch the tests that use various values out of `ArtifactStatus`, because it appears they are all testing support for correctly differentiating between two different statuses (e.g. filtering or choosing between status1 and status2) — not anything that would be impacted by adding one more value to the list. Hopefully that's true.

fix(artifact): add RELEASE status to artifacts/images

---

keel-core/src/test/kotlin/com/netflix/spinnaker/keel/diff/ResourceDiffTests.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/ec2/ClusterSpec.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/ec2/ServerGroup.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandler.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/api/ec2/ServerGroupDiffTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandlerTests.kt

Diff doesn't work as nicely when comparing a `Set<ServerGroup>` as it does with a `Map<String, ServerGroup>`. In particular ignored fields still register as a diff, which causes false deltas in this case.

represent a cluster's server groups as a Map not a Set

---

keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandler.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandlerTests.kt

I noticed yesterday that when there is a diff in > 1 region of a cluster Keel is fixing them one at a time. This is because Orca rejects tasks with the same correlation id as a task that is running already.

make correlation ids distinct when annealing > 1 region

---

keel-actuator/src/main/kotlin/com/netflix/spinnaker/keel/actuation/ResourcePersister.kt
keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/keel/bakery/resource/ImageHandler.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/api/DeliveryConfig.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/api/Environment.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/api/NotificationConfig.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/config/EC2Config.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ApplicationLoadBalancerHandler.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClassicLoadBalancerHandler.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandler.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/EnvironmentResolver.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/SecurityGroupHandler.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/ApplicationLoadBalancerHandlerTest.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClassicLoadBalancerHandlerTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandlerTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/EnvironmentResolverTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/SecurityGroupHandlerTests.kt
keel-orca/keel-orca.gradle.kts
keel-orca/src/main/kotlin/com/netflix/spinnaker/keel/model/EchoNotification.kt
keel-orca/src/main/kotlin/com/netflix/spinnaker/keel/model/OrchestrationRequest.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlDeliveryConfigRepository.kt
keel-sql/src/main/resources/db/changelog/20191002-add-env-notifications.yml
keel-sql/src/main/resources/db/databaseChangeLog.yml
keel-tagging-plugin/src/main/kotlin/com/netflix/spinnaker/keel/tagging/KeelTagHandler.kt

Closes https://github.com/spinnaker/keel/issues/442 (Details about format in the issue)
Environments can now have notifications, they are applied at the environment level (examples in the ticket). For now we support either slack or email, and you can't define your own custom message (`:rainbow: Managed update succeeded`). 
The environment level notification applies to every resource who cares (load balancers, security groups, clusters). You can't override it or shut it off for a specific resource (for now).

feat(notifications): add env notifications for infra tasks

---

keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/CloudDriverService.kt
keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/model/SecurityGroupModel.kt
keel-clouddriver/src/test/kotlin/com/netflix/spinnaker/keel/clouddriver/model/SecurityGroupTest.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/ec2/SecurityGroup.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/ec2/SecurityGroupRule.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/ec2/SecurityGroupSpec.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/SecurityGroupHandler.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/api/ec2/SecurityGroupTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/SecurityGroupHandlerTests.kt

- This is a breaking change for securityGroup resource definitions that standardizes on a `locations` object as used in `ClusterSpec` to contain account/region assignments. A single-region securityGroup called "keeldemo" that was previously defined in part as:
```
---
apiVersion: "ec2.spinnaker.netflix.com/v1"
kind: "security-group"
metadata:
serviceAccount: "delivery@spinnaker"
spec:
moniker:
app: keeldemo
accountName: test
region: us-west-2
...
```
becomes:
```
---
apiVersion: "ec2.spinnaker.netflix.com/v1"
kind: "security-group"
metadata:
serviceAccount: "delivery@spinnaker"
spec:
moniker:
app: keeldemo
locations:
accountName: test
regions:
- us-west-2
...
```

feat(securityGroup): multi-region resource definitions

---

keel-api/src/main/kotlin/com/netflix/spinnaker/keel/rest/ApplicationController.kt
keel-api/src/test/kotlin/com/netflix/spinnaker/keel/ec2/normalizers/ClusterAvailabilityZonesResolverTests.kt
keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ResourceRepositoryTests.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/api/Locatable.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/api/RegionSpec.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/api/ResourceSummary.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/model/SimpleRegionSpec.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/model/SubnetAwareRegionSpec.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ResourceRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/memory/InMemoryResourceRepository.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/ec2/ClusterSpec.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/ec2/LoadBalancer.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/ec2/SecurityGroupSpec.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/normalizers/ClusterAvailabilityZonesResolver.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ImageResolver.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/SecurityGroupHandler.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/api/ec2/ClusterSpecTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/image/CurrentlyDeployedImageApproverTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandlerTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/ImageResolverTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/SecurityGroupHandlerTests.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlResourceRepository.kt
keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/DummyResourceTypeIdentifier.kt
keel-test/src/main/kotlin/com/netflix/spinnaker/keel/test/Resources.kt

For the UI views for managed delivery we need an endpoint (by app) to poll for status and info. 
This implementation is expensive - we recalculate the status on every call. There's a todo in there to fix that. 
`GET https://localhost:8087/application/emburnstest?includeDetails=true` 
```json
{
"hasManagedResources": true,
"resources": [
{
"id": "ec2:cluster:test:emburnstest-md-wow",
"kind": "cluster",
"status": "ERROR",
"moniker": {
"app": "emburnstest",
"stack": "md",
"detail": "wow"
},
"locations": {
"accountName": "test",
"regions": [
"us-west-1"
]
}
},
{
"id": "ec2:security-group:test:emburnstest-managed",
"kind": "security-group",
"status": "HAPPY",
"moniker": {
"app": "emburnstest",
"stack": "managed"
},
"locations": {
"accountName": "test",
"regions": [
"us-west-1"
]
}
}
]
}
```

feat(api): provide resource summary info by app

---

keel-api/src/test/kotlin/com/netflix/spinnaker/keel/rest/ConvertExampleFilesTest.kt
keel-api/src/test/resources/examples/alb-example.yml
keel-api/src/test/resources/examples/clb-example.yml
keel-api/src/test/resources/examples/cluster-example.yml
keel-api/src/test/resources/examples/image-example.yml
keel-api/src/test/resources/examples/security-group-example.yml

I've created examples of valid yaml files that will be objectmappered to their corresponding java classes every time tests are run. This should help us keep a current folder of yaml examples that is less likely to break.

feat(examples): yaml that will break if you change the spec

---

keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ResourceRepositoryTests.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/events/ResourceEvent.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/memory/InMemoryResourceRepository.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlResourceRepository.kt

Right now if we have a "resource check error" we persist an error state. If we resolve this state but the outcome is that the resource is valid we stay in an "error" state (the last history event is an error). This PR changes the history a bit so that we persist one `ResourceValid` status if the resource is valid.
The event gets sent [here](https://github.com/spinnaker/keel/blob/684f9e546a5879cdce7c0cbfe615686df58200ba/keel-actuator/src/main/kotlin/com/netflix/spinnaker/keel/actuation/ResourceActuator.kt#L88-L92)

feat(status): include resource valid events in history

---

keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/keel/bakery/resource/ImageHandler.kt
keel-bakery-plugin/src/test/kotlin/com/netflix/spinnaker/keel/bakery/resource/ImageHandlerTests.kt

Right now if you try and calculate the desired state for an image it'll fail if the artifact isn't registered. Sure, we register the artifact for you, but that only takes affect the next time.
This PR changes the behavior slightly so that if the artifact isn't registered or it is but we don't have any versions for it we fetch the versions from igor. If we still can't find a version we throw an exception. 
This makes it possible to create an ad-hoc diff for images and clusters.

feat(artifact): pull version on demand if none found

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/api/Locatable.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/ec2/ClusterSpec.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resolvers/NetworkResolver.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ApplicationLoadBalancerHandler.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClassicLoadBalancerHandler.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/SecurityGroupHandler.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resolvers/NetworkResolverTests.kt

This fixes the situation where we can't resolve current state of a security group because its `vpc` property is `null`. We need to map `vpc` to a VPC id so we can send that to CloudDriver to fetch the current state. We don't currently apply resolvers to the spec passed to `ResourceHandler.desired` so the property can be `null` if the spec relies on the default applied by `NetworkResolver`. This is an interim fix until we figure out the proper approach.

require vpc on locations but default to vpc0

---

keel-actuator/src/main/kotlin/com/netflix/spinnaker/keel/diff/AdHocDiffer.kt
keel-api/keel-api.gradle.kts
keel-api/src/main/kotlin/com/netflix/spinnaker/keel/Main.kt
keel-api/src/test/kotlin/com/netflix/spinnaker/keel/rest/ConvertExampleFilesTest.kt
keel-api/src/test/resources/examples/titus-cluster-example.yml
keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/CloudDriverService.kt
keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/model/ActiveServerGroup.kt
keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/model/TitusActiveServerGroup.kt
keel-clouddriver/src/test/kotlin/com/netflix/spinnaker/keel/clouddriver/model/ActiveServerGroupTest.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/api/Capacity.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/api/ClusterDependencies.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/ec2/Capacity.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/ec2/ClusterSpec.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandler.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/api/ec2/ClusterSpecTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resolvers/NetworkResolverTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandlerTests.kt
keel-titus-plugin/keel-titus-plugin.gradle.kts
keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/config/TitusConfig.kt
keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/titus/cluster/TitusClusterHandler.kt
keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/titus/cluster/TitusClusterSpec.kt
keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/titus/cluster/TitusServerGroup.kt
keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/titus/titus.kt
settings.gradle.kts

An initial stab at titus support. Ad-hoc diffing support allows us to prove out the model. I'm opening this PR for feedback on the yaml representation, as well as to pull some classes up to the `keel-api` module for sharing.
This is subject to changes as I figure out what attributes I need to submit a task to orca, as well as make the common functions in `keel-clouddriver` support multiple resource types.

feat(titus): initial support of ad-hoc titus diffing

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/api/RegionSpec.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/ec2/ApplicationLoadBalancerSpec.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/ec2/ClassicLoadBalancerSpec.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/ec2/LoadBalancerSpec.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/ec2/SecurityGroupSpec.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ApplicationLoadBalancerHandler.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClassicLoadBalancerHandler.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/ApplicationLoadBalancerSpecHandlerTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClassicLoadBalancerHandlerTests.kt

- The `type` sent to `ExportController` should be "${loadBalancerType}$type", i.e. "classicLoadBalancers" or "applicationLoadBalancers" -> `/export/aws/{account}/applicationLoadBalancers/{name}?serviceAccount=foo@spinnaker.io`

feat(resources/export): export for ec2 load balancers

---

keel-api/src/test/kotlin/com/netflix/spinnaker/keel/rest/ConvertExampleFilesTest.kt
keel-api/src/test/resources/examples/simple-titus-cluster-example.yml
keel-api/src/test/resources/examples/titus-cluster-example.yml
keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/CloudDriverService.kt
keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/model/TitusActiveServerGroup.kt
keel-tagging-plugin/src/main/kotlin/com/netflix/spinnaker/keel/tagging/ResourceTagger.kt
keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/titus/cluster/TitusClusterHandler.kt
keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/titus/cluster/TitusClusterSpec.kt
keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/titus/cluster/TitusServerGroup.kt
keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/titus/exceptions/RegistryNotFoundException.kt
keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/titus/exceptions/TitusAccountConfigurationException.kt
keel-titus-plugin/src/test/kotlin/com/netflix/spinnaker/keel/titus/resource/TitusClusterHandlerTests.kt

Changes in titus spec to flatten structure. Actuation support needed for managing titus resources. Tests!
Still todo:
- notification support for environments
- an "image provider" instead of specifying a digest
- have kind be `cluster` instead of `titus-cluster`

Titus actuation support

---

keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/config/EC2Config.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ApplicationLoadBalancerHandler.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClassicLoadBalancerHandler.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandler.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/SecurityGroupHandler.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/ApplicationLoadBalancerSpecHandlerTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClassicLoadBalancerHandlerTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandlerTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/EnvironmentResolverTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/SecurityGroupHandlerTests.kt
keel-plugin/keel-plugin.gradle.kts
keel-plugin/src/main/kotlin/com/netflix/spinnaker/keel/plugin/EnvironmentResolver.kt
keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/config/TitusConfig.kt
keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/titus/cluster/TitusClusterHandler.kt
keel-titus-plugin/src/test/kotlin/com/netflix/spinnaker/keel/titus/resource/TitusClusterHandlerTests.kt

Moving the `EnvironmentResolver` to `keel-plugin` (and adding a dependency on `keel-orca`) so that all plugins have access to the environmentResolver transforms.
Adding notifications to titus clusters.

feat(titus): add notifications, move env resolver

---

keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/keel/bakery/resource/ImageHandler.kt
keel-bakery-plugin/src/test/kotlin/com/netflix/spinnaker/keel/bakery/resource/ImageHandlerTests.kt

If we have an image diff where the image exists in one region but not any of the others a simple "bake" doesn't fix it. Instead, we bake every minute for the rest of time.
This change adds a force rebake to try and remedy this situation (context parameter checked in orca [here](https://github.com/spinnaker/orca/blob/master/orca-bakery/src/main/groovy/com/netflix/spinnaker/orca/bakery/tasks/CreateBakeTask.groovy#L140)).

fix(bake): rebake if region missing

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/api/RegionSpec.kt
keel-tagging-plugin/src/main/kotlin/com/netflix/spinnaker/keel/tagging/ResourceTagger.kt

This PR fixes `SimpleRegionSpec` getting serialized (in ResourceId) as `SimpleRegionSpec(name=blah)`, but does not affect serialization into json. This has no impact on exporting resources to the correct yaml or submitting resources.
I also didn't see security group tags coming up in the ui locally, so I fixed the `resourceTagger` to have the correct "entity id" (`securitygroup` instead of `security-group`).

fix(tags): serialize simple region correctly, tag sec groups

---

keel-api/src/main/kotlin/com/netflix/spinnaker/keel/rest/ArtifactController.kt
keel-artifact/src/main/kotlin/com/netflix/spinnaker/keel/artifact/ArtifactListener.kt
keel-artifact/src/main/kotlin/com/netflix/spinnaker/keel/artifact/UnsupportedArtifactTypeException.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/api/DeliveryArtifact.kt

Add a new artifact type (`DOCKER_IMAGE`), and save those too.
Also, adding the `/artifact/register` endpoint back for easy testing.

feat(docker): react to and store docker images

---

keel-api/src/main/kotlin/com/netflix/spinnaker/keel/rest/ExportController.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ApplicationLoadBalancerHandler.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClassicLoadBalancerHandler.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandler.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/SecurityGroupHandler.kt

- also return a 404 instead of 500 when attempting to export resources
that cannot be found.

fix(export): better mapping between clouddriver types and keel kinds

---

keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/ImageService.kt
keel-clouddriver/src/test/kotlin/com/netflix/spinnaker/keel/clouddriver/ImageServiceTests.kt
keel-clouddriver/src/test/resources/named-images.json
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resolvers/ImageResolver.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resolvers/ImageResolverTests.kt

When we search for an image we may get a list back where some images don't have a region, and some have a region but don't have tags in that region.
This is a problem because we assume an image has the same name in each region we're deploying to and we use the tags to figure out what package version the image is running.
This PR allows us to find the latest image which has all the regions we care about and also has tags for each region.
Thoughts on whether this will help with the amount of re-baking we're doing?

fix(bake): ignore image where region or tags are missing

---

keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/keel/bakery/resource/ImageHandler.kt
keel-bakery-plugin/src/test/kotlin/com/netflix/spinnaker/keel/bakery/resource/ImageHandlerTests.kt
keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/ImageService.kt
keel-clouddriver/src/test/kotlin/com/netflix/spinnaker/keel/clouddriver/ImageServiceTests.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resolvers/ImageResolver.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resolvers/ImageResolverTests.kt

Instead of finding the latest image and shouting "DIFF!" when it's not perfect, look for an image that is in all the regions we want and has tags in all regions. If one can't be found, fall back to the latest image.
This should help us not find diffs as much in images and rebake.
I also changed function names because I was a little confused when working with them.

fix(image): look at latest complete image, cut down on bakes

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/api/DeliveryArtifact.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/serialization/ArtifactTypeSerializationTests.kt

Addresses #557 by introducing "friendly names" for artifact types (i.e. lower-case names as opposed to the default enum value names). Given that all current friendly names match the upper-case enum names, this could probably be even simpler, but when I started we had a conversion between `"docker"` and `DOCKER_TYPE` and so I figured it's OK to have a place to add that kind of logic if we ever have other types that don't match the friendly name. The `@JsonCreator` factory method also allows for backwards-compatibility with existing specs still using the upper-as names.

feat(serialization): Use friendly names for artifact types

---

keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/ImageService.kt
keel-clouddriver/src/test/kotlin/com/netflix/spinnaker/keel/clouddriver/ImageServiceTests.kt
keel-tagging-plugin/src/main/kotlin/com/netflix/spinnaker/keel/tagging/ResourceTagger.kt

Accidentally didn't use account in the query to find an image by package name. That didn't work. Trying again with the right api calls here.
Also removing `titus-cluster` from tag-able things because I forgot to earlier

fix(bake): include account in find packages

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/api/DeliveryArtifact.kt

The rocket team is migrating from FINAL -> RELEASE. This PR enables that and shouldn't break anything in the process 🤞

chore(artifacts): add RELEASE

---

keel-api/src/main/kotlin/com/netflix/spinnaker/keel/jsonschema/JsonSchemaGenerator.kt
keel-api/src/main/kotlin/com/netflix/spinnaker/keel/rest/SchemaController.kt
keel-api/src/test/kotlin/com/netflix/spinnaker/keel/jsonschema/JsonSchemaGeneratorTests.kt

I ended up rolling my own JSON schema generator because existing libraries did not handle polymorphic types well. It's relatively easy to just scrape the necessary info using Kotlin reflection. We can certainly enhance this to plug some gaps such as:
1. specifying the `apiVersion` and `kind` that correspond to each resource spec type
2. requiring `serviceAccount` in metadata
3. handling types with custom serialization / deserialization
4. ignore things that are non-public (e.g. keel tag resource kind)
This is a start, though.
Relevant to #230

Endpoints for json schema

---

keel-actuator/src/main/kotlin/com/netflix/spinnaker/keel/actuation/ResourceActuator.kt
keel-actuator/src/test/kotlin/com/netflix/spinnaker/keel/actuation/ResourceActuatorTests.kt
keel-api/src/main/kotlin/com/netflix/spinnaker/keel/rest/ApplicationController.kt
keel-api/src/test/kotlin/com/netflix/spinnaker/keel/rest/ApplicationControllerTests.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/api/ResourceId.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/events/ResourceEvent.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ResourceRepository.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/events/ResourceStatusTests.kt
keel-veto/src/main/kotlin/com/netflix/spinnaker/keel/veto/application/ApplicationVeto.kt

Addresses #561 
~After discussing with @emjburns, I implemented an override of the resource status in `ApplicationController`, which is what the UI calls to get resource summaries, so that it was possible to use the auto-wired `VetoEnforcer` bean without introducing new cross-module dependencies (the `ResourceRepository` interface, which is where status is currently calculated for resources, is in `keel-core`, and `VetoEnforcer` is in `keel-veto`). This works, but has the undesired side-effect that the `PAUSED` status as defined by a presence of any veto on a resource is only visible from the `/application` API. For example, if you call `/resources` you'll still get whatever the "real" status of the resource is.~
@asher @robfletcher If you have any ideas on how to do this in a …

feat(resource-status): Return PAUSED status for vetoed resources

---

keel-api/src/main/kotlin/com/netflix/spinnaker/keel/rest/ArtifactController.kt
keel-artifact/src/main/kotlin/com/netflix/spinnaker/keel/artifact/ArtifactListener.kt
keel-artifact/src/test/kotlin/com/netflix/spinnaker/keel/artifact/ArtifactListenerTests.kt
keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ArtifactRepositoryTests.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/events/ArtifactEvent.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ArtifactRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/memory/InMemoryArtifactRepository.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlArtifactRepository.kt

Scheduled method to fetch the latest artifact version in case we
- we miss events
- can't handle the event we received so we throw it out
- are running locally and want to test out artifact version things
I have some open questions, namely:
- should this be a distributed mechanism so that we're not doing the fetching on each instance every 3 minutes?
- should I launch a bunch of async tasks with coroutines for the fetch for each artifact, instead of going one by one in a loop?

feat(deb): scheduled fetch latest artifact

---

keel-actuator/src/main/kotlin/com/netflix/spinnaker/keel/actuation/ResourceActuator.kt
keel-actuator/src/test/kotlin/com/netflix/spinnaker/keel/actuation/ResourceActuatorTests.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/api/ResourceCurrentlyUnresolvable.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/api/ResourceDependencyNotFound.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/events/ResourceEvent.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ResourceRepository.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/events/ResourceStatusTests.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/NoImageFound.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resolvers/ImageResolver.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resolvers/ImageResolverTests.kt

This creates a new base exception type we can use for any "transient" failures in resolving desired state. In this case I'm using it to treat the inability to resolve an AMI for the desired app version as a fatal error as the presumption is it's currently baking (or about to bake).

don't treat missing AMI as a fatal resolution error

---

keel-clouddriver/src/test/kotlin/com/netflix/spinnaker/keel/clouddriver/ImageServiceTests.kt

It bothered me that these tests were in a different format than the other ones in keel, so I changed them.

chore(tests): convert image service test to junit5

---

keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/model/ActiveServerGroup.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/ec2/LaunchConfiguration.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandler.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandlerTests.kt

Fixes #555 by allowing the app version field in the launch configuration to be null instead of throwing an exception.

fix(resolution): Gracefully handle missing appversion tag

---

keel-api/src/main/kotlin/com/netflix/spinnaker/keel/rest/ApplicationController.kt
keel-api/src/main/kotlin/com/netflix/spinnaker/keel/rest/DeliveryConfigController.kt
keel-api/src/test/kotlin/com/netflix/spinnaker/keel/rest/ApplicationControllerTests.kt
keel-api/src/test/kotlin/com/netflix/spinnaker/keel/rest/DeliveryConfigControllerTests.kt
keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/DeliveryConfigRepositoryTests.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/api/Constraint.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/api/ConstraintState.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/constraints/ManualJudgementConstraintEvaluator.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/DeliveryConfigRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/memory/InMemoryDeliveryConfigRepository.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlDeliveryConfigRepository.kt
keel-sql/src/main/resources/db/changelog/20191108-environment-artifact-constraint.yml

- Includes all current constraint states in the `ApplicationController` method polled by deck, when the application has a delivery-config and details are expanded.
- REST methods to read constraint history and update status.
- Persistence refactor, including adding a `current_constraint` table to serve the `ApplicationController` access pattern.

feat(constraints): crud support for state

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/diff/ResourceDiff.kt
keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/titus/cluster/TitusClusterHandler.kt
keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/titus/cluster/TitusClusterSpec.kt
keel-titus-plugin/src/test/kotlin/com/netflix/spinnaker/keel/titus/resource/TitusClusterHandlerTests.kt

Closes #570.
Other changes of note in this PR:
- Removes the top-level `container` field in `TitusClusterSpec` which was redundant with the `@JsonUnwrapped` `defaults.container` one and caused that field to show up twice in JSON/YAML

feat(export): Titus cluster export

---

keel-artifact/src/test/kotlin/com/netflix/spinnaker/keel/artifact/ArtifactListenerTests.kt
keel-bakery-plugin/src/test/kotlin/com/netflix/spinnaker/keel/bakery/resource/ImageHandlerTests.kt

The all-arg and no-arg constructors for Artifact and ExpectedArtifact were deprecated in spinnaker/kork#429. Replace their usages with a builder.

refactor(artifacts): Use builder to create artifacts

---

keel-api/keel-api.gradle.kts
keel-api/src/test/kotlin/com/netflix/spinnaker/keel/rest/ConvertExampleFilesTest.kt
keel-api/src/test/resources/examples/titus-cluster-with-artifact-example.yml
keel-artifact/src/main/kotlin/com/netflix/spinnaker/keel/artifact/ArtifactListener.kt
keel-artifact/src/test/kotlin/com/netflix/spinnaker/keel/artifact/ArtifactListenerTests.kt
keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/CloudDriverService.kt
keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/model/DockerImage.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ArtifactRepository.kt
keel-docker/keel-docker.gradle.kts
keel-docker/src/main/kotlin/com/netflix/spinnaker/keel/docker/Container.kt
keel-docker/src/main/kotlin/com/netflix/spinnaker/keel/docker/ContainerDeserializer.kt
keel-docker/src/main/kotlin/com/netflix/spinnaker/keel/docker/DockerComparator.kt
keel-docker/src/main/kotlin/com/netflix/spinnaker/keel/docker/DockerImageResolver.kt
keel-docker/src/main/kotlin/com/netflix/spinnaker/keel/docker/InvalidRegexException.kt
keel-docker/src/main/kotlin/com/netflix/spinnaker/keel/docker/TagVersionStrategy.kt
keel-docker/src/test/kotlin/com/netflix/spinnaker/keel/docker/DockerComparatorTests.kt
keel-docker/src/test/kotlin/com/netflix/spinnaker/keel/docker/SampleDockerImageResolver.kt
keel-docker/src/test/kotlin/com/netflix/spinnaker/keel/docker/SampleDockerImageResolverTests.kt
keel-titus-plugin/keel-titus-plugin.gradle.kts
keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/titus/cluster/NoDockerImageFound.kt
keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/titus/cluster/TitusClusterHandler.kt
keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/titus/cluster/TitusClusterSpec.kt
keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/titus/cluster/TitusImageResolver.kt
keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/titus/cluster/TitusServerGroup.kt
keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/titus/exceptions/ErrorResolvingContainerException.kt
keel-titus-plugin/src/test/kotlin/com/netflix/spinnaker/keel/titus/resource/TitusClusterHandlerTests.kt
settings.gradle.kts

This PR provides the start for artifact support for docker images. Most of the logic is in a `keel-docker` module so it can be reused for kubernetes. You can now define a container like:
```
"container": {
"organization": "emburns",
"image": "spin-titus-demo",
"tagVersionStrategy": "increasing",
"captureGroupRegex": "^master-h(\\d+).*$"
}
```
The capture group that you provide will be used to parse the tag and get something that can be compared either with semver or numerically.
Still to do for full support: 
- https://github.com/spinnaker/keel/issues/619 (to facilitate correct sorting in lots of places)
- actually sort correctly using ^ for "latest artifact approved in"
- refresh the version info of docker images (just like we do for debs) so it's easy to run locally
- more real testing

feat(titus): docker artifact support

---

keel-actuator/src/main/kotlin/com/netflix/spinnaker/keel/actuation/ResourceActuator.kt
keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/keel/bakery/DefaultBaseImageCache.kt

Fixes #610.
The root cause for this error was twofold:
1. An `UnknownBaseImage` exception was being thrown here since there were no base images in the config file and the `@ConfigurationProperties` responsible from loading that data into the config properties class had one path too many in the prefix:
https://github.com/spinnaker/keel/blob/78b9e61498f3a27078cf97f53badab517c92568c/keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/keel/bakery/DefaultBaseImageCache.kt#L10
2. The `resolve` extension function defined in `ResourceActuator` was using a [`coroutineScope`](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/coroutine-scope.html) to run the current and desired state evaluations in parallel, which, according to the documentation, has the …

fix(actuation) Fix stack overflow in ResourceActuator

---

keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/CloudDriverService.kt
keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/ImageService.kt
keel-clouddriver/src/test/kotlin/com/netflix/spinnaker/keel/clouddriver/ImageServiceTests.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/api/Constraint.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/api/ConstraintState.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/api/DeliveryConfig.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/constraints/ConstraintEvaluator.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/constraints/ManualJudgementConstraintEvaluator.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/config/EC2Config.kt
keel-orca/keel-orca.gradle.kts
keel-orca/src/main/kotlin/com/netflix/spinnaker/keel/constraints/PipelineConstraintEvaluator.kt
keel-orca/src/main/kotlin/com/netflix/spinnaker/keel/orca/OrcaService.kt
keel-orca/src/test/kotlin/com/netflix/spinnaker/keel/constraints/PipelineConstraintEvaluatorTests.kt
keel-plugin/src/main/kotlin/com/netflix/spinnaker/keel/plugin/TaskLauncher.kt

An environment promotion constraint to gate promotions on the successful execution
of a Spinnaker pipeline. The target pipeline is launched via orca the first time
a pipeline constraint is evaluated for a given artifact version and [Environment].
The state of that pipeline execution is then assessed on each subsequent evaluation
and can optionally be retried on failure.
Example env constraint:
```
constraints:
- type: pipeline
serviceAccount: keel@spinnaker (OPTIONAL, defaults to DEFAULT_SERVICE_ACCOUNT)
pipelineId: (the id visible when editing a pipeline, not its name)
retries: (OPTIONAL, the number of times to retry a failure, defaults to 0)
parameters: (OPTIONAL, Map of trigger parameters to pass along, `user` and `type` are reserved)
```

feat(constraints): pipeline execution constraint

---

keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/keel/bakery/resource/ImageHandler.kt
keel-bakery-plugin/src/test/kotlin/com/netflix/spinnaker/keel/bakery/resource/ImageHandlerTests.kt

The root cause for the delay of ~5 minutes between detecting an image diff and being able to retrieve the artifact details from igor was that the rocket cache consumed by igor takes a while to update. It turns out that we don't need any more detail to start a bake task than what we already had in the resource diff and the spec, so long as we use a simple naming convention for full package names, so this fixes that issue by removing the call to igor.

fix(baking): Fix slow bakes due to missing data in rocket cache

---

keel-actuator/src/main/kotlin/com/netflix/spinnaker/keel/actuation/ResourceActuator.kt
keel-core/keel-core.gradle.kts
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/api/Exportable.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/logging/TracingSupport.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/logging/TracingSupportTests.kt
keel-ec2-plugin/keel-ec2-plugin.gradle.kts
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/ApplicationLoadBalancerHandlerTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClassicLoadBalancerHandlerTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandlerTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/SecurityGroupHandlerTests.kt
keel-titus-plugin/src/test/kotlin/com/netflix/spinnaker/keel/titus/resource/TitusClusterHandlerTests.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/ExportController.kt

As a follow-up to #645, this adds an `X-SPINNAKER-RESOURCE-ID` discrete field to the keel logs when the output is in JSON format, which can be helpful in narrowing down logs when troubleshooting.
Instrumentation is currently limited to only the resource checking loop in `ResourceActuator` and the resource export flow initiated by `ExportController`, but the helper methods defined in `TracingSupport` should be reusable elsewhere.
Perhaps of particular note in this PR, the resource ID is not propagated to calls executed in thread pools, such as those from the `okhttp3` HTTP client. It should be technically possible to wire those threads with MDC, but I feel like that should be left for a future PR.

feat(logging): Add X-SPINNAKER-RESOURCE-ID to logs for traceability

---

keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/ImageService.kt
keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/model/NamedImage.kt

We are erroring on images w/o an app version, so I figure that we should ignore them before we sort on app version.

fix(image): ignore images w/o an app version

---

keel-actuator/src/main/kotlin/com/netflix/spinnaker/keel/pause/ResourcePauser.kt
keel-actuator/src/test/kotlin/com/netflix/spinnaker/keel/ResourcePauserTests.kt
keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ResourceRepositoryTests.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ResourceRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/memory/InMemoryResourceRepository.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlResourceRepository.kt

Closes https://github.com/spinnaker/keel/issues/668.
Now that pause is so quick, the paused status gets cleared immediately and the status icon is stale. This is worrisome and creates confusion when you pause while keel was doing something, stop that action and fix the resource, then unpause and still have the "we're doing something" icon.
This PR adds back in the `RESUMED` events and status. This is done via events. If the events don't make it (say, the instance gets killed mid-event) it's not a big deal. The resource will just have a stale status for < 1 minute.

fix(events): add resume events so status isn't stale

---

keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/model/ActiveServerGroup.kt
keel-clouddriver/src/test/kotlin/com/netflix/spinnaker/keel/clouddriver/model/ActiveServerGroupTest.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/api/Capacity.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/ec2/ClusterSpec.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/ec2/Scaling.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/ec2/ServerGroup.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandler.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandlerTests.kt
keel-plugin/src/main/kotlin/com/netflix/spinnaker/keel/plugin/TaskLauncher.kt
keel-titus-plugin/src/test/kotlin/com/netflix/spinnaker/keel/titus/resource/TitusClusterHandlerTests.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/ConvertExampleFilesTest.kt
keel-web/src/test/resources/examples/ec2-cluster-with-autoscaling-example.yml

- Adds support for EC2 target tracking and step scaling based autoscale policies.
- `Capacity.desired` is now ignored when clusters have at least one autoscale policy.
- Autoscale policies are added, updated, or removed without deploying new server groups if resource diffs only effect scaling policies or scaling policies and capacity.
- When a cluster with scaling policies is deployed for the first time (no `current` state), the server group is created and scaling policies applied via two stages within the same orchestration.
- Modified scaling policies are applied via two stages (delete + add) within the same orchestration.
- Export functionality is fully supported; the Spinnaker UI's Create Scaling Policy wizard can thus be used to assist with the creation of declarative scaling …

feat(ec2): support for declarative autoscale policies

---

keel-artifact/src/main/kotlin/com/netflix/spinnaker/keel/artifact/ArtifactListener.kt

We were inconsistently registering docker versions. Fixing.

fix(docker): persist the correct image version

---

keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlArtifactRepository.kt

We were filtering for status with docker images. This PR makes sure we only do that for debs.
This might be not ideal, and this filtering should probably be lifted up a level. I'll refactor in a different PR, this just fixes things so that it's not broken.

fix(docker): sql sorting of artifacts

---

keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/DeliveryConfigController.kt

Right now, if a user requests a delivery config that does not exist, e.g. `/managed/delivery-configs/config-that-does-not-exist`, Spinnaker will return a 500 status code. It should probably return a 404, right?

fix(delivery): throw 404 when delivery config not found

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/diff/ResourceDiff.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/serialization/ObjectMappers.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/api/ResourceMetadataTests.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandler.kt
keel-plugin/src/main/kotlin/com/netflix/spinnaker/keel/plugin/ResourceSpecExportHelper.kt
keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/titus/cluster/TitusClusterHandler.kt
keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/titus/cluster/TitusClusterSpec.kt
keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/titus/cluster/TitusImageResolver.kt
keel-titus-plugin/src/test/kotlin/com/netflix/spinnaker/keel/titus/resource/TitusClusterHandlerTests.kt

This is my attempt at simplifying the process of omitting defaults and creating overrides when exporting resource specs. 
I'd originally envisioned being able to fully automate this process by comparing a baseline "dummy" spec with all resolvable fields resolved, but after running into several blockers (e.g. the fact that `Resolver` interfaces are defined in terms of `Resource` and not `ResourceSpec` and don't provide any feedback as to what they changed, the fact that the `resolve()` methods in `ResourceSpec` types operate on concrete resolved types and not specs, the fact that `ResourceSpec` types use a mix of spec-like data classes with all properties nullable and concrete types with no nullable properties, etc.) I gave up.
Instead, I've tried to turn 🍋into lemonade by simplifying the …

refactor(export): Refactor export to simplify omitting defaults and creating overrides

---

keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/model/ActiveServerGroup.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/api/Constraint.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/api/ConstraintState.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/constraints/CanaryConstraintDeployHandler.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/config/EC2Config.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/constraints/Ec2CanaryConstraintDeployHandler.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandler.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/api/ec2/constraints/Ec2CanaryConstraintDeployHandlerTests.kt
keel-orca/src/main/kotlin/com/netflix/spinnaker/keel/constraints/CanaryConstraintEvaluator.kt
keel-orca/src/main/kotlin/com/netflix/spinnaker/keel/orca/OrcaService.kt
keel-orca/src/test/kotlin/com/netflix/spinnaker/keel/constraints/CanaryConstraintEvaluatorTests.kt
keel-plugin/src/main/kotlin/com/netflix/spinnaker/keel/plugin/TaskLauncher.kt
keel-sql/src/main/resources/db/changelog/20191108-environment-artifact-constraint.yml

An environment promotion constraint that deploys control (baseline) and experiment (canary)
clusters which are evaluated by Kayenta using a constraint-provided canary config.
When the constraint specifies a multi-region canary, the Kayenta ACA must pass in all
regions for promotion to be allowed. Kayenta false positives can be overridden to
allow promotion via the `DeliveryConfigController.updateConstraintStatus` REST method.
Example constraint:
```
constraints:
- type: canary
serviceAccount: "keel@keel.io" // Will soon move to the Delivery Config root
canaryConfigId: b11b739d-7b1d-47c7-8430-d8ddffafb645 // Will later support named configs
beginAnalysisAfter: PT3M
canaryAnalysisInterval: PT10M
lifetime: PT30M
marginalScore: 50
passScore: 90
capacity: 1
source:
account: test
cloudProvider: …
```

feat(constraint): kayenta canary constraint with ec2 implementation

---

keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlArtifactRepository.kt
keel-sql/src/main/resources/db/changelog/20200109-fix-delivery-artifact-uniqueness.yml
keel-sql/src/main/resources/db/databaseChangeLog.yml

Turns out we obviously needed a unique constraint for artifacts. Making a delivery artifact unique on name, type, delivery config, and reference. This means that you can care about the same exact artifact in more than one way (i.e. snapshot status for feature branch env, release status for prod flow) as long as you give it a different "reference".

fix(artifact): fixing uniqueness

---

keel-actuator/src/main/kotlin/com/netflix/spinnaker/keel/actuation/EnvironmentPromotionChecker.kt
keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/keel/bakery/resource/ImageHandler.kt
keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ArtifactRepositoryTests.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ArtifactRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/memory/InMemoryArtifactRepository.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/NoImageFound.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resolvers/ImageResolver.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resolvers/ImageResolverTests.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlArtifactRepository.kt

Fixes https://github.com/spinnaker/keel/issues/690
When we ask for versions of an artifact, we now only get valid versions based on the artifact status information.
This means we can't approve a version for deployment that has an invalid status.

fix(artifacts): don't approve a version with an invalid status

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/api/DeliveryConfig.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/api/Locatable.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/serialization/DeserializationContexts.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/serialization/SubmittedEnvironmentDeserializer.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/serialization/SubmittedResourceDeserializer.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/serialization/SubmittedEnvironmentDeserializerTests.kt

This allows all resources in an environment to omit their `locations` property in favor of the one set at the environment level. It relies on some Jackson JSON parsing trickery. The nice part is that the `locations` property on the resource spec does _not_ need to be nullable, and we don't need to keep looking up the environment in order to fetch the locations -- instead it's all handled when parsing the submitted delivery config.
Closes #445

Optionally specify locations at the environment level

---

keel-sql/keel-sql.gradle.kts
keel-sql/src/main/kotlin/com/netflix/spinnaker/config/SqlConfiguration.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlArtifactRepository.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlDeliveryConfigRepository.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlDiffFingerprintRepository.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlPausedRepository.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlResourceRepository.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlRetry.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlUnhappyVetoRepository.kt
keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/SqlArtifactRepositoryTests.kt
keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/SqlDeliveryConfigRepositoryPeriodicallyCheckedTests.kt
keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/SqlDeliveryConfigRepositoryTests.kt
keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/SqlDiffFingerprintRepositoryTests.kt
keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/SqlPausedRepositoryTests.kt
keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/SqlResourceRepositoryPeriodicallyCheckedTests.kt
keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/SqlResourceRepositoryTests.kt
keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/SqlUnhappyVetoRepositoryTests.kt

Added retries to most places. One exception: persisting a delivery config. Because of the created spring transaction which operates across many tables and repositories it was impossible to add retries to those specific methods. I opened this issue (https://github.com/spinnaker/keel/issues/740) to track where we need to rethink things before being able to apply retries.
**View this w/o whitespace changes** for best experience. I wrap a lot of methods.

feat(sql): add retries to most places

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/api/DeliveryConfig.kt
keel-sql/src/main/resources/db/changelog/20200122-delivery-config-api-version.yml
keel-sql/src/main/resources/db/databaseChangeLog.yml

Adding api version to delivery configs so that we can make versioned changes to delivery configs. Not required for submission, we will default the value to v1.

feat(configs): add api version to delivery configs

---

keel-actuator/src/main/kotlin/com/netflix/spinnaker/keel/diff/AdHocDiffer.kt

This allows diffs of delivery configs that have the service account defined at the top level.

fix(diff): allow top level service account in dc diff

---

keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/DeliveryConfigController.kt

seems nice to return the delivery config that's being deleted. we already have it.

fix(delete): return deleted delivery config for safekeeping

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/actuation/ResourcePersister.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/exceptions/DuplicateResourceIdException.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/actuation/ResourcePersisterTests.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/ExceptionHandler.kt

We currently don't validate that you can't have the same resource in more than one env. This PR adds validation based on resource id. 
If the resource is present in more than one env, we throw an exception with a detailed error message and delete the delivery config. We do it in this order because we only calculate the resource id once it's been normalized and saved.

fix(config): add validation that resource names are unique

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ResourceRepository.kt

Adding ACTUATING status to both ResourceTaskSucceeded and ResourceTaskFailed events (events triggered based on statuses of orca tasks), as it currently implemented as informative tasks (meaning just provide info to the user, and we're not deciding upon them if there is an actual error).

fix(resourceEvents): adding statuses to ResourceTaskSucceeded and ResourceTaskFailed

---

keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/plugins/ResourceHandler.kt
keel-test/src/main/kotlin/com/netflix/spinnaker/keel/test/Resources.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/DeliveryConfigController.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/ExceptionHandler.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/ExceptionHandlerTests.kt

Introduces the following:
1. Additional logic in `ExceptionHandler` when dealing with YAML/JSON parsing errors by leveraging details exposed by Jackson and translating them into a well-defined format that should be easy to parse in the UI/CLI.
2. A `/delivery-configs/validate` API that is basically a no-op but which, by delegating to Jackson to parse the request body as a `SubmittedDeliveryConfig`, takes advantage of the functionality in (1) to implement a very simple validation API.
Example response:
```yaml
message: "Cannot construct instance of `com.netflix.spinnaker.keel.core.api.SubmittedResource`,\
\ problem: Cannot deserialize value of type `com.netflix.spinnaker.keel.test.DummyEnum`\
\ from String \"wrong\": not one of the values accepted for Enum class: [VALUE]\n\
\ at [Source: …
```

feat(api): Validation API and better parsing errors

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/events/ResourceEvent.kt
keel-orca/src/main/kotlin/com/netflix/spinnaker/keel/orca/OrcaTaskMonitorAgent.kt
keel-orca/src/test/kotlin/com/netflix/spinnaker/keel/orca/OrcaTaskMonitorAgentTests.kt

- issue https://github.com/spinnaker/keel/issues/829
- added orca task data (id + name) for `ResourceTaskFailed` and `ResourceTaskSucceeded`, in order for deck to be able to parse this data and show it in the history view.
- since only a single task can be associated with these events, only a single task gets saved (and not a list).

fix(TaskEvents): Adding task id and name to resource events

---

keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/CombinedRepositoryTests.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/exceptions/DuplicateArtifactReferenceException.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/exceptions/DuplicateResourceIdException.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/exceptions/ValidationException.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/CombinedRepository.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/ExceptionHandler.kt

Enforce that all artifacts in a delivery configuration have a unique reference.
Fixes #761.
If a user attempts to submit a delivery configuration that violates this, the response payload looks like this:
```
---
message: "Multiple artifacts are using the same reference: {lhochstein/lorintesttitus=my-artifact,\
\ emburns/spin-titus-demo=my-artifact}. Please ensure each artifact has a unique\
\ reference."
```
~(As an aside, I don't think keel should return a 500 error on input that fails validation, but that's the current behavior).~ (*My mistake: returning 500 was not the previous behavior on a validation error*)
It will also log a similar error message at the ERROR level:
```
Multiple artifacts are using the same reference: {lhochstein/lorintesttitus=my-artifact, …
```

feat(repository): disallow duplicate artifact refs

---

keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/ResourceKind.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/events/ResourceEvent.kt

Fixes an issue with the `ResourceTaskSucceeded` and `ResourceTaskFailed` event classes which were causing deserialization to fail for existing records without task references.

fix(events): Tolerate missing tasks in resource events

---

keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ArtifactRepositoryTests.kt
keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/CombinedRepositoryTests.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/core/api/ArtifactSummary.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/core/api/EnvironmentSummary.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ArtifactRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/CombinedRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/KeelRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/memory/InMemoryArtifactRepository.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlArtifactRepository.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/ApplicationController.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/DeliveryConfigController.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/services/ApplicationService.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/ApplicationControllerTests.kt

This PR addresses additions and changes to the `/application` API required by `deck` in the new Environments UI, including:
- Refactoring the `/application` endpoint to support returning multiple views into the environment, resource and artifact data
- Moving the existing "environments summary" API previously under `/delivery-configs` over to the `/application` endpoint
- Adding support for an artifact-centric view into the data
Sample response:
```yaml
---
applicationPaused: false
hasManagedResources: true
resources:
- id: titus:cluster:titustestvpc:serverlablpollo
kind: titus/cluster@v1
status: ACTUATING
moniker:
app: serverlablpollo
locations:
account: titustestvpc
vpc: vpc0
regions:
- name: eu-west-1
- name: us-east-1
- name: us-west-2
environments:
- artifacts:
- name: …
```

feat(api): API  improvements for environments/artifacts UI

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/events/ApplicationEvent.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/events/PersistentEvent.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/events/ResourceEvent.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/pause/ActuationPauser.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/actuation/ResourceActuatorTests.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/events/ResourceStatusTests.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/pause/ActuationPauserTests.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlArtifactRepository.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/EventController.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/apidocs/ApiDocTests.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/EventControllerTests.kt

This is an alternative take on #842 and #853. Instead of injecting synthetic resource events in the history, we inject the original application-level paused/resumed events as appropriate.
Sample API response:
```yaml
- type: "ApplicationActuationPaused"
application: "fnord"
reason: "Application fnord paused"
timestamp: "2020-03-11T06:27:03.453Z"
scope: "application"
uid: "fnord"
- type: "ApplicationActuationResumed"
application: "fnord"
reason: "Application fnord resumed"
timestamp: "2020-03-11T06:17:03.453Z"
scope: "application"
uid: "fnord"
- type: "ApplicationActuationPaused"
application: "fnord"
reason: "Application fnord paused"
timestamp: "2020-03-11T06:07:03.453Z"
scope: "application"
uid: "fnord"
- type: "ResourceValid"
kind: "test/whatever@v1"
id: "test:whatever:33323037" …
```

fix(events): Revisit reflecting application paused/resumed events on resources

---

keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/ResourceKind.kt
keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/plugins/ResourceHandler.kt
keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/CombinedRepositoryTests.kt
keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/DummyResourceTypeIdentifier.kt
keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/tx/DeliveryConfigTransactionTests.kt
keel-test/src/main/kotlin/com/netflix/spinnaker/keel/test/Resources.kt
keel-web/keel-web.gradle.kts
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/ExportController.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/DeliveryConfigControllerTests.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/DummyResourceConfiguration.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/ExceptionHandlerTests.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/ExportControllerTests.kt

Fixes the export API in a backwards-compatible manner with the old resource kind format. Introduces new behavior in terms of looking up the correct handler by defaulting to the one that supports the latest version for the specified group and kind.

fix(export): Fix export API to handle new kind format

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/veto/unhappy/UnhappyVeto.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/veto/UnhappyVetoTests.kt

Add missing syntax for variable substitution
Fixes an issue in #866. This is work to address #894

fix(veto): fix Value annotation syntax

---

keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/titus/cluster/TitusImageResolver.kt

For titus clusters seeing this error:
```
com.netflix.spinnaker.keel.plugin.CannotResolveDesiredState: Unable to resolve desired state of titus:cluster:titustestvpc:emburnstest-mmmwaffles-testing due to: List is empty
...
Caused by: java.util.NoSuchElementException: List is empty.
```
This is caused when we try to access the first item of an empty list. Fixing the handling here so that the `NoDigestFound` exception actually gets thrown.

fix(titus): throw correct exception if no digest is found

---

README.md
keel-artifact/src/main/kotlin/com/netflix/spinnaker/keel/artifact/ArtifactListener.kt
keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/keel/bakery/resource/ImageHandler.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/ArtifactController.kt

I made a small change so that the artifact registration event doesn't cause a double artifact registration. I think that was the problem with the flakey delivery config transactionality test - sometimes, the artifact would get registered, then rolled back, then registered again. 
Since i haven't seen the test failure after I made that change I'm going to hope that was the problem, merge this in, and keep monitoring it.

chore(tests): trying to stop flakey delivery config test

---

keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/artifacts/DeliveryArtifact.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/core/api/ArtifactSummary.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/services/ApplicationService.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/ApplicationControllerTests.kt

closes https://github.com/spinnaker/keel/issues/887.
Adding some info to artifact versions so the UI has great data to display. Fallback is to not display any metadata if it doesn't exist.
Right now I'm parsing things from the version string which is brittle but okay for Netflix and this stage. In the future we will want a sustainable strategy for pulling info from stash/jenkins/git/etc and maybe storing it somewhere. We will need a refactor for that. 
Refactored the tests to have an actual app version so that we test the debian parsing with frigga.
In a future PR I'll look at also adding some docker tests.
Looks like: (leaving the list of environments empty here to make the example smaller)
```yaml
---
artifacts:
- name: emburns/spin-titus-demo
type: docker
versions:
- version: …
```

feat(summary): giving artifact versions a display name and metadata

---

keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/CombinedRepositoryTests.kt
keel-core-test/src/main/kotlin/com/netflix/spinnaker/time/MutableClock.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/events/PersistentEvent.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/memory/InMemoryArtifactRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/memory/InMemoryDeliveryConfigRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/memory/InMemoryDiffFingerprintRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/memory/InMemoryResourceRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/memory/InMemoryTaskTrackingRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/serialization/ObjectMappers.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/actuation/ResourceActuatorTests.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/events/ResourceEventSerializationTests.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/pause/ActuationPauserTests.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/persistence/memory/InMemoryArtifactRepositoryTests.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/telemetry/TelemetryListenerTests.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandler.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/api/ec2/export/ClusterExportTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandlerTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/OrcaTaskLauncherTests.kt
keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/SqlArtifactRepositoryTests.kt
keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/SqlCombinedRepositoryTests.kt
keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/SqlDeliveryConfigRepositoryTests.kt
keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/SqlTaskTrackingRepositoryTests.kt
keel-test/src/main/kotlin/com/netflix/spinnaker/keel/test/CombinedRepository.kt
keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/titus/cluster/TitusClusterHandler.kt
keel-titus-plugin/src/test/kotlin/com/netflix/spinnaker/keel/titus/resource/TitusClusterExportTests.kt
keel-titus-plugin/src/test/kotlin/com/netflix/spinnaker/keel/titus/resource/TitusClusterHandlerTests.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/config/DefaultConfiguration.kt

We had previously discussed the need to standardize on a timezone or UTC. Recently, when writing new tests for the API where I tried to use a UTC clock, I realized it wouldn’t work because not all components rely on the Spring configuration, and even if I tweaked the tests to pass today by converting timestamps to PDT, they would break whenever we exit daylight savings. This PR settles on using UTC across the board.
Closes #862

Convert all clocks to UTC

---

keel-core-test/src/main/kotlin/com/netflix/spinnaker/time/MutableClock.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/core/api/ArtifactSummary.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/core/api/EnvironmentSummary.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ArtifactRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/CombinedRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/KeelRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/memory/InMemoryArtifactRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/serialization/ObjectMappers.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlArtifactRepository.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/config/DefaultConfiguration.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/services/ApplicationService.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/ApplicationControllerTests.kt

Adds information about stateful constraints applicable to an artifact version within an environment, in support of the UI.
Closes #888.

feat(api): Add stateful constraint information to artifact summaries

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/constraints/ConstraintState.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/core/api/ArtifactSummary.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/core/api/UID.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/services/ApplicationService.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/ApplicationControllerTests.kt

This is just a left-over from #926, where I forgot to add the synthetic `NOT_EVALUATED` constraint status for those constraints which have not yet been evaluated (i.e. a state even before `PENDING`).

feat(api): Add synthetic NOT_EVALUATED status for stateful constraints

---

keel-artifact/keel-artifact.gradle.kts
keel-artifact/src/main/kotlin/com/netflix/spinnaker/keel/artifact/ArtifactDeployingListener.kt
keel-artifact/src/test/kotlin/com/netflix/spinnaker/keel/artifact/ArtifactDeployingListenerTests.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/events/ArtifactVersionDeploying.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/MissingAppVersionException.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandler.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandlerTests.kt
keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/titus/cluster/TitusClusterHandler.kt
keel-titus-plugin/src/test/kotlin/com/netflix/spinnaker/keel/titus/resource/TitusClusterHandlerTests.kt

Fixes https://github.com/spinnaker/keel/issues/915:
(1) Adds "DEPLOYING" when we launch tasks to deploy new versions to clusters. Note: for Titus that means we have to translate the digest to the desired app version. 
(2) Since we're already calculating the version to send in an event right after the task launches, also include the version in the task description so it shows up in the UI (like `Upsert server group emburnstest-md-test2 to deb-sample-app-server-0.117.0-h347.3cc480c in account/region`

fix(artifacts): mark as deploying, version in task description

---

keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/CombinedRepositoryTests.kt
keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/DeliveryConfigRepositoryPeriodicallyCheckedTests.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/CombinedRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/DeliveryConfigRepository.kt
keel-sql/src/main/resources/db/changelog/20200330-delivery-config-unique-per-application.yml
keel-sql/src/main/resources/db/databaseChangeLog.yml

Closes https://github.com/spinnaker/keel/issues/676.
A first pass at limiting delivery configs to one per app.
Right now, we're making the choice to limit delivery configs to one per app so that it's easy to work with from the UI. This assumption might change as we get more adoption. I've put this one easy limit together now, which will prevent you from saving a new delivery config if one exists for your app. 
Do you think we need more precautions than this?

feat(api): limit 1 delivery config per app

---

keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/CombinedRepositoryTests.kt
keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/DeliveryConfigRepositoryTests.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/CombinedRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/DeliveryConfigRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/KeelRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/memory/InMemoryDeliveryConfigRepository.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlDeliveryConfigRepository.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/AdminController.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/EnvironmentController.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/services/ApplicationService.kt

Delivery config changes to follow enforcing one config per app (https://github.com/spinnaker/keel/pull/944). This will make it easier to work with delivery configs.

fix(configs): get by app returns one delivery config

---

keel-web/src/main/kotlin/com/netflix/spinnaker/keel/services/ApplicationService.kt

This PR name might lead you to think that this is less hacky than before. It's not. It's just more wacky-input-safe.

fix(artifact): more resilient app version parsing

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/core/api/ArtifactSummary.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/services/ApplicationService.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/ApplicationControllerTests.kt

Closes #889 
Adding stateless constraints info the artifact summary API.
an example of the output would be:
```json
"statelessConstraints": [
{
"type": "depends-on",
"currentlyPassing": true,
"attributes": {
"environment": "testing"
}
},
{
"type": "allowed-times",
"currentlyPassing": false,
"attributes": {
"windows": [
{
"days": "Wed",
"hours": "12-14"
}
],
"tz": "America/Los_Angeles"
}
}
]
```

feat(api): Add stateless constraint information to artifact summary

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/constraints/ConstraintState.kt
keel-docker/src/test/kotlin/com/netflix/spinnaker/keel/docker/SampleDockerImageResolverTests.kt
keel-test/src/main/kotlin/com/netflix/spinnaker/keel/test/CombinedRepository.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/ApplicationController.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/AuthorizationSupport.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/DeliveryConfigController.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/services/ApplicationService.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/ApplicationServiceTests.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/ApplicationControllerTests.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/DeliveryConfigControllerTests.kt

Closes https://github.com/spinnaker/keel/issues/940.
The UI needs to be able to judge constraints by using the application name instead of the delivery config name. This PR adds a new endpoint that is the same as the delivery config endpoint (see linked issue). This new endpoint has auth protections as well.
I removed the old endpoint, and also updated the tests for this functionality. I moved all tests for constraints and generating the views to the `ApplicationServiceTests` class. I kept actual controller tests (like auth rejection) in the controller tests.

chore(api): endpoint to judge constraints by application

---

keel-core/src/test/kotlin/com/netflix/spinnaker/keel/constraints/ManualJudgementConstraintEvaluatorTests.kt

Closes https://github.com/spinnaker/keel/issues/938.
I can't reproduce that bug locally or in a test. So, this PR just adds the test I wrote for manual judgement timeout. Eric and I are hypothesizing that this is just leftover from a prior incident and is not a current bug.

chore(mj): add a timeout test

---

keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/DeliveryConfigRepositoryTests.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/actuation/CheckScheduler.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/telemetry/TelemetryEvent.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/actuation/CheckSchedulerTests.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/persistence/memory/InMemoryDeliveryConfigRepositoryTests.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlResourceRepository.kt
keel-sql/src/main/resources/db/changelog/20200401-resource-check-veto.yml
keel-sql/src/main/resources/db/databaseChangeLog.yml
keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/DummyResourceTypeIdentifier.kt
keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/SqlDeliveryConfigRepositoryTests.kt
keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/SqlResourceRepositoryPeriodicallyCheckedTests.kt

After I promoted the change where we no longer check image resources, but instead check artifacts, we discovered that resource checking halted because Keel was no longer able to parse resources with `ImageSpec` payloads.
This change makes it so that if we hit that condition, we'll flag the resource as unreadable and stop checking it. That way resources we _can_ handle will continue being processed.

If we can't parse a resource in the database, stop checking

---

.github/workflows/build.yml
.github/workflows/release.yml

fix(coverage): Move codecov metric publishing to master build

---

keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/NoImageFound.kt

Improve the wording on this exception so that it's not ambiguous/misleading in the UI:
The real error here is that there's no image that _currently passes the constraints in the environment_. The current message seems to imply there's something missing in the environment, which is not the case.

fix(errors): Improve error message for NoImageSatisfiesConstraints

---

keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/ApplicationController.kt

The call to update constraint state in ballast is failing with a 403 due to the authorization check because of the metatron identity used by Titus in the container. I've done some research and think I know how to fix it, but it's quite involved and so I'm disabling the check temporarily for now.
Sample error:
```
[AUTH] ballast-149510111645 is trying to access service account delivery-engineering@netflix.com. They DO NOT have permission. Delivery config for application ballast: ballast-manifest
```

fix(authz): Temporarily disable constraint API check

---

gradle.properties

This should fix the errors we're seeing in the `master` build.

fix(build): Add prefix to liquibase tasks to avoid conflict with snapshot

---

keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ApplicationSummaryGenerationTests.kt
keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ArtifactRepositoryTests.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/actuation/CheckScheduler.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/core/api/EnvironmentSummary.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/core/api/PromotionStatus.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ArtifactRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/memory/InMemoryArtifactRepository.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/persistence/memory/InMemoryApplicationSummaryGenerationTests.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlArtifactRepository.kt
keel-sql/src/main/resources/db/changelog/20200402-more-artifact-info.yml
keel-sql/src/main/resources/db/databaseChangeLog.yml
keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/SqlApplicationSummaryGenerationTests.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/ApplicationServiceTests.kt

Recently we were talking about artifact statuses. We have an `APPROVED` status which means "this artifact is ready to be deployed". But, we sometimes have the situation where an artifact is approved for an environment but never deployed to that environment. This is probably because the artifact was superseded by another version of an artifact (both were ready to deploy, but we deployed the latest one). 
We also have a `PENDING` status for artifacts to represent that something might be going on in the future, but we have no idea what. That is calculated like this: we look at all versions we know about, and versions that we have data for in an environment (like `APPROVED`/`CURRENT` etc). The versions that we know about but are not in the environment are marked `PENDING`. This is weird, …

feat(artifact): introduce SKIPPED status, more data for previous

---

keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ApplicationSummaryGenerationTests.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/CombinedRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/KeelRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/memory/InMemoryArtifactRepository.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/services/ApplicationService.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/ApplicationServiceTests.kt

Turns out skipped versions weren't correctly getting an entry for the environment in `ArtifactVersionSummary`. This PR should address that. 
I added a skipped artifact into our `ArtifactServiceTests` to make sure that skipped info was tested. I also made the version numbers variables.

fix(artifacts): add skipped summary to env summary

---

keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ArtifactRepositoryTests.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/core/api/EnvironmentArtifactPin.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlArtifactRepository.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/ApplicationController.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/ArtifactController.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/services/ApplicationService.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/ApplicationControllerTests.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/ArtifactControllerTests.kt

Move pin operations to the application controller so that they're consistent with the other things the UI is going to call. 
Will add auth once the big PR by @luispollo (#955) has been merged in.
I did not add tests because all these methods are just passthrough, and testing should be done on the artifact repository.
Part of https://github.com/spinnaker/keel/issues/979

chore(pin): move pinning to the application controller

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/core/api/ArtifactSummary.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/core/api/EnvironmentSummary.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/core/api/ResourceSummary.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ResourceRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/memory/InMemoryArtifactRepository.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlArtifactRepository.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/services/ApplicationService.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/ApplicationServiceTests.kt

Artifacts are guaranteed to be unique by reference in a delivery config. They are not guaranteed to be unique by name + type. Adding reference here for artifact, resource, and environment summaries. @erikmunson you are able to use `reference` instead of name and type.
Fixes https://github.com/spinnaker/keel/issues/980

fix(summary): add artifact reference

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/actuation/CheckScheduler.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/actuation/ScheduledResourceCheckStarting.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/telemetry/TelemetryEvent.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/telemetry/TelemetryListener.kt

Calculate the resource check drift metric (keel.resource.check.drift)
by using the last time resource check succeeded as the start time.
Previously, it was calculating based on the beginning of the actuation
loop, which would drop to zero when the loop restarted due to timeout.
Fixes #950

fix(metrics): record drift from last resource check

---

keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/AuthorizationSupport.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/DeliveryConfigController.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/ApplicationControllerTests.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/ArtifactControllerTests.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/AuthorizationTestSupport.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/DeliveryConfigControllerTests.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/ResourceControllerTests.kt

I had a bad reference in the SPeL expression, and forgot that the submitted delivery config is not in the database yet. 😝

fix(api): Fix authorization for POST /delivery-configs

---

keel-artifact/src/main/kotlin/com/netflix/spinnaker/keel/artifact/ArtifactDeployedListener.kt
keel-artifact/src/test/kotlin/com/netflix/spinnaker/keel/artifact/ArtifactDeployedListenerTests.kt
keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ArtifactRepositoryTests.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ArtifactRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/CombinedRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/KeelRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/memory/InMemoryArtifactRepository.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlArtifactRepository.kt

I discovered that as long as an artifact is deployed, we will keep marking it as successfully deployed/current to an environment over and over again. This means that the deployed time will keep updating. This is confusing and incorrect. This PR fixes the behavior so we only mark a version as current in an environment if the version is not current.
Pretty sure this bug has been around for months but I didn't notice it until the awesome environments view kept telling me my artifact was deployed "less than a minute ago"

fix(artifacts): don't keep marking as deployed over and over

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/actuation/ResourceActuator.kt

Create an ad-hoc coroutine id to help gather related log messages. This is a temporary change to make it easier to go through the log messages for debugging #951.
Context: I'm seeing different thread names that seem to be associated with the same coroutine. Since there's no guarantee of 1:1 mapping between threads and coroutines, I don't know if it's the same coroutine or a different one, this change will make it easier to figure that out.

fix(actuator): add coroutine id to help debug

---

keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/keel/bakery/artifact/ImageHandler.kt
keel-bakery-plugin/src/test/kotlin/com/netflix/spinnaker/keel/bakery/artifact/ImageHandlerTests.kt
keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/ImageService.kt

The problem was that the `imageService` functions all make sure that an image has an appversion. The base ami doesn't. I just took the old find baseami function from the old image handler (replaced in https://github.com/spinnaker/keel/pull/988/files).

fix(bake): locate baseami

---

keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/keel/bakery/artifact/ImageHandler.kt
keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/keel/bakery/telemetry/BakeryTelemetryListener.kt

Tagging a bake counter with the appversion so that we can see if we're re-baking the same app version over and over again. I'm going to set up an alert for baking the same appversion like... more than 10 times or something.

chore(bake): add a metric to alert on for when we bake too much

---

keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/keel/bakery/artifact/ImageHandler.kt

I included a string that renders as such hot trash in metric view. Let's just use the desired version.

fix(bake): nice string rather than a garbage string

---

keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/keel/bakery/BaseImageCache.kt
keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/keel/bakery/DefaultBaseImageCache.kt
keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/keel/bakery/artifact/ImageHandler.kt
keel-bakery-plugin/src/test/kotlin/com/netflix/spinnaker/keel/bakery/DefaultBaseImageCacheTests.kt
keel-bakery-plugin/src/test/kotlin/com/netflix/spinnaker/keel/bakery/artifact/ImageHandlerTests.kt
keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/ImageService.kt

Obviously, this will require equivalent change in `keel-nflx` where we'll use `ImageService.findBaseAmiVersion` to go from the image name we get from the Bakery's fast property to the actual `base_ami_version` tag on that image.

Make BaseImageCache map to base_ami_version rather than just imageName

---

keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/ExceptionHandler.kt

Unfortunately, since the `@PreAuthorize` behavior in Spring is just to check boolean-returning functions, there's no way to propagate the actual permission error up the stack. Authorizationt errors are all turned into "Access is denied", which is not very informative.
I could change the permission check methods to throw my own `AccessDeniedException`, but that would short-circuit Spring's `AccessDecisionManager`, which didn't seem like a good idea, so my approach here is just to use a generic message that's better than the default.
Closes #998

fix(api): Better 403 error messages

---

build.gradle.kts

Bump the OkHttp library to version 4.5.0.
Hopefully fixes #951

chore(dependencies): bump okhttp to 4.5.0

---

build.gradle.kts
gradle.properties

Bumping both okhttp and kork broke prestaging. Roll them both back for now.

fix(deps): roll back okhttp and kork

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/serialization/ObjectMappers.kt

We're calling `configuredObjectMapper()` all over the codebase to obtain an instance of an `ObjectMapper` with our custom configuration. This should generally yield new copies of a mapper with the same configuration, except that in the application startup code we do additional configuration of the ones registered with the Spring context, which exclude all the ones instantiated directly.
This PR ensures that there's only ever a single copy of each type of `ObjectMapper` by using a singleton for each.
Attempt to close https://github.com/spinnaker/keel/issues/1015

fix(core): Ensure there's only ever 1 of each type of configured ObjectMapper

---

keel-web/src/main/kotlin/com/netflix/spinnaker/config/KeelConfigurationFinalizer.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/Main.kt

Really fixes #1015 (hopefully).

fix(init): Move configuration finalization out of Main

---

keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/DeliveryConfig.kt
keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/Resource.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/core/api/EnvironmentArtifactPin.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ArtifactRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/memory/InMemoryArtifactRepository.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlArtifactRepository.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/ApplicationController.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/ArtifactController.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/services/ApplicationService.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/ApplicationControllerTests.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/ArtifactControllerTests.kt

Moving the apis for vetoing an artifact in an environment to the application controller in preparation for exposing them through gate. Removed the need to specify the artifact type and delivery config name, just like the other apis.

chore(veto): move veto apis to application controller

---

build.gradle.kts

Bump to newest version of okhttp, which fixes a bug we seem to be hitting.
Hopefully fixes #951

fix(deps): bump okhttp

---

keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/keel/bakery/artifact/ImageHandler.kt

This makes the orca task user for a bake look the same as for other tasks launched by keel.

chore(usability): Use consistent formats for task user

---

keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ArtifactRepositoryTests.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/core/api/ArtifactSummary.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/core/api/EnvironmentArtifactPin.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/core/api/EnvironmentSummary.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ArtifactRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/CombinedRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/KeelRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/memory/InMemoryArtifactRepository.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/actuation/EnvironmentPromotionCheckerTests.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlArtifactRepository.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/ApplicationController.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/services/ApplicationService.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/ApplicationServiceTests.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/ApplicationControllerTests.kt

I'm doing several things in this PR:
- Change pinning to only need artifact reference, not reference and type. Artifact reference is unique. Artifact name + type is not unique.
- Clean up some methods around ^
- Add pinning data into the summary view: both in the environment summary and the artifact summary
A request to pin an env will now look like:
`POST /application/{appName}/pin`
```json
{
"targetEnvironment": "testing",
"reference" : "my-artifact",
"version" : "master-h13.73d1d93"
}
```
(you don't need the `type` in the body anymore, will update gate in a future PR)

feat(artifacts): add pinned info, only use reference

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/actuation/ResourceActuator.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/actuation/ResourceActuatorTests.kt

fixes https://github.com/spinnaker/keel/issues/295.
We observe some event mismatch behavior in the resource history API - for some resources, the event chain is `Drift detected` --> `valid` without `ResourceDeltaResolved` prior to `valid` (see screenshot).
Solution: prior to emitting `ResourceDeltaResolved` event, we check what was the resource last event? 
`ResourceActuationLaunched`? -- do nothing and wait for task completion.
`ResourceTaskSucceeded` or `ResourceTaskFailed`? --> emit the `resolved` event (as we have a clear status and the delta is resolved).
`ResourceDeltaDetected`? but no actuation was launched, emit the `resolved` event (as probably we resolved it without taking any explicit action).

fix(resourceEvent): emit ResourceDeltaResolved when actually needed

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/actuation/ResourceActuator.kt

Back out code that was added to debug issue #951:
* log.debug statements
* running an async block in single thread context (originally done to see if it would resolve the issue. It didn't).

chore(core): back out debug logging and single thread context

---

keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandler.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/api/ec2/export/ClusterExportTests.kt

The code to export a launch config was including the server group's own instance type to compare with itself, which... er... would always be the same, and therefore get omitted. 🤦 
Fixes #918

fix(export): Fix launch config export

---

keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/model/NamedImage.kt
keel-clouddriver/src/test/kotlin/com/netflix/spinnaker/keel/clouddriver/model/NamedImageTests.kt

Fix an edge case in `NamedImage` class where `hasAppVersion` was returning true, even though  app version information was missing.
Methods in the [ImageService](https://github.com/spinnaker/keel/blob/fa634a154158c6da17cfe0814698dff039fe2bc5/keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/ImageService.kt#L31) class always call `filter{ it.hasAppVersion }` after calling `cloudDriverService.namedImages` , which means that any returned [NamedImage] object should have a valid appversion field.
However, we are seeing an exception being thrown when reading the `NamedImage.appVersion` property (see stack trace in #1052), which shouldn't be possible given that we always filter on `hasAppVersion`. 
It turned out there was a case where the `hasAppVersion` check returns true, …

fix(clouddriver): hasAppVersion edge case

---

keel-web/src/main/kotlin/com/netflix/spinnaker/keel/apidocs/SealedClassModelConverter.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/apidocs/ApiDocTests.kt

ensure DeliveryArtifact schema is output correctly even if things render in a different order

---

keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/ApplicationController.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/services/ApplicationService.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/ApplicationControllerTests.kt

I keep wanting to look up a delivery config by app instead of by manifest name. So I made that api.

feat(configs): fetch config by app

---

README.md
keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/CloudDriverService.kt
keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/MemoryCloudDriverCache.kt
keel-clouddriver/src/test/kotlin/com/netflix/spinnaker/keel/clouddriver/MemoryCloudDriverCacheTest.kt

This is an attempt to fix #1060.
Our cache for security groups was indexing SGs by ID/name, but using a call to clouddriver that retrieves _all_ SGs for the account+region, which in our case is thousands of objects. Even on a server group with a small number of SGs, that meant repeated calls to that API. This PR changes that behavior to use the existing clouddriver API to retrieve a single SG by name, and a [newly introduced variant of the API to retrieve an SG by ID](https://github.com/spinnaker/clouddriver/pull/4540), which I hope should significantly speed things up.
Depends on https://github.com/spinnaker/clouddriver/pull/4540

fix(performance): Avoid retrieving all SGs when looking for one

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/core/api/EnvironmentSummary.kt

Log an error & cut the artifact out of the summary if we're in a weird edge case.
Problem:
We have a bug where sometimes artifacts get stuck in the "DEPLOYING" state within an environment. When this happens, and we try and generate the summary for that environment, we throw an exception and bork the whole artifacts summary. That's annoying.
This PR changes things so we log an error instead of throwing an exception, and then we return null (which will cut that artifact out of the summary).
I'm still working on fixing the underlying issue, but this is a little bandaid so the view doesn't completely break

fix(artifacts): log instead of throw when artifacts have weird statuses

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/telemetry/TelemetryListener.kt

We currently report drift time (time since last resource/environment/artifact check) in milliseconds. However, typical drift times are currently on the order of one second, and unhealthy drift times are much higher. 
Here's an example of the three drift metrics for a typical healthy time period (click to embiggen):
At this scale, it's easier for me to reason about seconds than thousands of milliseconds. This PR changes the reported drift metrics from milliseconds to seconds, to help make these graphs easier to read.
Note that the reported metric is still a float, so we won't lose any precision.

chore(telemetry): report drift time in seconds

---

keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/CloudDriverService.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/core/api/ClusterDeployStrategy.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/plugin/ResourceSpecExportHelper.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/config/EC2Config.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandler.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/api/ec2/export/ClusterExportTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandlerTests.kt
keel-orca/src/main/kotlin/com/netflix/spinnaker/keel/orca/ClusterExportHelper.kt
keel-orca/src/main/kotlin/com/netflix/spinnaker/keel/orca/OrcaService.kt
keel-orca/src/test/kotlin/com/netflix/spinnaker/keel/orca/ClusterExportHelperTests.kt
keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/config/TitusConfig.kt
keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/titus/cluster/TitusClusterHandler.kt
keel-titus-plugin/src/test/kotlin/com/netflix/spinnaker/keel/titus/resource/TitusClusterExportTests.kt
keel-titus-plugin/src/test/kotlin/com/netflix/spinnaker/keel/titus/resource/TitusClusterHandlerTests.kt

Adds support for exporting the deployment strategy associated with a cluster based on information retrieved from pipelines (for not-yet-migrated apps) and tasks (for already-managed apps or clusters created manually in the UI).
Limitations: currently, the export supports `createServerGroup` tasks and `deploy` pipeline stages only. Support for clone operations, if necessary, will be addressed in a separate PR.
Closes #753. As I was working in this area of the code anyway, I've taken the opportunity to also fix #625.

feat(export): Export deployment strategy

---

keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ArtifactRepositoryTests.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ArtifactRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/memory/InMemoryArtifactRepository.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlArtifactRepository.kt

Right now, we sort tags based on the docker strategy you've chosen. If you choose the wrong strategy, we don't necessarily care, and even though we can't sort in a meaningful way we don't stop trying! We just put that un-sortable data at the bottom of the list. That seems not great.
This PR filters out non-matching tags based on the versioning strategy you've chosen. One caveat - this doesn't protect from user error. For example, you could tell us that your tag is and will always be a semantic version. Then, you could start pushing tags with colors (or other string garbage). Because you've told us that your whole tag is what we should use to sort, we say "sure! let's do it!". This PR doesn't change that (except that we explicitly ignore the "latest" tag).
If you've given us a custom regex …

fix(titus): filtering out non matching tags

---

keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/plugins/ResourceHandler.kt
keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/model/ActiveServerGroup.kt
keel-clouddriver/src/test/kotlin/com/netflix/spinnaker/keel/clouddriver/model/ActiveServerGroupTest.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/exceptions/DockerArtifactExportError.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/ec2/ServerGroup.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandler.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/api/ec2/constraints/Ec2CanaryConstraintDeployHandlerTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/api/ec2/export/ClusterExportTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandlerTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/TestUtils.kt
keel-orca/src/test/kotlin/com/netflix/spinnaker/keel/orca/ClusterExportHelperTests.kt
keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/titus/cluster/TitusClusterHandler.kt
keel-titus-plugin/src/test/kotlin/com/netflix/spinnaker/keel/titus/resource/TitusClusterExportTests.kt
keel-titus-plugin/src/test/kotlin/com/netflix/spinnaker/keel/titus/resource/TitusClusterHandlerTests.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/ExportController.kt

This PR adds an endpoint to export artifacts given a cluster. The existing cluster export will now return a reference provider with a reference to the name of the artifact instead of the old style full artifact (which is no longer supported)
These endpoints should be used together to produce the artifact and cluster that are both needed to put a cluster correctly in a delivery config.
A `GET /export/artifact/{provider}/{account}/{cluster}` will return something like:
```json
{
"name": "deb-sample-app-server",
"reference": "deb-sample-app-server",
"vmOptions": {
"baseLabel": "RELEASE",
"baseOs": "xenial",
"regions": [
"us-east-1",
"us-west-2"
],
"storeType": "EBS"
},
"statuses": [],
"type": "deb"
}
```
Notes:
- Name and reference will be the same, and reference can be excluded or changed. …

feat(export): export artifacts from clusters

---

keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/CloudDriverCache.kt
keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/MemoryCloudDriverCache.kt
keel-clouddriver/src/test/kotlin/com/netflix/spinnaker/keel/clouddriver/MemoryCloudDriverCacheTest.kt
keel-ec2-plugin/keel-ec2-plugin.gradle.kts
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandlerTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/SecurityGroupHandlerTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/vetos/RequiredSecurityGroupVetoTests.kt
keel-retrofit-test-support/src/main/kotlin/com/netflix/spinnaker/keel/retrofit/errors.kt

We have an issue in that `CloudDriverCache` is frequently called as part of determining the current state of a resource. Usually this is for converting ids to names for things like subnets and security groups. If the cache is not primed, we make a call to CloudDriver. If that call throws a `RetrofitException` it will propagate out of the `CloudDriverCache` method and be handled in the resource handler. If the exception is a 404 we can misinterpret that as meaning the resource itself was not found. 
For example, look at https://github.com/spinnaker/keel/blob/master/keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ApplicationLoadBalancerHandler.kt#L261-L267 where if we catch an `HttpException` with a code of 404, we return `null` for the current state of the ALB …

Disambiguate 404s

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/core/api/ApplicationSummary.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/CombinedRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/DeliveryConfigRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/KeelRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/memory/InMemoryDeliveryConfigRepository.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlDeliveryConfigRepository.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/AdminController.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/services/AdminService.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/AdminControllerTests.kt

issue https://github.com/spinnaker/keel/issues/1063.
This is a proposal for an endpoint to retrieve all of the managed applications. 
I've created a new response type called `ApplicationSummary` , 
and the new endpoint will return a list of these. Here's an example:
`    "name": "gyardeni-manifest",
"application": "gyardeniapp",
"serviceAccount": "delivery-engineering@netflix.com",
"apiVersion": "delivery.config.spinnaker.netflix.com/v1",
"isPaused": true`

feat(getAllApps): Endpoint to get all managed applications

---

keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/DiffFingerprintRepositoryTests.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/DiffFingerprintRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/memory/InMemoryDiffFingerprintRepository.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlDiffFingerprintRepository.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/AdminController.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/services/AdminService.kt

Sometimes we might need to trigger a recheck of a resource. This might happen after recovering from an incident or bug (like https://github.com/spinnaker/keel/issues/1090). I created an admin endpoint to do this instead of just going into the database.

feat(admin): recheck endpoint

---

keel-retrofit/src/main/kotlin/com/netflix/spinnaker/keel/retrofit/KeelRetrofitConfiguration.kt

Making a `OkHttpClient` bean `PROTOTYPE` scope is a big no-no:
> OkHttp performs best when you create a single `OkHttpClient` instance and reuse it for all of your HTTP calls. This is because each client holds its own connection pool and thread pools. Reusing connections and threads reduces latency and saves memory. Conversely, creating a client for each request wastes resources on idle pools.

fix(retrofit): OkHttpClient should not be PROTOTYPE scope

---

keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/ApplicationController.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/services/ApplicationService.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/ApplicationControllerTests.kt

Adding an endpoint to delete delivery configs by app, because it's annoying to have to first make a call to find the config name
I'm not removing the other endpoint for backwards compatibility.

chore(config): delete config by app

---

keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/CombinedRepositoryTests.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/exceptions/MissingEnvironmentReferenceException.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/CombinedRepository.kt

fixes https://github.com/spinnaker/keel/issues/936.
Adding a validation for the depends on constraint - if referencing to a non-existing environment, throw a bad request exception. 
I'm planning on extracting the delivery config validation into a new service but will do it in a separate PR.

fix(validation): Throw an exception when referencing a non existing env

---

gradle.properties
settings.gradle.kts

This adds flags for the related projects that we bring in
as dependencies, to enable referencing the related project
as a composite build via gradle.
This method of enabling composite builds seems to work
significantly better with IntelliJ. (As opposed to
importing multiple projects into the IDE and configuring
the composite relationship after the fact)
This holds the opinion that all the projects are checked
out in the same parent directory, and can be found at
`'../<projectName>'` relative to this project.
To enable a composite reference to a project, set the
project property `'<projectName>Composite=true'`.
This can be done either as
* a command line flag, e.g. `-PkorkComposite=true`
* a project property via gradle.properties
* a global project property via ~/.gradle/gradle.properties

feat(build): adds project properties for composite builds.

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/events/ResourceEvent.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/events/ResourceState.kt

Previously, both `ResourceDeltaDetected` and `ResourceCheckUnresolvable` events were reported with identical tags in the `keel.resource.checked` metric, which meant we couldn't tell how many times we were getting transient resource check failures.
This change differentiates these two events by introducing a new resource state. I called it `unresolvable` to match the name `ResourceChecekUnresolvable`.

chore(events): add unresolvable state for metrics

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/core/api/SubmittedDeliveryConfig.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/diff/AdHocDiffer.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/CombinedRepository.kt

Even though you can definitely omit the name when submitting to `keel` directly, I'm pretty sure the serialization from gate sends a key with a null value for the name. `keel` does not like that. This change allows a null name, and uses another property to give the correct name if it indeed is null.

fix(config): allow null name, use correctly

---

keel-web/src/main/kotlin/com/netflix/spinnaker/config/DefaultConfiguration.kt

Enable Spring controller (server-side IPC) metrics, consistent with the other Spinnaker apps.
I implemented this using [fiat's config](https://github.com/spinnaker/fiat/blob/0d58386152ad78234b2554f5efdf12d26b77d57c/fiat-web/src/main/java/com/netflix/spinnaker/fiat/config/FiatConfig.java#L47-L54) as a starting point.
Some of the calls that Fiat makes have been deprecated, so I'm using the non-deprecated equivalents  (I'm not using the deprecated `WebMvcConfigurerAdapter` or the deprecated constructor of `MetricsInterceptor`).
Fixes #868.

chore(web): add controller invocation metrics

---

keel-web/src/main/kotlin/com/netflix/spinnaker/config/DefaultConfiguration.kt

Several keel REST controllers use "name" as a path variable, so I originally thought it would be useful to report those as tags on the controller invocations metric.
The problem is that "name" is already used as the metric key (`controller.invocations`), and so specifying it as a path variable tag has no effect. This commit removes it from the list of path variables to tag.
Longer term, if we want to capture this information as tags in the metrics, we should rename the variable in the controllers from "name" to something else so we can use it in a tag.

chore(metrics): remove useless "name" path metrics variable

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/events/ApplicationEvent.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/events/ResourceEvent.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/events/ResourceEventSerializationTests.kt

I inadvertently made new fields non-optional on the primary constructor, which broke deserialization of old events in the DB.

fix(events): Fix deserialization of paused/resumed events

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/CombinedRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/KeelRepository.kt

I used the wrong endpoint for deleting things by app. The one I used didn't actually delete anything but the config. This one actually deletes everything.

fix(delete): delete by app now deletes everything

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/exceptions/DockerArtifactExportError.kt
keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/titus/cluster/TitusClusterHandler.kt
keel-titus-plugin/src/test/kotlin/com/netflix/spinnaker/keel/titus/resource/TitusClusterExportTests.kt
keel-titus-plugin/src/test/kotlin/com/netflix/spinnaker/keel/titus/resource/TitusClusterHandlerTests.kt

When exporting docker artifacts I was ignoring the possibility that a currently running container might have two tags (like `latest`). This fixes that problem.

fix(export): ignore latest tag

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/core/api/ClusterDeployStrategy.kt
keel-orca/src/main/kotlin/com/netflix/spinnaker/keel/orca/ClusterExportHelper.kt

Turns out you can't cast strings to ints with `as` in kotlin. I also added some error handling because orca's context is .... not reliably typed and bound to give us a hard time

fix(export): fix discover deploy strategy

---

keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/AuthorizationSupport.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/DeliveryConfigController.kt

fixes https://github.com/spinnaker/keel/issues/1153.
The delivery config name is not mandatory anymore, but the application is. So for authorization checks, we will use the application name instead.

fix(configAuthz): not relying on delivery config name for authorization

---

keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/AuthorizationSupport.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/DeliveryConfigController.kt

following PR https://github.com/spinnaker/keel/pull/1163/, fixing the endpoints that take the application names as the identifier to use `application` as the target, instead of `deliveryConfig`

fix(deliveryConfig): support both application and config name

---

keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ResourceRepositoryTests.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/events/ApplicationEvent.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/events/PersistentEvent.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/events/ResourceEvent.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/pause/ActuationPauser.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/CombinedRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/KeelRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ResourceRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/memory/InMemoryResourceRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/services/ApplicationService.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/services/ResourceHistoryService.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/services/ResourceStatusService.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/events/ResourceStatusTests.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/services/ApplicationServiceTests.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/services/ResourceHistoryServiceTests.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/services/ResourceStatusServiceTests.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlResourceRepository.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/EventController.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/ResourceController.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/EventControllerTests.kt

Attempt to fix an issue identified recently where resources got stuck in RESUMED status, and hopefully prevent future pitfalls around resource events/status.
The cause of this particular problem was that we look at the event history to determine status, and, in this case, there were `ApplicationActuationResumed` events appearing last in the event history for those resources. (We also noticed the application paused/resumed events were not displayed on the UI, making the experience even more confusing, but that’s a separate issue).
Upon investigation, we discovered that keel behaved as expected after an application is resumed and proceeded to check the resources and emitted `ResourceValid` events. The problem was that these events have the `ignoreRepeatedInHistory` flag set to `true`, which …

fix(events): Simplify resource event history

---

keel-orca/src/main/kotlin/com/netflix/spinnaker/keel/orca/OrcaService.kt
keel-orca/src/test/kotlin/com/netflix/spinnaker/keel/constraints/PipelineConstraintEvaluatorTests.kt

This really bugs me, but it's a blocker so I've just reverted the change I made. When just using a plain map Retrofit throws a runtime exception ```java.lang.IllegalArgumentException: Parameter type must not include a type variable or wildcard: java.util.Map<java.lang.String, ?> (parameter #3)```

fix(orca): Fix stupid Retrofit error

---

keel-api-jackson/src/test/kotlin/com/netflix/spinnaker/keel/api/ConstraintTests.kt
keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ApproveOldVersionTests.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/actuation/EnvironmentPromotionCheckerTests.kt
keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/SqlApproveOldVersionTests.kt

A test that reproduces https://github.com/spinnaker/keel/issues/1100
note: this behavior only fails in the sql implementation, not the in memory implementation. cc @lorin in case you were curious.
Note: test is commented out because it's breaking. Putting this up for @gal-yardeni  to use, but it's probably a needed test because this flow is COMPLICATED!
...also, I can't spell judgement...

chore(artifacts): write test for approving old version

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/services/ResourceStatusService.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/services/ResourceStatusServiceTests.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlResourceRepository.kt

While refactoring `SqlResourceRepository` in #1159, I removed a check that threw a `NoSuchResourceId` if the event history for a resource was empty, because I assumed that would be accounted for by the call in the same function to `get(id)`. However, we started seeing exceptions in the logs when trying to determine resource status because the event history is empty, so I suspect the original behavior was masking the fact that we end up with an empty list under certain conditions.
Given that persisting events is asynchronous and could fail for a variety of reasons, this PR accounts for an empty event list by resolving the resource status to `UNKNOWN` in that case.
I also added debug logs to event persistence which will hopefully help troubleshoot this further if any future problems occur.

fix(status): Account for unexpected empty event history

---

keel-retrofit/src/main/kotlin/com/netflix/spinnaker/keel/retrofit/KeelRetrofitConfiguration.kt
keel-retrofit/src/main/kotlin/com/netflix/spinnaker/keel/retrofit/SpinnakerHeadersInterceptor.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/integration/AuthPropagationTests.kt

Undo changes by @srekapalli to change the initialization of `SpinnakerHeadersInterceptor`, and remove the dependency on `FiatPermissionEvaluator` in that interceptor to avoid the circular dependency on the `OkHttpClient` introduced by the latest versions of kork.
This has the side-effect that we no longer include the `X-SPINNAKER-ACCOUNTS` header in downstream calls and hence have these warnings in the logs:
```
c.n.s.okhttp.OkHttp3MetricsInterceptor   : [] Request GET:https://<redacted>/securityGroups/test/aws/us-east-1/<redacted>?getById=true is missing [X-SPINNAKER-ACCOUNTS] authentication headers and will be treated as anonymous.
```
I will follow up with a separate PR to address that (see https://github.com/spinnaker/keel/issues/1175).

fix(core): Fix StackOverflowError caused by new OkHttpClient setup in kork

---

keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/ec2/ClusterDependencyContainer.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/vetos/RequiredLoadBalancerVeto.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/vetos/RequiredSecurityGroupVeto.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/vetos/RequiredLoadBalancerVetoTests.kt

The required load balancer veto was only checking CLB / target group name and regions, not ensuring the dependency was in the right account! I discovered this  by accident today when testing something else. This fixes it.

Required load balancer veto needs to match account

---

keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ApproveOldVersionTests.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/actuation/EnvironmentPromotionChecker.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/actuation/EnvironmentPromotionCheckerTests.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlDeliveryConfigRepository.kt

fixes https://github.com/spinnaker/keel/issues/1100.
The problem: 
1. Artifact `deb` has 2 versions: `version1` and `version2`, where `version1` is older. 
2. We have `manual-judgement` constraint for the environment, and both versions are in `PENDING` state.
3. I approve `version1` but nothing is happening.
The fix:
When changing a constraint state, in this case, `PENDING` -> `PASS` (or `OVERIDE_PASS`), the following is happening:
1. we persist the new state to `ENVIRONMENT_ARTIFACT_CONSTRAINT`
2. we insert to `CURRENT_CONSTRAINT` (which holds the current constraints for an application per environment)
3. we have another table called `ENVIRONMENT_ARTIFACT_QUEUED_APPROVAL` which actually holds the approved version. When we change the state to pass, assuming all other stateful constraints …

fix(ApprovedVersion): Approved versions are now actually get deployed

---

keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandler.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/api/ec2/export/ClusterExportTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/TestUtils.kt

Step #1 to fixing https://github.com/spinnaker/keel/issues/1167 is guessing the base os more correctly and throwing an error if we can't determine it

fix(deb): export base-os correctly

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/actuation/ResourceActuator.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/events/ResourceEvent.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ResourceRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/services/ResourceStatusService.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/veto/Veto.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/events/ResourceEventSerializationTests.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/services/ResourceStatusServiceTests.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/vetos/RequiredLoadBalancerVeto.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/vetos/RequiredSecurityGroupVeto.kt

I was investigating https://github.com/spinnaker/keel/issues/1126 (which I can't reproduce locally). I found it frustrating that we weren't persisting veto events for flapping resources, so i updated our code to add that event and then determine whether a resource is unhappy by either the fact that it's vetoed or that it has been flapping.
This means that a resource that is vetoed because it's flapping or because it doesn't have the required resources (sec group or lb) will have a history event that says vetoed and a status of `unhappy`. @erikmunson and I thought that `unhappy` was clearer to users than `vetoed`.
Thoughts?
UPDATE:
added a `MISSING_DEPENDENCY` status to be specific for the missing load balancer and missing sg stuff.

feat(status): vetoed resources get history event + unhappy status

---

keel-core/src/main/java/com/netflix/rocket/api/artifact/internal/debian/DebianArtifactParser.java
keel-core/src/test/java/com/netflix/rocket/api/artifact/internal/debian/DebianArtifactParserTests.java
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandler.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/api/ec2/export/ClusterExportTests.kt

Part # 2 to https://github.com/spinnaker/keel/issues/1167
We now use a class adapted from the rocket team to give ourselves a hacky guess at what the debian status is. This is fine for now. 
Note: if you have a flow where you are deploying snapshot artifacts to feature branch clusters, you'll still need to edit your delivery config by hand. This change will just actually capture that you have two different statuses.

fix(export): we now look at deb status in a hacky way

---

keel-orca/src/main/kotlin/com/netflix/spinnaker/keel/constraints/PipelineConstraintEvaluator.kt
keel-orca/src/test/kotlin/com/netflix/spinnaker/keel/constraints/PipelineConstraintEvaluatorTests.kt

Adding a "start pipeline" log and putting the env name in the link text (as `Env {env}`). Any better link text ideas? Trying to find something short but informative

chore(logs): pipeline logs + trigger

---

keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/model/ApplicationLoadBalancerModel.kt
keel-clouddriver/src/test/resources/loadBalancers.json

Make targetGroupName optional in the Action model.
Keel assumed that a load balancer Action field will always have a targetGroupName, but that’s not true for redirect actions.
fixes #1198.

fix(clouddriver) LB Action: targetGroupName optional

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/actuation/EnvironmentPromotionChecker.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/actuation/EnvironmentPromotionCheckerTests.kt

Remove logging (sorry @gal-yardeni, I didn't want to take the time to ensure it would log but also not break the ordering), and revert back to only checking stateful if stateless pass.

fix(constraints): don't evaluate stateful unless stateless pass

---

keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/model/ApplicationLoadBalancerModel.kt
keel-clouddriver/src/test/resources/loadBalancers.json
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ApplicationLoadBalancerHandler.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/ApplicationLoadBalancerHandlerTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/vetos/RequiredLoadBalancerVetoTests.kt

Change the `healthCheckPort` field on a clouddriver data model object from `Int` to `String`.
Fixes #1200 
When we query clouddriver for an ApplicationLoadBalancer (ALB) model object, one of the model sub-objects, TargetGroup, has a field named `healthCheckPort`.
This field is encoded as a string in the JSON payload, but is almost always a string-quoted integer (e.g., `"8080"`). However, we recently discovered that it is not always an integer: a valid value is the string `"traffic-port"`, which means "just use the same port that the load balancer sends the regular traffic to."
Keel's `TargetGroup` model object currently represents this value as an `Int`, which leads to a deserialization error when an ALB is configured with `"traffic-port"`.
To fix this, we need to modify the `TargetGroup` …

fix(clouddriver): healthCheckPort as string

---

keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/CombinedRepositoryTests.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/CombinedRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/validators/DeliveryConfigValidator.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/validators/DeliveryConfigValidatorTests.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/DeliveryConfigController.kt

Closes https://github.com/spinnaker/keel/issues/1021.
This is a stab at aligning delivery config validations across endpoints:
POST /delivery-configs (upsert a config)
POST /delivery-configs/diff (diffing a new config to an existing one)
POST /delivery-configs/validate (static validation of config)
My logic was to extract the validation logic to a `DeliveryConfigValidator` class, which will be a centralized class for the different validations. To make it work with all the endpoints above, I've transformed the logic to apply on the `SubmittedDeliveryConfig` object rather than `DeliveryConfig` and wired the validator to the controller class rather than each individual implementation.
Next:

Chore(validations): Aligning config validations across multiple endpoints

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/exceptions/NoSuchEnvironmentException.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/services/AdminService.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/services/AdminServiceTests.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/AdminController.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/ExceptionHandler.kt

closes https://github.com/spinnaker/keel/issues/1174
An endpoint to redo the evaluation of all stateful constraints for an environment, with the option to specifically trigger only one type. This is useful for recovering from a bad state.

feat(admin): redo constraint evaluation

---

keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlAgentLockRepository.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlArtifactRepository.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlDeliveryConfigRepository.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlDiffFingerprintRepository.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlPausedRepository.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlResourceRepository.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlTaskTrackingRepository.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlUnhappyVetoRepository.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/timestamps.kt
keel-sql/src/main/resources/db/changelog/20200522-standardize-timestamps.yml
keel-sql/src/main/resources/db/databaseChangeLog.yml

We've used a mixture of `bigint` and `timestamp` on our tables. This PR standardizes on the latter. It also ensures we have millisecond precision (which is probably only really important on `event` but makes sense as a standard for compatibility with `java.time` types).

refactor(db): standardize timestamp types in all tables

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/validators/DeliveryConfigValidator.kt

when validating a submitted delivery config, generate its unique resource id rather than the spec id.

fix(validations): fetch the right resource id when looking for duplications

---

keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/UnhappyVetoRepositoryTests.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlUnhappyVetoRepository.kt

If you call `getOrCreateVetoStatus` before a status exists for that resource it would NPE.

Fix NPE in UnhappyVetoRepository

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/core/api/ClusterDeployStrategy.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/api/ClusterDeployStrategyTests.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandler.kt
keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/titus/cluster/TitusClusterHandler.kt

Adds a `waitForInstancesUp` configuration to the `red-black` deployment strategy, and replaces the hard-coded 30 minute orca stage timeout for deployment jobs with the sum of this new duration plus existing delay fields in the config (`delayBeforeScaleDown` and `delayBeforeDisable`).
For example, the following config:
```yaml
deployWith:
delayBeforeScaleDown: PT1H
resizePreviousToZero: true
rollbackOnFailure: false
strategy: red-black
```
...would translate to a 1 hour delay before scale down + (default) 30 min wait for instances up = 1h30min timeout for the orca task.
Fixes #1180.

feat(deploy): Make red-black wait time configurable, orca stage timeout based on all delays

---

keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/CombinedRepositoryTests.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/exceptions/DuplicateManagedResourceException.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/CombinedRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/KeelRepository.kt

fixes https://github.com/spinnaker/keel/issues/1242.
Currently we allow a single resource to be managed by more than 1 delivery config file. This fix is blocking it by making sure the combination of a delivery config name + resource id is unique.

fix(duplicateResources): don't allow resources to be managed in more than 1 config

---

.github/workflows/build.yml

The `jacocoAggregateReport` task  was inadvertently removed in #1044.

fix(coverage): Reenable generation of jacoco report

---

keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/ec2/ClusterSpec.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/ec2/ServerGroup.kt
keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/titus/cluster/TitusServerGroup.kt

`UnhappyControl` is only relevant to resource specs but I noticed it was implemented by a couple of concrete model classes.

Remove UnhappyControl from non-ResourceSpec classes

---

keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ArtifactRepositoryTests.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/actuation/ResourceActuator.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/core/api/ArtifactSummary.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/core/api/EnvironmentArtifactVeto.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/exceptions/InvalidVetoException.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ArtifactRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/CombinedRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/KeelRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/services/ApplicationService.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/actuation/ResourceActuatorTests.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlArtifactRepository.kt
keel-sql/src/main/resources/db/changelog/20200528-add-veto-info.yml
keel-sql/src/main/resources/db/databaseChangeLog.yml
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/ApplicationController.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/ExceptionHandler.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/ApplicationControllerTests.kt

Closes https://github.com/spinnaker/keel/issues/1233.
Adds a table to store 'mark as bad' comments + user + timestamp. 
`POST /applications/{application}/veto`
with body:
```kotlin
data class EnvironmentArtifactVeto(
val targetEnvironment: String,
val reference: String,
val version: String,
val comment: String?
)
```
Marks an artifact as bad and saves the user who vetoed.
Unmark as bad is `DELETE /{application}/veto/{targetEnvironment}/{reference}/{version}`
(will make the corresponding updates in `gate` shortly)

feat(mark-as-bad): add comment, show comment

---

keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/DeliveryConfig.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/core/api/SubmittedDeliveryConfig.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/CombinedRepository.kt
keel-igor/keel-igor.gradle.kts
keel-igor/src/main/kotlin/com/netflix/spinnaker/config/IgorConfiguration.kt
keel-igor/src/main/kotlin/com/netflix/spinnaker/igor/ScmService.kt
keel-igor/src/main/kotlin/com/netflix/spinnaker/keel/services/DeliveryConfigImporter.kt
keel-igor/src/test/kotlin/com/netflix/spinnaker/keel/services/DeliveryConfigImporterTests.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlDeliveryConfigRepository.kt
keel-sql/src/main/resources/db/changelog/20200603-add-delivery-config-metadata.yml
keel-sql/src/main/resources/db/databaseChangeLog.yml
keel-test/keel-test.gradle.kts
keel-web/keel-web.gradle.kts
keel-web/src/main/kotlin/com/netflix/spinnaker/config/DefaultConfiguration.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/AuthorizationSupport.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/DeliveryConfigController.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/ExceptionHandler.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/DeliveryConfigControllerTests.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/ResourceControllerTests.kt

Implements a new `POST /delivery-configs/import` API that performs the same steps as the orca `ImportDeliveryConfigTask`, namely retrieving a specified delivery config from source control via igor, and upserting the delivery config into the keel database.
This PR also takes advantage of the fact that we now have metadata available in keel about the provenance of the delivery config, and adds a `metadata` column to the `delivery_config` table to store that information.
The goal of this PR is to make progress towards #870 and provide a more self-contained way to test the import flow locally by avoiding as many dependencies and steps as possible in the manual test flow. For example, with this change, it's straightforward to replicate the error from #1262 locally.

feat(import): API to import delivery config from source

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/exceptions/InvalidArtifactReferenceException.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/exceptions/NonexistentArtifactReferenceException.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/validators/DeliveryConfigValidator.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/validators/DeliveryConfigValidatorTests.kt

Add a validation check for artifact references that refefrences artifacts that aren't defined in the delivery config.
Fixes #1271

fix(validation): disallow invalid artifact refs in delivery configs

---

keel-sql/src/main/resources/db/changelog/20200611-fix-event-timestamps.yml
keel-sql/src/main/resources/db/databaseChangeLog.yml

Because the `event.timestamp` column used to not store sub-second precision this change just ensures that the timestamps in the event JSON payload and the denormalized `timestamp` column are identical.
Fixes #1158

ensure event timestamps have subsecond precision

---

keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ApproveOldVersionTests.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/actuation/EnvironmentConstraintRunner.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/actuation/EnvironmentPromotionChecker.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/DeliveryConfigRepository.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/actuation/EnvironmentConstraintRunnerTests.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/actuation/EnvironmentPromotionCheckerTests.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/actuation/NewEnvironmentPromotionCheckerTests.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlDeliveryConfigRepository.kt

In preparation for solving https://github.com/spinnaker/keel/issues/1254, I needed to split up the `EnvironmentPromotionChecker` class to make it a lot easier to build on. I did that by splitting the checking constraints into a new class, `EnvironmentConstraintRunner`.
In  `EnvironmentConstraintRunner`, constraints get evaluated and then queued for approval. `EnvironmentPromotionChecker` looks at that list to figure out what should be approved for each environment. Most notably, if the environment is pinned, we never evaluate the constraints (right now). Changing that is now an easy change!
There are still some todos in here for me, but I wanted to open a PR because this took me like 3 full days and I'm thrilled that the tests pass with only some small additions to reflect the queue then …

chore(constraints): refactor the environment promotion checker

---

keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/ec2/SecurityGroupRule.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/jackson/IngressPortsDeserializer.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/jackson/IngressPortsSerializer.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/SecurityGroupHandler.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/api/ec2/SecurityGroupRuleTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/SecurityGroupHandlerTests.kt

Clouddriver can return a security group with ingress rules defined like this:  
```json
"inboundRules": [
{
"class": "com.netflix.spinnaker.clouddriver.model.securitygroups.IpRangeRule",
"range": {
"ip": "100.64.0.0",
"cidr": "/10"
},
"protocol": "-1",
"portRanges": [
{}
],
"description": "0AIr0"
}
]
```
A protocol of `-1` means "all protocols" and an empty port range object means "all ports".
This change supports those in `ec2/security-group@v1` resources with the notation 
```yaml
protocol: ALL
portRange: ALL
```

Support all protocols / all ports ingress rules

---

keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/Resource.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlDeliveryConfigRepository.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlResourceRepository.kt
keel-sql/src/main/resources/db/changelog/20200611-create-resource-metadata-view.yml
keel-sql/src/main/resources/db/databaseChangeLog.yml
keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/SqlResourceRepositoryPeriodicallyCheckedTests.kt

Original intent here was a way to keep service account consistent between a delivery config and its resources. However, I think it makes sense to have all metadata be derived.
Fixes #1097.

Derive resource metadata instead of storing it

---

keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/CombinedRepositoryTests.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/exceptions/DuplicateManagedResourceException.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/CombinedRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/DeliveryConfigRepository.kt

closes #1260 .
The delivery config name should be unique across all applications. 
This PR preventing the following:
- delivery config with name "config" and application "app1" is already persisted.
- someone is trying to submit a config with name "config", for application "app2".
- "app1" and "app2" have at least one same resource.
If app1 and app2 somehow have the same resources (like in the bug description), both apps are entering a weird state.

fix(configName): check delivery config name uniqueness

---

keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlArtifactRepository.kt

an artifact was only successfully deployed if it has a status of current or previous. updating the sql query here to reflect that. I think this was just a bit outdated

fix(artifacts): successfully deployed status only current or previous

---

keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/artifacts/SpinnakerArtifact.kt
keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/events/artifacts.kt
keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/plugins/ArtifactPublisher.kt
keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/plugins/SupportedArtifact.kt
keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/plugins/SupportedVersioningStrategy.kt

First part of breaking up #1286 into more manageable reviews.
This PR introduces only new code, which will be latent until part 3 of this series when I plan to refactor keel's existing artifact detection implementation to use the new plugin interface.

feat(artifacts): Introduce ArtifactPublisher plugin interface (1 of 3)

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/constraints/AllowedTimesConstraintEvaluator.kt

Addresses the keel side of https://github.com/spinnaker/keel/issues/1263
`UTC` (the short code) wasn't valid. You have to use the long code. Switched to PST while i was at it because... most of us are in California.

fix(allowed-times): use correct zoneId, switch default to PST

---

keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/CloudDriverService.kt
keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/model/ActiveServerGroup.kt
keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/model/TitusActiveServerGroup.kt
keel-clouddriver/src/test/kotlin/com/netflix/spinnaker/keel/clouddriver/model/ActiveServerGroupTest.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/ec2/ServerGroup.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandler.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/api/ec2/constraints/Ec2CanaryConstraintDeployHandlerTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandlerTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/TestUtils.kt
keel-orca/src/test/kotlin/com/netflix/spinnaker/keel/orca/ClusterExportHelperTests.kt
keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/titus/cluster/TitusClusterHandler.kt
keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/titus/cluster/TitusServerGroup.kt
keel-titus-plugin/src/test/kotlin/com/netflix/spinnaker/keel/titus/resource/TestUtils.kt
keel-titus-plugin/src/test/kotlin/com/netflix/spinnaker/keel/titus/resource/TitusClusterHandlerTests.kt

We had a longstanding incorrect assumption that an active asg was healthy. this is not true. 
This pr takes advantage of the `instanceCounts` object on all server group responses:
```
instanceCounts": {
"total": 1,
"up": 1,
"down": 0,
"unknown": 0,
"outOfService": 0,
"starting": 0
}
```
Now, we will only publish a "successfully deployed" event if the server groups are all healthy (`total == up`).

fix(deploys): active server groups are not always healthy

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/core/api/ClusterDeployStrategy.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/api/ClusterDeployStrategyTests.kt

The automatic rollback feature of deploys doesn't play nicely with keel's management. I'm switching this to default to off because keel will take care of rolling back if the deploy fails

fix(deploy): we don't need to rollback on failure

---

keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlArtifactRepository.kt

When marking something as deploying, we shouldn't mark that same version as skipped if it has already been marked deploying

fix(stuck): don't mark currently deploying version as skipped

---

keel-web/keel-web.gradle.kts

The `springdoc` libs were recently updated and bring in a binary-incompatible version of `jackson-module-kotlin`. This rolls back the version to fix it.

fix(jackson): Fix jackson-module-kotlin binary compatibility issue

---

keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/plugins/ArtifactSupplier.kt
keel-artifact/src/main/kotlin/com/netflix/spinnaker/keel/artifact/ArtifactListener.kt
keel-artifact/src/main/kotlin/com/netflix/spinnaker/keel/artifact/DebianArtifactSupplier.kt
keel-artifact/src/main/kotlin/com/netflix/spinnaker/keel/artifact/DockerArtifactSupplier.kt
keel-artifact/src/test/kotlin/com/netflix/spinnaker/keel/artifact/DebianArtifactSupplierTests.kt
keel-artifact/src/test/kotlin/com/netflix/spinnaker/keel/artifact/DockerArtifactSupplierTests.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/services/ApplicationService.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/services/ApplicationServiceTests.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/config/SqlConfiguration.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/ArtifactUtils.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlArtifactRepository.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlDeliveryConfigRepository.kt
keel-test/src/main/kotlin/com/netflix/spinnaker/keel/test/artifacts.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/config/KeelConfigurationFinalizer.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/apidocs/DeliveryArtifactModelConverter.kt

In #1321, I defined `supportedVersioningStrategies` (plural) in `ArtifactSupplier`. But we currently only have a single versioning strategy per existing artifact type (Docker and Debian), with additional options configured within those as necessary (e.g. `DockerVersioningStrategy` uses the `tagVersionStrategy` to build the right comparator). So, on second thought, it seemed like unnecessary complexity to allow multiple strategies per artifact type.
This PR makes it so that each `ArtifactSupplier` can only support a single versioning strategy sub-type, which is also reflected in a new generic parameter to the interface, making it even more clear what each supplier supports.

refactor(artifacts): Allow single versioning strategy per ArtifactSupplier

---

README.md

...just so it's easier for plugin developers to find out the latest library versions.

docs(*): Add badge with latest release version to README

---

keel-orca/src/main/kotlin/com/netflix/spinnaker/keel/orca/OrcaTaskMonitorAgent.kt
keel-orca/src/test/kotlin/com/netflix/spinnaker/keel/orca/OrcaTaskMonitorAgentTests.kt

If we are trying to query orca for information about some task and orca returns an error, log it, and remove that task from `task_tracking` table.
Question: should we publish an event for that unknown task, something like `ResourceTaskUnknown`?

fix(orcaError): catch errors from orca when failing to get info on tasks

---

keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlArtifactRepository.kt

Refactor the `SqlArtifactRepository.markAsVetoedIn` method to (hopefully) make the code easier to understand. Mostly this is pulling out chunks of code into separate methods. I also added some header docs with preconditions and postconditions.
This is preparation work for tackling #1086. I wanted to first submit a refactoring change that had no (intended) behavioral changes, to make it easier to review.

refactor(db): refactor markAsVetoedIn

---

keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ArtifactRepositoryTests.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlArtifactRepository.kt

Properly handle the case when vetoing (marking as bad) an artifact version in an environment that had never been deployed to that environment.
Fixes #1086
Previously, we did an UPDATE to the record in environment_artifact_versions to mark the version as vetoed. This change does an *upsert* instead of an *update*, to handle the case where the record doesn't exist yet.
`updateAsVetoedInEnvironmentArtifactVersionsTable` has been renamed to `upsertAsVetoedInEnvironmentArtifactVersionsTable` to reflect this.
Previously, all of the logic in this method was in a lambda passed to the `fetchOne` method. But, because `fetchOne` can return null if there are no matching records, the code inside that lambda wasn't getting executed when the record in environment_artifact_versions didn't exist yet. …

fix(sql): handle veto when never previously deployed to target environment

---

build.gradle.kts
keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/artifacts/VersioningStrategy.kt
keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/plugins/ArtifactSupplier.kt
keel-artifact/src/main/kotlin/com/netflix/spinnaker/keel/artifact/DebianArtifactSupplier.kt
keel-artifact/src/main/kotlin/com/netflix/spinnaker/keel/artifact/DockerArtifactSupplier.kt
keel-artifact/src/main/kotlin/com/netflix/spinnaker/keel/artifact/coroutines.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/artifacts/DebianSemVerVersioningStrategy.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/artifacts/DockerVersioningStrategy.kt
keel-test/src/main/kotlin/com/netflix/spinnaker/keel/test/artifacts.kt

Addresses a couple of issues found when attempting to implement the first plugin based on `ArtifactSupplier`:
- Removes `suspend` modifier from `getLatestArtifact()`
- Annotates `publishArtifact()` with `@JvmDefault` such that the default implementation carries over to Java
- Changes `VersioningStrategy` to an interface

refactor(artifacts): Cleanup from ArtifactSupplier implementation PoC

---

keel-ec2-api/src/main/kotlin/com/netflix/spinnaker/keel/api/ec2/ApplicationLoadBalancerSpec.kt

Turns out this class gets `toString`'d when we serialize history event deltas, because the diffing lib sees the structure as a map where the `TargetGroup` is the key. Today that produces some gnarly diff output, seen here in the UI:
This serializes the name instead, so you get something like `targetGroups[deck-test-targetgroup]`

fix(ec2): serialize TargetGroups as their name (for history deltas)

---

keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/config/EC2Config.kt

We were missing the registration of this resource kind as a Spring bean such that it gets picked up by `ResourceSpecIdentifier.identify()`.

fix(resources): Register ALB v1.1 resource kind

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/artifacts/DockerArtifact.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/jackson/DeliveryArtifactTests.kt

Docker convention is to have images of the form `organization/image-name:tag`. Adding some validation to enforce that because it's tricky when images have a slash in the `image-name` format.

feat(docker): don't allow a/a/a format

---

keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/CombinedRepositoryTests.kt
keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/DeliveryConfigRepositoryTests.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/CombinedRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/DeliveryConfigRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/KeelRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/services/AdminService.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlDeliveryConfigRepository.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/DeliveryConfigController.kt

Recently we had an incident where a rogue delivery config caused resource checks to drop off. To remediate the issue we wanted to delete the delivery config, but we couldn't because our current delete relies on serialization of resources.
This PR changes delete to delete without serialization so that it is more bester and able to be used when we have serialization problems

fix(delete): delete without serialization

---

keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/DeliveryConfigRepositoryTests.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/CombinedRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/DeliveryConfigRepository.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlDeliveryConfigRepository.kt

I tried deleting a delivery config locally during testing and it failed. We were mixing up delivery config names with application names. This fixes it.

fix(api): Fix delete delivery config API

---

gradle.properties

Revert fiat version to prevent fiat from bringing in a newer version of kork.
We want kork 7.50.0, but fiat-api 1.22.0 brings in kork 7.51.2, and that leads keel to throw the following error on startup:
```
Could not find class [com.netflix.spinnaker.kork.eureka.EurekaComponents]
```

fix(deps): revert fiat version

---

keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ArtifactRepositoryTests.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/core/api/ArtifactSummary.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/serialization/ArtifactSummarySerializationTests.kt

Fixes serialization of fields in artifact/environment summary. Instead of boolean fields and objects now there are just the objects.

Fix serialization of pinned and vetoed fields

---

keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlResourceRepository.kt
keel-sql/src/main/resources/db/changelog/20200714-add-event-application-column.yml
keel-sql/src/main/resources/db/databaseChangeLog.yml

@robzienert observed recently that we were doing some quite expensive queries selecting for `json -> '$.application'` on the event table. This PR introduces a generated column to avoid the need to do that.
See #1359

Use a generated application column on event table

---

keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/plugins/ResourceHandler.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/actuation/ResourceActuator.kt

This simply marks `ResourceHandler` as a `SpinnakerExtensionPoint` to make it explicit that it supports implementations via the Spinnaker plugin framework.
As far as I can see at this point, there's nothing in `ResourceActuator` that would prevent an external plugin from working in keel, so my goal with this PR is to release a version that we can implement an external plugin against to verify that assumption.

feat(plugins): Expose ResourceHandler as a SpinnakerExtensionPoint

---

keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/titus/cluster/TitusClusterSpec.kt
keel-titus-plugin/src/test/kotlin/com/netflix/spinnaker/keel/titus/resource/TitusClusterDesiredStateResolutionTests.kt

There was a subtle bug where the default took precedence over the override in map properties of Titus clusters. This fixes it.

Fix overrides for Titus cluster map properties

---

keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/plugins/ResolvableResourceHandler.kt
keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/plugins/ResourceHandler.kt
keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/plugins/SimpleResourceHandler.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ApplicationLoadBalancerHandler.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClassicLoadBalancerHandler.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandler.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/SecurityGroupHandler.kt
keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/titus/cluster/TitusClusterHandler.kt

It turns out that abstract classes don't work with the current implementation of the Spinnaker plugin framework because it uses proxy classes which can implement interfaces marked as `SpinnakerExtensionPoint`, but cannot extend an abstract class. This PR refactors `ResourceHandler` into an interface and pulls the common behavior around using resolvers into an abstract `ResolvableResourceHandler` base-class that the native plugin implementations now extend.

refactor(plugins): Make ResourceHandler an interface for Spinnaker plugin compatibility

---

keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlDeliveryConfigRepository.kt

Fixes the query to get constraint state such that the artifact reference is only used when actually passed in.

fix(constraints): Fix query to load constraint state

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/resources/ResourceSpecIdentifier.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/config/EC2Config.kt
keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/config/TitusConfig.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/config/KeelConfigurationFinalizer.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/KindController.kt

Replaces previous reliance on a Spring-injected list of `SupportedKind<*>` with querying the `ExtensionRegistry`, such that external plugin-provided resource kinds are included.

fix(plugins): Fix discovery of supported resource kinds

---

keel-web/config/keel.yml
keel-web/keel-web.gradle.kts
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/Main.kt
keel-web/src/main/resources/application.properties

- add reasonable keel configuration defaults under `keel-web/config/keel.yml`
- apply `io.spinnaker.package` to keel-web
- use `additional-location` for additive properties
This work depends on fixing https://github.com/spinnaker/keel/issues/1409 , so let's address that first.
/cc @ezimanyi 
/cc @emjburns

chore(defaulting): set reasonable defaults for services

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/resources/ResourceSpecIdentifier.kt

Adding some debug logs so we can see if the expected auto-wired constructor is being called.

debug(core): Debug registration of supported resource kinds

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/resources/ResourceSpecIdentifier.kt

We were reading the supported resource kinds too early in the constructor. This PR delays that until the list is actually used to give a chance for the configuration finalizer to register the types.

fix(core): Delay usage of extension registry when identifying resource types

---

keel-sql/keel-sql.gradle.kts
keel-sql/src/main/resources/jooqConfig.xml

When using the Gradle dæmon the JOOQ generation task generates its .java files to the wrong place. This fixes it by ensuring `jooqConfig.xml` contains a fully-qualified path.

Fix JOOQ generation under Java 11

---

keel-web/keel-web.gradle.kts

Uprading springdoc-openapi pulls in a newer version of Spring Boot we do not want yet.

Stop accidentally upgrading Spring Boot

---

keel-web/src/main/kotlin/com/netflix/spinnaker/config/DefaultConfiguration.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/DeliveryConfigYamlParsingFilter.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/DeliveryConfigYamlParsingFilterTests.kt

feat(api): Enable parsing of YAML anchors and aliases

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/core/VersioningStrategyComparators.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/api/VersioningStrategyTests.kt

We noticed versions such as `1597277806575` were not being sorted correctly as they are bigger than `Int.MAX_VALUE`.

fix(artifacts): Allow long increasing versions

---

keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/constraints/StatefulConstraintEvaluator.kt
keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/plugins/ConstraintEvaluator.kt
keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/keel/bakery/constraint/ImageExistsConstraintEvaluator.kt
keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ApproveOldVersionTests.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/actuation/EnvironmentConstraintRunner.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/constraints/AllowedTimesConstraintEvaluator.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/constraints/ArtifactUsedConstraintEvaluator.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/constraints/DependsOnConstraintEvaluator.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/services/ApplicationService.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/actuation/EnvironmentConstraintRunnerTests.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/services/ApplicationServiceTests.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/config/KeelConfigurationFinalizer.kt

I noticed `ConstraintEvaluator` was the only keel plugin interface that was not in the `plugins` package. This is just moving it there where it belongs.

chore(*): Move ConstraintEvaluator to plugins package

---

keel-sql/keel-sql.gradle.kts

I had previously added this task to work around the fact that, when building the Netflix wrapper project, the joog-generated files ended up in the wrong place. After @robfletcher's changes in #1426, though, not only was this unnecessary, but it was causing the composite build to fail on my machine as I had left-over files from previous builds that were being copied and overwriting the correct, newly generated ones in `keel`.

fix(build): Remove unnecessary task to copy generated jooq files

---

keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/ClusterDeployStrategy.kt
keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/model/ActiveServerGroup.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/api/ClusterDeployStrategyTests.kt
keel-ec2-api/src/main/kotlin/com/netflix/spinnaker/keel/api/ec2/ServerGroup.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandler.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandlerTests.kt
keel-orca/src/main/kotlin/com/netflix/spinnaker/keel/orca/ClusterExportHelper.kt
keel-orca/src/main/kotlin/com/netflix/spinnaker/keel/orca/_clusterDeployStrategies.kt
keel-orca/src/test/kotlin/com/netflix/spinnaker/keel/orca/ClusterDeployStrategyTests.kt
keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/titus/cluster/TitusClusterHandler.kt
keel-titus-plugin/src/test/kotlin/com/netflix/spinnaker/keel/titus/resource/TitusClusterHandlerTests.kt

Clusters that don't use Discovery-based health need to send an additional parameter to Orca, and should be considered healthy regardless of Discovery health counts.

support non discovery clusters

---

keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/Locatable.kt
keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/Locations.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/services/ApplicationService.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/AuthorizationSupport.kt

As discussed, certain resources won't concern themselves with VPCs and subnets. This PR introduces an even simpler `Locations` implementation that contains the regions alone.

feat(api): Enable resources with just regions for locations

---

keel-ec2-api/src/main/kotlin/com/netflix/spinnaker/keel/api/ec2/ServerGroup.kt

If a cluster's instances are registered in discovery we'll wait forever for them to be `unknown` which is just as dumb as waiting for ones that _do_ use discovery to be `up`.

Handle a cluster that does use discovery but is configued not to

---

.gitignore
keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/Monikered.kt
keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/ResourceSpec.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/core/api/ResourceSummary.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/jackson/KeelApiModule.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/jackson/mixins/ResourceSpecMixin.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/services/ApplicationService.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/serialization/SubmittedEnvironmentDeserializerTests.kt
keel-docker/src/test/kotlin/com/netflix/spinnaker/keel/docker/SampleDockerImageResolver.kt
keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/LegacySpecUpgradeTests.kt
keel-test/src/main/kotlin/com/netflix/spinnaker/keel/test/Resources.kt

Adds a `displayName` property to `ResourceSpec` and `ResourceSummary` such that we have a consistent way of figuring out what to display in the UI for all resource types.

feat(resources): Add standardized display name for resources

---

keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/ArtifactInterfaces.kt
keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/Resource.kt

Instead of checking for `ComputeResourceSpec` to figure out which resources have links to artifacts, just check the artifact-provider interfaces it wraps, allowing for other types of resources to provide that information. This is required to enable our current work on internal resource plugins.
Also, annotates a few methods on those interfaces with `@JvmDefault` so they can be used in Java plugins.
Cc: @erikmunson

fix(core): Don't make assumptions about which resources link to artifacts

---

Dockerfile.compile
gradle.properties
keel-sql/keel-sql.gradle.kts
keel-sql/src/main/resources/jooqConfig.xml

This PR introduces the ability to build keel inside a Docker container by installing MySQL in the container, then using liquibase and the standard jOOQ code generation tool in place of the jooqModelator plugin (which itself uses Docker).
Cc: @nimakaviani

feat(build): Replace jooqModelator with native jooq tooling + docker

---

keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/CloudDriverService.kt
keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/model/ActiveServerGroup.kt
keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/model/TitusActiveServerGroup.kt
keel-clouddriver/src/test/kotlin/com/netflix/spinnaker/keel/clouddriver/model/ActiveServerGroupTest.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/exceptions/ActiveServerGroupsException.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/api/ec2/constraints/Ec2CanaryConstraintDeployHandlerTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/TestUtils.kt
keel-orca/src/test/kotlin/com/netflix/spinnaker/keel/orca/ClusterExportHelperTests.kt
keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/titus/cluster/TitusClusterHandler.kt
keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/titus/cluster/TitusClusterSpec.kt
keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/titus/cluster/TitusServerGroup.kt
keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/titus/exceptions/ActiveServerGroupsException.kt
keel-titus-plugin/src/test/kotlin/com/netflix/spinnaker/keel/titus/resource/TestUtils.kt
keel-titus-plugin/src/test/kotlin/com/netflix/spinnaker/keel/titus/resource/TitusClusterHandlerTests.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/PassThruController.kt

Fist stab at addressing https://github.com/spinnaker/keel/issues/1084 for titus only (titus is less complicated). Feedback desired.
This PR adds a new property to the server group response (`onlyEnabledServerGroup`) which defaults to true. When the desired state is resolved for a server group, it is also true. When we fetch the current state of clusters we calculate whether that property is true or false for each "active server group" (aka the one we're looking at to see if it's in the right state or not).
If `onlyEnabledServerGroup == false`, and that's the only diff, then we disable the oldest active server group (heuristic alert! feedback desired!). The heuristic is: disable the oldest active server group with the _wrong version_ until there are none left. Then, do the same with …

feat(titus): only allow one active server group

---

keel-ec2-api/src/main/kotlin/com/netflix/spinnaker/keel/api/ec2/ServerGroup.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandler.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandlerTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/TestUtils.kt
keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/titus/cluster/TitusClusterHandler.kt
keel-titus-plugin/src/test/kotlin/com/netflix/spinnaker/keel/titus/resource/TitusClusterHandlerTests.kt

Follow up to https://github.com/spinnaker/keel/pull/1448: same functionality, but for EC2!
Also, fixing the titus tests to correctly throw a not found when there are no server groups, instead of returning the wrapper object with an empty list like I incorrectly expected it to.
Closes https://github.com/spinnaker/keel/issues/1084

feat(ec2): don't allow multiple enabled ASGs

---

keel-artifact/src/main/kotlin/com/netflix/spinnaker/keel/artifacts/BaseArtifactSupplier.kt
keel-igor/src/main/kotlin/com/netflix/spinnaker/keel/services/ArtifactMetadataService.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/ArtifactController.kt

- changed `retry` logic to support kotlin coroutines
- added an external endpoint for calling the artifact service, currently for debugging purposes.

fix(retry): fixing retry for artifact metadata service

---

keel-orca/src/main/kotlin/com/netflix/spinnaker/keel/orca/OrcaService.kt
keel-orca/src/main/kotlin/com/netflix/spinnaker/keel/orca/OrcaTaskMonitorAgent.kt

keel assumed that failed orca tasks always had certain fields present in the context about the exception. This turned out not to be true. This change makes all exception fields optional so keel doesn't throw a deserialization exception.
In addition, if keel encountered an error when deserializing a task, that would prevent it from processing other tasks that are valid. This PR adds a warning log instead of throwing an exception.

fix(orcaException): fix deserialization issue while parsing errors from orca

---

keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/titus/jackson/TitusClusterSpecDeserializer.kt

This was an error caused when moving from a `@JsonCreator` factory method see https://github.com/spinnaker/keel/blob/v0.173.0/keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/api/titus/cluster/TitusClusterSpec.kt#L95-L112 to a custom deserializer (in order to remove Jackson annotations from the API types).

Fix deserialization of Titus cluster resources

---

keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlArtifactRepository.kt

In the `markAsSuccessfullyDeployedTo` function, the query to determine the list of approved artifact versions was too broad. This change strengthens the WHERE clause.

fix(db): narrow scope of database query

---

keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/titus/jackson/mixins/TitusClusterSpecMixin.kt

We were ignoring the `container` field when serializing, but requiring it when deserializing:
https://github.com/spinnaker/keel/blob/9e944c253820818464d92e38a84be98c474671a3/keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/titus/jackson/TitusClusterSpecDeserializer.kt#L48-L49
This just removes the unnecessary annotated field from the mixin.

fix(titus): Revert ignoring serialization of container field in TitusClusterSpec

---

keel-artifact/src/main/kotlin/com/netflix/spinnaker/keel/artifacts/DebianArtifactSupplier.kt
keel-artifact/src/test/kotlin/com/netflix/spinnaker/keel/artifacts/NpmArtifactSupplierTests.kt
keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/keel/bakery/artifact/ImageHandler.kt
keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/keel/bakery/constraint/ImageExistsConstraintEvaluator.kt
keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/ImageService.kt
keel-core/src/main/java/com/netflix/rocket/semver/shaded/DebianVersionComparator.java
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/artifacts/NetflixSemVerVersioningStrategy.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/core/VersioningStrategyComparators.kt
keel-core/src/test/java/com/netflix/rocket/semver/shaded/DebianVersionComparatorTest.java
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/artifacts/NetflixSemverVersioningStrategyTests.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/constraints/Ec2CanaryConstraintDeployHandler.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resolvers/ImageResolver.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandler.kt

In this PR:
- Update for shaded Rocket's `DebianVersionComparator` which fixes the `NumberFormatException`
- Additional updates to the regular expression used in `NpmArtifactSupplier` such that it matches the format used for Debian packages at Netflix and allows us to continue to use the same comparator.
As noted in the `TODOs` added in this PR, in my opinion we should consolidate/simplify our parsing of semantic version strings, ideally by using an off-the-shelf library like we're already using for Docker tags, but at the very least consolidating between our usage of the `frigga` library's `AppVersion` class and the Rocket code when comparing versions for Debian and NPM.

fix(artifacts): More fixes for NPM version parsing

---

keel-orca/src/main/kotlin/com/netflix/spinnaker/keel/orca/OrcaExecutionStatus.kt

We got the following error because keel was not aware of the "buffered" orca execution status.
```
com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `com.netflix.spinnaker.keel.orca.OrcaExecutionStatus` from String "BUFFERED": not one of the values accepted for Enum class: [SKIPPED, SUCCEEDED, NOT_STARTED, FAILED_CONTINUE, SUSPENDED, TERMINAL, STOPPED, PAUSED, RUNNING, CANCELED, REDIRECT]
```
Add support for this status.

fix(orca): support BUFFERED execution status

---

keel-artifact/src/test/kotlin/com/netflix/spinnaker/keel/artifacts/NpmArtifactSupplierTests.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/artifacts/NetflixSemVerVersioningStrategy.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/core/VersioningStrategyComparators.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/artifacts/NetflixSemverVersioningStrategyTests.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/core/VersioningStrategyComparatorsTests.kt

We were still failing to parse valid versions of NPM artifacts with Frigga in `NETFLIX_SEMVER_COMPARATOR`. This PR fixes that by replacing the use of Frigga in this case with our internal parser, using a regular expression we know matches Rocket and accommodates for version strings with and without the package name as a prefix.

fix(artifacts): Fix Netflix semver version comparisons

---

keel-schema-generator/src/main/kotlin/com/netflix/spinnaker/keel/schema/Generator.kt
keel-schema-generator/src/test/kotlin/com/netflix/spinnaker/keel/schema/GeneratorTests.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/config/DefaultConfiguration.kt

Since Keel accepts enums case-insensitively and we typically document them as lower case this PR makes the schema generator emit them as lower-case as well.

Document enums in schema as lower case

---

keel-igor/src/main/kotlin/com/netflix/spinnaker/igor/BuildService.kt
keel-igor/src/main/kotlin/com/netflix/spinnaker/model/Build.kt

Going off on a hunch here that maybe the reason we're getting `null` from the retrofit call is that we're failing to parse the response as JSON (even though I'd have expected that to log an exception, which it doesn't).

fix(artifacts): Attempt to fix retrieval of artifact metadata from igor

---

keel-igor/src/main/kotlin/com/netflix/spinnaker/keel/services/ArtifactMetadataService.kt

Just in case we're getting extraneous whitespace in the Rocket events (I don't think we are, but running out of ideas)...

fix(artifacts): Last try at fixing call to igor

---

keel-echo/src/main/kotlin/com/netflix/spinnaker/keel/echo/ManualJudgementNotifier.kt
keel-echo/src/test/kotlin/com/netflix/spinnaker/keel/echo/ManualJudgementNotifierTests.kt
keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/spring/SpringStartupTests.kt
keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/tx/DeliveryConfigTransactionTests.kt
keel-web/src/test/resources/application.properties

Improves the manual judgement (Slack) notification by adding a link to the corresponding artifact version in the Environments view and restructuring the format to make it more easily readable.
Sample:
Closes #1266

feat(notifications): Improve manual judgement notifications

---

keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/ClusterDeployStrategy.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/jackson/mixins/ClusterDeployStrategyMixin.kt
keel-ec2-api/src/main/kotlin/com/netflix/spinnaker/keel/api/ec2/ApplicationLoadBalancerSpec.kt
keel-ec2-api/src/main/kotlin/com/netflix/spinnaker/keel/api/ec2/ClassicLoadBalancerSpec.kt
keel-ec2-api/src/main/kotlin/com/netflix/spinnaker/keel/api/ec2/SecurityGroupSpec.kt
keel-ec2-api/src/main/kotlin/com/netflix/spinnaker/keel/api/ec2/old/ApplicationLoadBalancerV1Spec.kt
keel-orca/src/main/kotlin/com/netflix/spinnaker/keel/orca/_clusterDeployStrategies.kt
keel-schema-generator/src/main/kotlin/com/netflix/spinnaker/keel/schema/Generator.kt
keel-schema-generator/src/main/kotlin/com/netflix/spinnaker/keel/schema/Schema.kt
keel-schema-generator/src/test/kotlin/com/netflix/spinnaker/keel/schema/GeneratorTests.kt
keel-titus-api/src/main/kotlin/com/netflix/spinnaker/keel/api/titus/TitusClusterSpec.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/config/KeelConfigurationFinalizer.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/apidocs/ApiDocCompatibilityTests.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/apidocs/ApiDocTests.kt
keel-web/src/test/resources/examples/cluster-example.yml
keel-web/src/test/resources/examples/delivery-config-example.yml
keel-web/src/test/resources/examples/ec2-cluster-with-autoscaling-example.yml
keel-web/src/test/resources/examples/titus-cluster-with-artifact-example.yml
keel-web/src/test/resources/examples/wrong-resource-kind.yml

Now each type of resource specifies the kind alongside the matching spec format in a way JSON schema validation can pick up.
Instead of being: 
```yaml
$defs:
SubmittedResource:
properties:
metadata:
type: object
kind:
enum:
- ec2/cluster@v1
- titus/cluster@v1
ClusterSpecSubmittedResource:
allOf:
- $ref: #/$defs/SubmittedResource
- type: object
properties:
spec:
$ref: #/$defs/ClusterSpec
TitusClusterSpecSubmittedResource:
allOf:
- $ref: #/$defs/SubmittedResource
- type: object
properties:
spec:
$ref: #/$defs/TitusClusterSpec
```
It will now be:
```yaml
$defs:
SubmittedResource:
properties:
kind:
enum:
- ec2/cluster@v1
- titus/cluster@v1
allOf:
- if:
properties:
kind:
const: ec2/cluster@v1
then:
properties:
spec:
$ref: #/$defs/ClusterSpec
- if:
properties:
kind:
const: titus/cluster@v1 …
```

Better representation of resource kinds in schema

---

keel-schema-generator/src/main/kotlin/com/netflix/spinnaker/keel/schema/Generator.kt
keel-schema-generator/src/main/kotlin/com/netflix/spinnaker/keel/schema/Schema.kt
keel-schema-generator/src/test/kotlin/com/netflix/spinnaker/keel/schema/GeneratorTests.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/apidocs/ApiDocCompatibilityTests.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/apidocs/ApiDocTests.kt

Previously I was using `format: duration` for properties that are `java.time.Duration` however that's not actually one of the formats supported by JSON schema and is an extension from Open API. Here I've replaced it with a regex pattern that enforces correct duration format.

fix(schema): specify duration as a regex

---

keel-schema-generator/src/main/kotlin/com/netflix/spinnaker/keel/schema/Generator.kt
keel-schema-generator/src/main/kotlin/com/netflix/spinnaker/keel/schema/Schema.kt
keel-schema-generator/src/test/kotlin/com/netflix/spinnaker/keel/schema/GeneratorTests.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/apidocs/ApiDocCompatibilityTests.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/apidocs/ApiDocTests.kt
keel-web/src/test/resources/examples/security-group-with-cidr-rule-example.yml

Without specifying `additionalProperties: false` some ingress rules can look like other types. That caused errors for users because the schema couldn't distinguish between the ingress rule types. I've made `additionalProperties: false` be the default for objects except where it's creating parameterized types.
Also, fixed values, such as singleton objects were being rendered as an `enum` with a single value when they can just be a `const`.
Addresses one of the things in #1535

Disambiguate ingress rule types in schema

---

keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/artifacts/PublishedArtifact.kt
keel-artifact/src/test/kotlin/com/netflix/spinnaker/keel/artifacts/ArtifactListenerTests.kt

I forgot that artifact events coming from echo have upper-case artifact type strings... 😛

fix(artifacts): Fix handling of upper-case artifact types

---

keel-sql/keel-sql.gradle.kts
keel-sql/src/main/resources/db/changelog/20200925-environment-related-indices.yml

PR #1540 adds an index composed of 4 `varchar(255)` columns. Therefore the size of the index you'd think would be 1020 bytes (4 * 255). The max index size in MySQL InnoDB tables is 3072 bytes. However, when using utf8mb4 character data the columns use 4 bytes per character so the index is actually 4080 bytes -- larger than the 3072 byte limit.
This was exacerbated by the fact that the dockerized mySQL database we use to run the `jooqGenerate` task in Gradle was not set up to use utf8 so the problem was not caught until deployment time.

Fix DB index size

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/core/api/EnvironmentSummary.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/services/ApplicationService.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/services/ApplicationServiceTests.kt
keel-test/src/main/kotlin/com/netflix/spinnaker/keel/test/Resources.kt

We got a bug report for a scenario where the user had a delivery config with two artifacts pointing to the same Debian package but with different release statuses. The `/application` API would return an incorrect artifact summary (with empty environments) for one of the artifacts. It turns out we were looking up the corresponding environment summary by artifact type and name only (as opposed to by reference), which was causing results not to be found.
I recommend viewing the diff with "ignore whitespace" enabled.

fix(artifacts): Fix summaries for same artifact with different release statuses

---

keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandler.kt

Extract common code into a method. This is code that generates the payload for the orca job that creates new server groups.
No (intentional)) behavior changes in this PR.
This is prep work for adding support for different [EBS volume types](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-volume-types.html). That future work should only require modifying the new function.

refactor(ec2): extract method

---

keel-cli/keel-cli.gradle.kts
keel-cli/src/main/kotlin/com/netflix/spinnaker/config/KeelCliConfiguration.kt
keel-cli/src/main/kotlin/com/netflix/spinnaker/keel/cli/KeelCli.kt
keel-cli/src/main/kotlin/com/netflix/spinnaker/keel/cli/commands/DataGenCommand.kt
keel-cli/src/main/resources/logback.xml
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/serialization/ObjectMappers.kt
settings.gradle.kts

Introduces a simple Spring Boot console application that can be used to aid in development and testing. In this PR, a single command is defined, `datagen`, which populates the local database with test records to assist with testing.

feat(cli): Keel data generation CLI

---

keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/keel/bakery/constraint/ImageExistsConstraintEvaluator.kt

If the app version associated with an AMI does not conform to the Frigga library convention, the exception thrown is:
```
java.lang.NullPointerException: AppVersion.parseName(version) must not be null
at com.netflix.spinnaker.keel.bakery.constraint.ImageExistsConstraintEvaluator$findMatchingImage$1.invokeSuspend(ImageExistsConstraintEvaluator.kt:57)
```
This change displays the problematic app version string to the exception message.

fix(bakery): better exception message on bad AMI version string

---

keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/artifacts/constants.kt
keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/persistence/KeelReadOnlyRepository.kt
keel-artifact/src/main/kotlin/com/netflix/spinnaker/keel/artifacts/ArtifactListener.kt
keel-artifact/src/test/kotlin/com/netflix/spinnaker/keel/artifacts/ArtifactListenerTests.kt
keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/keel/bakery/artifact/ImageHandler.kt
keel-bakery-plugin/src/test/kotlin/com/netflix/spinnaker/keel/bakery/artifact/ImageHandlerTests.kt
keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ArtifactRepositoryTests.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ArtifactRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/services/ApplicationService.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/services/ApplicationServiceTests.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/ApplicationController.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/ApplicationControllerTests.kt

Introduces the `maxArtifactVersions` query parameter to the `GET /application` API, which allows the caller to specify the maximum number of artifact versions to return (in descending order). This will give us more flexibility in the UI, and allow us to run performance tests with a higher number of versions.

feat(api): API support for limiting artifact versions

---

keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/PeriodicallyCheckedRepositoryTests.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/actuation/CheckScheduler.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/actuation/ResourceActuator.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/CombinedRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/DeliveryConfigRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/KeelRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/PeriodicallyCheckedRepository.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/actuation/IntermittentFailureTests.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/actuation/ResourceActuatorTests.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlDeliveryConfigRepository.kt
keel-sql/src/main/resources/db/changelog/20200930-environment-check-lock.yml
keel-sql/src/main/resources/db/databaseChangeLog.yml
keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/SqlDeliveryConfigRepositoryPeriodicallyCheckedTests.kt

Instead of continuing to check environment promotions for paused apps, just ensure that resource checks wait until environment checks are reasonably recent. This is to allow for environment checks to catch up if the application has been paused, and we'll therefore deploy an up-to-date artifact rather than whatever was approved last time the app was un-paused. If manual intervention has happened during the pause time we could roll back to an unwanted older version.

refactor(environments): delay delivery config last checked at write

---

keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/model/ActiveServerGroup.kt
keel-clouddriver/src/test/kotlin/com/netflix/spinnaker/keel/clouddriver/model/ActiveServerGroupTests.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/constraints/Ec2CanaryConstraintDeployHandler.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandler.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/api/ec2/export/ClusterExportTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandlerTests.kt

Add support for managing EC2 apps that have been configured to use AWS launch templates.
Clouddriver now support AWS [launch templates](https://docs.aws.amazon.com/autoscaling/ec2/userguide/LaunchTemplates.html). Clouddriver opts in apps to use launch templates, on a per-app basis.
For apps that are configured to use launch templates, the response payload from clouddriver changes when querying for server group information. For these apps, there is no longer a `launchConfig` field. Instead, there is a `launchTemplate` field. The `launchTemplate` field contains similar information, but the data has a different shape.
With this PR, we can now handle response payloads from clouddriver where there is a `launchTemplate` field instead of a `launchConfig` field.
Note that this PR does not change: …

feature(ec2): Add support for launch templates

---

keel-bakery-plugin/keel-bakery-plugin.gradle.kts
keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/keel/bakery/constraint/ImageExistsConstraintEvaluator.kt

AMI lookup can be slow-ish (~ .75 seconds) and results do not change (until old AMIs get cleaned up at least) so we might as well cache the results of the lookup. We cannot cache a negative result since that would stop us responding to newly baked AMIs.

refactor(constraints): cache results of AMI lookup

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/actuation/ResourceActuator.kt

We have some resource checks that are failing because of a failed `checkNotNull` check, which consequently throws an exception. However, these failures weren't incrementing our metric that tracks the rate of failed resource check.
It turns out that this check happened outside of the try block, so the relevant catch block which publisehs the `ResourceCheckError` event doesn't get executed in this code path. 
This change widens the scope of the try block to ensure that a failed `checkNotNull` call gets properly captured as an error.
You'll want to ignore whitespace when viewing this diff.

fix(actuator): broaden scope of try block

---

keel-bakery-plugin/keel-bakery-plugin.gradle.kts
keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/keel/bakery/constraint/ImageExistsConstraintEvaluator.kt
keel-clouddriver/keel-clouddriver.gradle.kts
keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/config/ClouddriverConfiguration.kt
keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/CloudDriverCache.kt
keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/ImageService.kt
keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/MemoryCloudDriverCache.kt
keel-clouddriver/src/test/kotlin/com/netflix/spinnaker/keel/clouddriver/ImageServiceTests.kt
keel-clouddriver/src/test/kotlin/com/netflix/spinnaker/keel/clouddriver/MemoryCloudDriverCacheTest.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resolvers/NetworkResolverTests.kt

Adds metrics to Clouddriver cache, also moves AMI caching into `ClouddriverCache` instead of being a standalone thing

Metrics for clouddriver cache

---

keel-ec2-api/src/main/kotlin/com/netflix/spinnaker/keel/api/ec2/ServerGroup.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandler.kt
keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/titus/TitusClusterHandler.kt

my titus cluster was "healthy" even though it had 0 instances (I asked for one). That's not healthy.

fix(heath): consider 0 instances unhealthy when you've asked for > 0

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/actuation/ResourceActuator.kt

We are seeing resource check errors that look like:
```
java.lang.IllegalStateException: Failed to find environment for
ec2:application-load-balancer:test:foo in deliveryConfig foo-manifest
```
It appears that the `DeliveryConfig.environmentFor` method is returning null, even though the resource exists in an environment in the delivery config.
PR #1557 changed when `DeliveryConfig.environmentFor` gets called. Previously, it was only invoked for resources associated with versioned artifacts. After that PR, it was invoked for all resources.
It appears that this call isn't working for the application load balancer resource. Not sure why. 
Change the implementation of `DeliveryConfig.environmentFor` so that it looks up a resource by id instead of doing an equality check.

fix(actuator): check for resource by id

---

keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/plugins/ActionDecision.kt
keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/plugins/ActionResponse.kt
keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/plugins/ResourceHandler.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/actuation/ResourceActuator.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/events/ResourceEvent.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ResourceRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/services/ResourceStatusService.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/actuation/IntermittentFailureTests.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/actuation/ResourceActuatorTests.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandler.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandlerTests.kt
keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/titus/TitusClusterHandler.kt
keel-titus-plugin/src/test/kotlin/com/netflix/spinnaker/keel/titus/resource/TestUtils.kt
keel-titus-plugin/src/test/kotlin/com/netflix/spinnaker/keel/titus/resource/TitusClusterHandlerTests.kt

Introducing a new behavior for resource handlers: the ability to pass on doing anything.
Why do we want this? Sometimes we can detect that there is a diff but we can't act on it. When might this be? Well, we might have situations where there is a diff (say, instances are unhealthy or there are too many active server groups) but we don't have enough information to fix the problem. Right now we get that way when there are two active server groups and the most recent is unhealthy (*note* I will work towards making this not the case, but I don't think I can make progress unless we have a way to opt out of taking action).
We want to communicate that we can't resolve the diff to the user. I'm doing this by adding a new state called `DIFF_NOT_ACTIONABLE`. 
This is not a great state for the user …

feat(handlers): allow handler to pass on taking action

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/actuation/ResourceActuator.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/actuation/IntermittentFailureTests.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/actuation/ResourceActuatorTests.kt

disabling new status with fast property backed property.
we can turn on (then remove this code) once the UI is all set.

fix(ui): disable new status

---

keel-echo/src/main/kotlin/com/netflix/spinnaker/keel/echo/ManualJudgementNotifier.kt

This will put the *Message* field up at the top of the notification body, when available.

refactor(slack): Reposition commit message in manual judgement notifications

---

keel-core/keel-core.gradle.kts
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/actuation/EnvironmentPromotionChecker.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/actuation/ResourceActuator.kt

Annotates `ResourceActuator.checkResource` and `EnvironmentPromotionChecker.checkEnvironments` so that New Relic will record traces for them (which doesn't happen by default for Kotlin suspend functions).
This won't have any practical effects in any environment where the New Relic agent is not actually running.
Reference: https://docs.newrelic.com/docs/agents/java-agent/api-guides/java-agent-api-instrument-using-annotation

chore(monitoring): Enable New Relic tracing in select methods

---

keel-ec2-api/src/main/kotlin/com/netflix/spinnaker/keel/api/ec2/InstanceProvider.kt

The instance profiles plugin needs this

Fix missing discriminator for instance provider

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/jackson/CommitMessageSerializer.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/jackson/KeelApiModule.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/jackson/mixins/CommitMixin.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/ApplicationControllerTests.kt

We've been using Slack markdown syntax for hyperlinks in commit messages because they render nicely in Slack, but not so much in the UI. This PR converts the link syntax so that it will render OK in the UI. 
Note: depends on a UI update to run the commit message text through the markdown parser.
Cc: @erikmunson

fix(api): Convert crazy Slack markdown syntax

---

keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/model/ActiveServerGroup.kt
keel-clouddriver/src/test/kotlin/com/netflix/spinnaker/keel/clouddriver/model/ActiveServerGroupTests.kt
keel-ec2-plugin/keel-ec2-plugin.gradle.kts
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/constraints/Ec2CanaryConstraintDeployHandler.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandler.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/api/ec2/export/ClusterExportTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandlerTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/LaunchConfigTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/TestUtils.kt

Add support for managing EC2 apps that have been configured to use AWS launch templates. This is a second 
attempt at #1566, which was reverted in #1573 because of a bug.
When resolving the current status of a cluster, if the current launch configuration contains a ramdisk id field that is
an empty string: `""`, keel is supposed to treat it as a `null`.
#1566 introduced a regression where it did not convert the blank string to a null. This led to false diffs where
the current state of an EC2 cluster had a ramdisk id of `""` and the desired state of an cluster had a ramdisk id of `null`.
A test has been added for this case. 
The rest of this description is identical to #1566.
Clouddriver now support AWS [launch templates](https://docs.aws.amazon.com/autoscaling/ec2/userguide/LaunchTemplates …

feature(ec2): Add support for launch templates, take 2

---

keel-artifact/src/main/kotlin/com/netflix/spinnaker/keel/artifacts/DebianArtifactSupplier.kt
keel-artifact/src/test/kotlin/com/netflix/spinnaker/keel/artifacts/DebianArtifactSupplierTests.kt
keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/keel/bakery/artifact/ImageHandler.kt
keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/ImageService.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/constraints/Ec2CanaryConstraintDeployHandler.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resolvers/ImageResolver.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandler.kt

This PR is wrapping all calls to Frigga to parse a version with try/catch, adding logs around it, and throw `systemException` if needed.

chore(frigga): handle frigga exceptions gracefully

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/actuation/ResourceActuator.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/telemetry/TelemetryEvent.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/telemetry/TelemetryListener.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/actuation/ResourceActuatorTests.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/ApplicationEventTests.kt

**Problem:**
One of the most helpful things we can do in MD is veto an artifact when the version isn't good (like, when the deploy times out because the instances never came up). 
One of the most _unhelpful_ things we can do is veto artifacts en mass when there is a problem (either with keel, with spinnaker, or with a cloud provider).
**Solution:**
This PR aims to narrow the scope of vetoing artifact versions to only veto versions that have **never** been successfully deployed. That means that we will no longer veto artifact versions that have been happy in an environment. 
We will not veto an artifact version if:
- there was a config change that is causing the instances to not start up
- there is a keel bug that causes the desired state of everything to change in a way that causes bad …

feat(artifact): veto only if never deployed successfully

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/actuation/ResourceActuator.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/veto/unhappy/UnhappyVeto.kt

I'm having a hard time troubleshooting an issue without logs in this area of the code.

chore(debug): Add debug logs around resource vetoing

---

keel-artifact/src/main/kotlin/com/netflix/spinnaker/keel/artifacts/DebianArtifactSupplier.kt
keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/keel/bakery/artifact/ImageHandler.kt
keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/keel/bakery/constraint/ImageExistsConstraintEvaluator.kt
keel-bakery-plugin/src/test/kotlin/com/netflix/spinnaker/keel/bakery/constraint/ImageExistsConstraintEvaluatorTests.kt
keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/config/ClouddriverConfiguration.kt
keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/ImageService.kt
keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/MemoryCloudDriverCache.kt
keel-clouddriver/src/test/kotlin/com/netflix/spinnaker/keel/clouddriver/ImageServiceTests.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/_appVersions.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/_maps.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/caffeine/CacheFactory.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/constraints/Ec2CanaryConstraintDeployHandler.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resolvers/ImageResolver.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandler.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/api/ec2/constraints/Ec2CanaryConstraintDeployHandlerTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resolvers/ImageResolverTests.kt

Keel has always only supported deploying a single "named image" to a cluster. However, there are situations where the correct app version may have different image names in each region. e.g.
* Bakery retries one region
* Multiple bakes happen targeting different individual regions
In this case we can fail to ever resolve the AMI because we only look at the latest image with a matching app version tag.
This led to an issue where a managed cluster in one region existed side-by-side with a pipeline deployed cluster in another.
Keel launched a bake, which succeeded, and it started deploying the cluster.
Meanwhile, the pipeline-initiated bake completed and the image it created was in the "wrong" region for the managed cluster.
Keel was no longer able to resolve the desired state of the cluster, …

Support AMIs where regions were baked individually

---

keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/ImageService.kt
keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/model/NamedImage.kt
keel-clouddriver/src/test/kotlin/com/netflix/spinnaker/keel/clouddriver/ImageServiceTests.kt

`ImageHandler` previously looked at a single `NamedImage` and could potentially think regions were missing if they were split across multiple image names.
This PR changes things so that the method in `ImageService` that finds the latest image for an artifact, looks for all named images that share the latest `appVersion` and `base_ami_version` tags.
This will stop metrics flagging that a region is missing in such a case.

Detect AMIs split across multiple named images when checking for latest baked versions

---

keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/titus/ContainerAttributesResolver.kt
keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/titus/DefaultContainerAttributes.kt
keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/titus/exceptions/AwsAccountConfigurationException.kt
keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/titus/exceptions/DefaultContainerAttributesException.kt
keel-titus-plugin/src/test/kotlin/com/netflix/spinnaker/keel/titus/ContainerAttributesResolverTests.kt

The titus team recently started setting some default container attributes. This adds them to a user spec if they're not present.
Default values are pulled from the config.
You can turn it off via fast property in case we mess something up :)

feat(titus): default container attrs resolver

---

keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/UnhappyVetoRepositoryTests.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/UnhappyVetoRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/veto/unhappy/UnhappyVeto.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/actuation/IntermittentFailureTests.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/veto/UnhappyVetoTests.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlUnhappyVetoRepository.kt

After much debugging, I found that, if a resource had been previously vetoed and a new diff detected, instead of rechecking the resource as expected after the wait period, we were just repeatedly vetoing it because we were always updating the `recheckTime` in that case, so it never expired.
This PR fixes that by introducing a check for only inserting a record when the veto is first created for the resource, and only updating it when the recheck time has expired, but _not_ in the in-between checks. I found it pretty hard to reason about this code because half of the business logic was in the `SqlUnhappyVetoRepository`, so this PR also refactors the code a bit to consolidate all the logic in `UnhappyVeto` which makes it easier to follow and to test.

fix(veto): Fix never-expiring resource vetos

---

keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/plugins/ArtifactSupplier.kt
keel-artifact/src/main/kotlin/com/netflix/spinnaker/keel/artifacts/ArtifactListener.kt
keel-artifact/src/main/kotlin/com/netflix/spinnaker/keel/artifacts/DebianArtifactSupplier.kt
keel-artifact/src/main/kotlin/com/netflix/spinnaker/keel/artifacts/DockerArtifactSupplier.kt
keel-artifact/src/main/kotlin/com/netflix/spinnaker/keel/artifacts/NpmArtifactSupplier.kt
keel-artifact/src/test/kotlin/com/netflix/spinnaker/keel/artifacts/ArtifactListenerTests.kt
keel-artifact/src/test/kotlin/com/netflix/spinnaker/keel/artifacts/DebianArtifactSupplierTests.kt
keel-artifact/src/test/kotlin/com/netflix/spinnaker/keel/artifacts/DockerArtifactSupplierTests.kt
keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ArtifactRepositoryTests.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlArtifactRepository.kt

This PR move that responsibility to each artifact provider in a unified way, giving us an easy way to control the versions we want to filter at the API level.

feat(processArtifacts): Move artifact processing decision to individual suppliers

---

keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/persistence/KeelReadOnlyRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/CombinedRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/KeelRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ResourceRepository.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlResourceRepository.kt

Previously on updating a resource the migrators were applied so the "current" resource compared with the request payload would be the latest spec version. If the only change in the payload was to update the version (and associated changes in spec format) the update would appear to be a no-op. This PR introduces a new repository method `getRaw` that retrieves the resource as currently stored in the database (without applying migrators). This is only intended for use in the update request flow.

Allow resource updates to change version

---

keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/titus/ContainerAttributesResolver.kt
keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/titus/DefaultContainerAttributes.kt
keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/titus/exceptions/DefaultContainerAttributesException.kt
keel-titus-plugin/src/test/kotlin/com/netflix/spinnaker/keel/titus/ContainerAttributesResolverTests.kt

Upon further reflection, let's not barf if we don't have a subnet entry. Let's just not add a key.

fix(titus): if we don't have a region be okay

---

keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/schema/Optional.kt
keel-ec2-api/src/main/kotlin/com/netflix/spinnaker/keel/api/ec2/SecurityGroupRule.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/jackson/KeelEc2ApiModule.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/jackson/SecurityGroupSpecDeserializer.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/jackson/mixins/ReferenceRuleMixin.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/jackson/mixins/SecurityGroupRuleMixin.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/SecurityGroupHandler.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/api/ec2/SecurityGroupRuleTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/api/ec2/SecurityGroupTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/SecurityGroupHandlerTests.kt

Previously we required that users omit the `name` propertly in order to make a `ReferenceRule` self-referential. However, this results in spurious unresolvable diffs if the user _does_ specify the name. The cause is not obvious.
It makes more sense to default the name so that users _may_ omit it or supply it as they prefer.

Default name for self-referential ingress rules

---

keel-artifact/src/main/kotlin/com/netflix/spinnaker/keel/artifacts/DebianArtifactSupplier.kt
keel-artifact/src/test/kotlin/com/netflix/spinnaker/keel/artifacts/DebianArtifactSupplierTests.kt

we actually need the artifact name to parse the version with Frigga.

fix(appversion): fix for wrong version parsing

---

keel-artifact/src/test/kotlin/com/netflix/spinnaker/keel/artifacts/ArtifactListenerTests.kt
keel-bakery-plugin/src/test/kotlin/com/netflix/spinnaker/keel/bakery/artifact/ImageHandlerTests.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/actuation/ResourceActuatorTests.kt
keel-titus-plugin/src/test/kotlin/com/netflix/spinnaker/keel/titus/resource/TitusClusterHandlerTests.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/DeliveryConfigControllerTests.kt

`any()` just satisfies the compile-time type check, it doesn't assert that the runtime type of the parameter matches the generic. For that you need `ofType()`. I just discovered this yesterday. I've updated tests that _are_ attempting to verify the parameter type to use the correct matcher function.

Update inappropriate use of any() to ofType() in tests

---

keel-sql/src/main/kotlin/com/netflix/spinnaker/config/SqlConfiguration.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlDeliveryConfigRepository.kt

Because `ClusterV1Spec` is not a `ArtifactReferenceProvider` the `ArtifactUsedConstraintEvaluator` did not find the artifacts they use. We were accidentally not migrating resources read via `deliveryConfigsDueForCheck` and attempting to check v1 clusters instead of always checking v1.1 clusters.

Ensure resources in environment check cycle are migrated

---

keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/ResourceFactory.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlDeliveryConfigRepository.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlResourceRepository.kt
keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/SqlDeliveryConfigRepositoryPeriodicallyCheckedTests.kt

Tidy up PR for #1635. Adds a test for migrating resources when delivery configs are checked, and unifies logic for doing so across both repositories that need it.

tidy up migration fix

---

keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/schema/Optional.kt
keel-ec2-api/src/main/kotlin/com/netflix/spinnaker/keel/api/ec2/SecurityGroupRule.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/jackson/KeelEc2ApiModule.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/jackson/SecurityGroupSpecDeserializer.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/jackson/mixins/ReferenceRuleMixin.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/jackson/mixins/SecurityGroupRuleMixin.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/SecurityGroupHandler.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/api/ec2/DeserializationInjectionTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/api/ec2/SecurityGroupRuleTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/api/ec2/SecurityGroupTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/SecurityGroupHandlerTests.kt

Restores changes made to deserialization of self-referential ingress rules in #1624 but fixes the fact I was assuming the wrong type for the injected `locations` value.

fix deserialization injection

---

keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/jackson/SecurityGroupSpecDeserializer.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/api/ec2/DeserializationInjectionTests.kt

Previous fix #1632 did not cater for ingress rules that appear inside a regional override on a security group spec.

Allow name injection in ingress rules in regional overrides

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/jackson/KeelApiModule.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/jackson/mixins/DeliveryConfigMixin.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/DeliveryConfigControllerTests.kt

I happened to notice the resources are included as an array at the top level of the delivery config JSON/YAML response as well as being under their respective environments. This is because `DeliveryConfig.resources` is a transient property not being ignored by Jackson.

Don't serialize resources at top level of delivery config

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/constraints/ArtifactUsedConstraintEvaluator.kt

Seems like this behavior is vetoing artifact versions and it's not clear why

add some logging so we can see what artifact used constraint is doing

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/actuation/ResourceActuator.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ArtifactRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/veto/unhappy/UnhappyVeto.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/actuation/ResourceActuatorTests.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlArtifactRepository.kt

One of our customers reported the following problems:
> - The automatic ‘mark as bad’ logic can mark artifacts bad that have never been deployed and is what’s blocking me
> -  There’s no way to manually ‘mark as good’ an artifact that was actually fine, but deployment failed due to a transient failure
> - The candidate waiting for approval to production (build 16) is the build currently healthy in test, despite it being marked bad. Looks like it went healthy just a couple of minutes after the deployment timed out
> - The automatic ‘mark as bad’ doesn’t mark bad for the production environment, so I bet if I accidentally approved build 16 it’d try to deploy. I guess I’d expect it to mark both as bad to prevent accidental deployment, or at least have the approval workflow not fire
> - …

fix(veto): Do not mark never-deployed versions as bad

---

keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/plugins/ResourceHandler.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/actuation/ResourceActuator.kt
keel-core/src/test/java/com/netflix/spinnaker/keel/actuation/MapBackedResourceSpec.java
keel-core/src/test/java/com/netflix/spinnaker/keel/actuation/SleepyJavaResourceHandler.java
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/actuation/ResourceActuatorTests.kt
keel-test/src/main/kotlin/com/netflix/spinnaker/keel/test/Resources.kt

Introduces Java-friendly counterparts to the `current` and `desired` methods in `ResourceHandler` that can be safely implemented in Java to avoid issues with shared threads with coroutines.
This is intended to address an issue we found where a Java-based plugin blocks in either of those calls, causing all of keel's resource actuation to also block since the Java code is entirely oblivious to coroutine management, but was blocking a coroutine thread.
My approach was to define methods that take in an `Executor` passed in by keel and that are expected to return a `CompletableFuture` that runs in that executor to complete its work. This allows keel to convert the future to a coroutine-friendly `Deferred` object that respects coroutine-specific behaviors like timeouts and cancellations.
This …

refactor(plugins): Define Java-friendly versions of ResourceHandler methods

---

gradle.properties
keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/DeliveryConfigRepositoryTests.kt
keel-sql/keel-sql.gradle.kts
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlDeliveryConfigRepository.kt
keel-web/keel-web.gradle.kts
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/DeliveryConfigControllerTests.kt

We were not checking whether the delivery config existed when deleting by name... This PR adds those checks and the corresponding tests.
I've had to upgrade `testcontainers` in order to test this locally since the latest version of Docker broke it.

Fix NPE deleting config by name

---

keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/DiffFingerprintRepositoryTests.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlDiffFingerprintRepository.kt

We were not resetting the action taken count on a new diff. We hadn't seen that before because usually a diff is cleared before a new diff comes in.

fix(diff): reset actions taken count for new diff

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/actuation/ResourceActuator.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/actuation/ResourceActuatorTests.kt

Rolled out successfully, so no longer need to hide this behind a flag

chore(diff): clean up property

---

keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/DeliveryConfigRepositoryTests.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlDeliveryConfigRepository.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlResourceRepository.kt

Discovered this by accident. If you move a resource from one environment to another the older entry in `environment_resource` remained there.

fix moving artifacts between environments

---

keel-orca/src/main/kotlin/com/netflix/spinnaker/keel/orca/ClusterExportHelper.kt

When exporting a cluster, if it was deployed by a pipeline using a red-black strategy, and there there was no `rollback` field in the context of the pipeline's deploy stage, then keel throws a null pointer exception when attempting to populate the `RedBlack.rollbackonFailure` field. 
Since the [RedBlack.rollbackOnFailure field is nullable][1], just return null if the `rollback` field isn't present in the pipeline's deploy context.
It felt like a lot of work to do given how much fixture setup is required for testing this. I manually unit tested it like this:
1.  Delete the `rollback` field in the [ClusterExportHelperTests][2] tests code.
2. Run the ClusterExportHelperTests tests and verify the tests fail.
3. Implement the fix
4. Run the tests again and verify they succeed.
[1]: …

fix(export): handle missing rollback field

---

keel-spring-test-support/src/main/kotlin/com/netflix/spinnaker/keel/spring/test/DisableSpringScheduling.kt
keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/spring/SpringStartupTests.kt
keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/tx/DeliveryConfigTransactionTests.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/config/IntegrationTestConfiguration.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/apidocs/ApiDocCompatibilityTests.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/apidocs/ApiDocTests.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/integration/AuthPropagationTests.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/integration/SchedulingResilienceTests.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/integration/SpringStartupTests.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/AdminControllerTests.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/ApplicationControllerTests.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/ApplicationEventTests.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/ArtifactControllerTests.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/DeliveryConfigControllerTests.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/ErrorSimulationControllerTests.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/EventControllerTests.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/ResourceControllerTests.kt

Noticed a bunch of noise in the CI build logs for #1660 where scheduled tasks were calling mocked repositories and there was no answer set up. I discovered a couple of tests where we'd missed disabling the scheduling. I also thought it might make sense to introduce a simpler annotation for that so the intent is clearer.

Cut down log noise in Spring tests

---

keel-orca/src/main/kotlin/com/netflix/spinnaker/keel/orca/ClusterExportHelper.kt
keel-orca/src/test/kotlin/com/netflix/spinnaker/keel/orca/ClusterExportHelperTests.kt

When attempting to export a cluster who was deployed by a pipeline whose deploy stage context is missing `delayBeforeDisableSec` or `delayBeforeScaleDownSec`, keel throws a 500 error with the following stack trace:
```
java.lang.NumberFormatException: For input string: "null"
at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
at java.lang.Integer.parseInt(Integer.java:652)
at java.lang.Integer.parseInt(Integer.java:770)
at com.netflix.spinnaker.keel.orca.ClusterExportHelper.contextToRedBlack(ClusterExportHelper.kt:134)
at com.netflix.spinnaker.keel.orca.ClusterExportHelper.access$contextToRedBlack(ClusterExportHelper.kt:16)
```
Since the `RedBlack` class already supported these two fields as nullable, just return a null if they are not present.
This is a …

fix(export): handle optional fields in context

---

keel-sql/src/main/resources/db/changelog/20201116-foreign-keys.yml

The `unhappy_veto` and `unhealthy` tables had a primary key of `resource_id`. I dropped that column and replaced it with `resource_uid` but didn't add a new primary key. Becuase `SqlUnhappyRepository` relies on `onDuplicateKeyIgnore` to avoid getting duplicate rows, this resulted in data corruption on that table.

Fix missing primary keys following foreign key changes

---

keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/DeliveryConfigRepositoryTests.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlDeliveryConfigRepository.kt
keel-test/src/main/kotlin/com/netflix/spinnaker/keel/test/DeliveryConfigs.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/ApplicationControllerTests.kt

I found out by accident that, when retrieving a delivery config via `GET /application/{application}/config`, the `metadata` field was always coming back empty, even when there was data in the database. Turns out we were not reading that column. This fixes that and adds a couple tests.

fix(api): Include metadata when retrieving delivery config by application

---

keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/verification/VerificationRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/telemetry/TelemetryEvent.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/telemetry/TelemetryListener.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/verification/VerificationRunner.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/verification/VerificationRunnerTests.kt

Not sure if we really need timing metrics since performance of verifications is not down to Keel. I'll add the usual metrics for scheduled check lag when I add the scheduled check itself.

basic metrics for start / end of verifications

---

keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ArtifactRepositoryTests.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ArtifactRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/CombinedRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/KeelRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/services/ApplicationService.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/artifacts/CreatedAtSortingStrategyTests.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/services/ApplicationServiceTests.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/services/ComparableLinksTests.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlArtifactRepository.kt
keel-test/src/main/kotlin/com/netflix/spinnaker/keel/test/artifacts.kt

We recently added a `see changes` button to compare between artifact versions.
**The current solution**
For each artifact version and status, we checked which corresponding status we need to compare against.
For example:
current --> will be compared against the latest previous version
deploying/approved --> will be compared against the current version
pending --> will be compared against the current version.
**The problem** 
We didn't take into account that if we have a pinned version, we have to include that version when making the comparison in most cases. Since we _**have**_ to provide the right order when creating the SCM compare link, we needed to handle those differently.
**The solution** 
We first check to see if there is a pinned version for that artifact, in the environment. If …

fix(pinning): return the right diffing link when a version is pinned

---

keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/ImageService.kt
keel-ec2-api/src/main/kotlin/com/netflix/spinnaker/keel/api/ec2/ServerGroup.kt

An issue arose recently where a new base AMI caused a new version of an image to get baked. Because on some instances the older image was cached Keel could arbitrarily pick either of the two available images (the one with the older base AMI, and the one with the newer one). This caused the desired state to flip-flop depending on which Keel instance checked it.
Exacerbating this is the fact that the cache is aggressively primed with any other regions found in the image. This meant that although the cache has a TTL of 1 hour it kept getting refreshed with the same value, extending the TTL.
This PR attempts to ensure we only prime the cache with additional regions if it currently doesn't contain a mapping for the app version / account / region combination, or the cached image is older than …

prevent unintentionally extending cache TTL

---

keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/artifacts/DeliveryArtifact.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/actuation/EnvironmentPromotionChecker.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/services/ApplicationService.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/services/ApplicationServiceTests.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/ApplicationController.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/ApplicationControllerTests.kt

This PR fixes the issue where we create summaries for environments where an artifact will never go. that is distracting and confusing in the UI. it does not spark joy.

fix(view): don't summarize artifact when unused

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/artifacts/ArtifactVersionLinks.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/services/ApplicationService.kt
keel-echo/src/main/kotlin/com/netflix/spinnaker/keel/echo/ManualJudgementNotifier.kt
keel-echo/src/test/kotlin/com/netflix/spinnaker/keel/echo/ManualJudgementNotifierTests.kt

Adding a "see changes" link whenever we send a manual judgment notification in slack.
Preview:
Looking for feedback mainly around:
- naming (I called it "show full diff" and then the full diff, for now)
- order (where should we show it within the notification?)

feat(compareLink): generate a comparable link in MJ slack notification

---

keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/keel/bakery/artifact/BakeryLifecycleMonitor.kt
keel-bakery-plugin/src/test/kotlin/com/netflix/spinnaker/keel/bakery/artifact/BakeryLifecycleMonitorTests.kt
keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/LifecycleMonitorRepositoryTests.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/lifecycle/LifecycleMonitorRepository.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlLifecycleMonitorRepository.kt

We only want to fail for consecutive failures, it's ok if something fails intermittently.
Also, the status of something we failed to monitor should be unknown, not failed. failed is misleading.

fix(bake monitor): fail only for consecutive failures

---

keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/ApplicationEventTests.kt

this test failed on a pr but succeeded in a re-run. Bumping the timeout up a bit.

chore(test): increase timeout

---

keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/spring/SpringStartupTests.kt
keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/tx/DeliveryConfigTransactionTests.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/apidocs/ApiDocCompatibilityTests.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/apidocs/ApiDocTests.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/integration/AuthPropagationTests.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/integration/SchedulingResilienceTests.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/AdminControllerTests.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/ApplicationControllerTests.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/ApplicationEventTests.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/ArtifactControllerTests.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/DeliveryConfigControllerTests.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/ErrorSimulationControllerTests.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/EventControllerTests.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/ResourceControllerTests.kt

Unfortunately this doesn't work with uses of `@MockkBean` but generally I think this is preferable.

prefer constructor autowiring to use of lateinit var in Spring tests

---

keel-artifact/src/main/kotlin/com/netflix/spinnaker/keel/artifacts/ArtifactListener.kt
keel-artifact/src/test/kotlin/com/netflix/spinnaker/keel/artifacts/ArtifactListenerTests.kt
keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/keel/bakery/artifact/BakeryLifecycleMonitor.kt
keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/keel/bakery/artifact/ImageHandler.kt
keel-bakery-plugin/src/test/kotlin/com/netflix/spinnaker/keel/bakery/artifact/BakeryLifecycleMonitorTests.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/lifecycle/LifecycleEvent.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/lifecycle/LifecycleMonitorScheduler.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/lifecycle/LifecycleMonitorSchedulerTests.kt
keel-igor/src/main/kotlin/com/netflix/spinnaker/keel/igor/BuildLifecycleMonitor.kt
keel-igor/src/test/kotlin/com/netflix/spinnaker/keel/services/BuildLifecycleMonitorTests.kt

After adding a second type of event I realized that it is a lot easier to use if the event can indicate whether it kicks off monitoring. I added a `monitor: Boolean` field to indicate whether or not the event should kick off a monitoring cycle. Follow-up events need to set this to `false`. 
I also refactored the publishing event functions in each monitor so that it was easy to enforce setting `monitor = false`.
No change in behavior except that the first `build` event is now of status `RUNNING`.

feat(lifecycle): refactor start monitoring events

---

keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/keel/bakery/artifact/BakeryLifecycleMonitor.kt
keel-bakery-plugin/src/test/kotlin/com/netflix/spinnaker/keel/bakery/artifact/BakeryLifecycleMonitorTests.kt
keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/LifecycleEventRepositoryTests.kt

Fix for the bakery lifecycle monitor to not copy time forward.
Previously, this didn't matter, because we didn't care about the time an event added. But, when I updated that logic so the build monitor could actually pass in the correct timing I didn't realize it would cause the bakery monitor to continually pass forward the start time.

fix(lifecycle): don't copy time forward

---

keel-web/keel-web.gradle.kts

Re-enable the Swagger UI by adding a dependency to springfox.

docs(api): Re-enable Swagger UI

---

keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/verification/VerificationRepository.kt
keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/CombinedRepositoryTests.kt
keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/VerificationRepositoryTests.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/actuation/CheckScheduler.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/actuation/ScheduledResourceCheckStarting.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/CombinedRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/KeelRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/telemetry/TelemetryEvent.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/actuation/CheckSchedulerTests.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/verification/VerificationRunnerTests.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/config/SqlConfiguration.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlDeliveryConfigRepository.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlStorageContext.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlVerificationRepository.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/deliveryconfigs/deliveryconfigs.kt
keel-sql/src/main/resources/db/changelog/20201130-environment-last-verified.yml
keel-sql/src/main/resources/db/databaseChangeLog.yml
keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/SqlApproveOldVersionTests.kt
keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/SqlCombinedRepositoryTests.kt
keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/SqlDeliveryConfigRepositoryPeriodicallyCheckedTests.kt
keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/SqlVerificationRepositoryTests.kt

This adds a new `@Scheduled` function to `CheckScheduler` that invokes verifications for environment/artifact combinations using the current version deployed in the environment.

Scheduler for running verifications

---

keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/LifecycleEventRepositoryTests.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlLifecycleEventRepository.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlLifecycleMonitorRepository.kt

(1) correctly calculates build steps: I changed the requirement to have the first event be NOT_STARTED, then I forgot to actually make that true. This PR fixes that.
(2) changes duplicate events to update the timestamp instead of saving a new event. Why? Last week I had a bug in my code where we never stopped monitoring failed builds. We got a LOT of events saved about this. It seems useless. Really, I just want to know the last seen time for the status. So, I made the saving this way.
(3) I put a retry around grabbing the event uuid for the foreign key.

fix(builds): calculate steps more correctly

---

keel-sql/src/main/resources/db/changelog/20201208-fix-environment-last-verified-cascade.yml
keel-sql/src/main/resources/db/databaseChangeLog.yml

Missing cascade causes deletion of artifacts / environment elsewhere to fail.

add missing cascade to foreign keys on environment_last_verified table

---

keel-bakery-plugin/src/test/kotlin/com/netflix/spinnaker/keel/bakery/artifact/BakeryLifecycleMonitorTests.kt
keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/LifecycleMonitorRepositoryTests.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/lifecycle/LifecycleEventHandler.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/lifecycle/LifecycleEventRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/lifecycle/LifecycleMonitorRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/lifecycle/LifecycleMonitorScheduler.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/lifecycle/MonitoredTask.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/lifecycle/StartMonitoringEvent.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/lifecycle/LifecycleMonitorSchedulerTests.kt
keel-igor/src/test/kotlin/com/netflix/spinnaker/keel/services/BuildLifecycleMonitorTests.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlLifecycleEventRepository.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlLifecycleMonitorRepository.kt

**Problem**
We currently have two listeners for lifecycle events: one that saves the event (this is the "triggering event"), and one that saves the monitor instructions for that event. We're seeing some instances where the triggering event has not been saved when we try to monitor it. Because there is a foreign keys from the monitor table to the lifecycle event table, this causes problems. 
**Proposed solution**
I've changed the behavior slightly in this pr so that the lifecycle event is saved, and then a "start monitoring event" is published with that event's uid (which will be the foreign key in the monitoring table). This guarantees that the saving of the monitor event will happen only once the original event is saved. However, I've sort of 'leaked' the fact that we save the event with …

fix(lifecycle): start monitoring kicked off after saving event

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/exceptions/InvalidAppNameException.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/validators/DeliveryConfigValidator.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/validators/DeliveryConfigValidatorTests.kt

A user submitted a delivery config with some invalid resource names, including an invalid application name: `{{application.name}}`. 
This was submitted by an app that generates delivery configs via templating, and something went wrong with this case that broke template substitution.
The invalid resource names led to clouddriver returning errors when keel queried for these resources.
Reject delivery config as invalid if the application name is not a valid Spinnaker application name according to the Frigga library.
This won't completely solve the problem of a user submitting a delivery config with invalid resource names, but it will catch the problem where there's a common mode failure with generating the app name and the resource names, as there was in the original case here with …

fix(controller): reject delivery config with invalid app name

---

keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/LifecycleEventRepositoryTests.kt
keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/LifecycleMonitorRepositoryTests.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/config/SqlConfiguration.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlLifecycleEventRepository.kt
keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/SqlLifecycleEventRepositoryTests.kt
keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/SqlLifecycleMonitorRepositoryTests.kt

**Problem**
Because of my coding, we missed monitoring some events (fixed in https://github.com/spinnaker/keel/pull/1698).
**Solution**
This pr looks for single events with a non-ending status (like `NOT_STARTED` or `RUNNING`) that have asked to be monitored (`startMonitoring  == true`) and have a timestamp of more than 5 minutes ago. If found, it triggers monitoring again. This should pick out all the events we missed.
This is kicked off when a user loads the `managed/application/{application}?entities=artifacts` page. I'm going to slyly visit every app once this is rolled out so it triggers the monitoring w/o our users knowing.
Once this is done I'll watch for it to re-surface (indicating that we're missing monitoring of events for some other reason...). If it doesn't, I"ll remove this …

fix(builds): follow up on things we may have missed

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/lifecycle/LifecycleEventStatus.kt

Unknown is not a terminal status, it can be present at any point. Removing it from the terminal status list so that generated summaries do not get "stuck" in unknown state.

fix(bake): unknwon is not a terminal status

---

keel-web/src/test/kotlin/com/netflix/spinnaker/keel/apidocs/ApiDocCompatibilityTests.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/apidocs/ApiDocTests.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/ConvertExampleFilesTest.kt
keel-web/src/test/resources/application.properties
keel-web/src/test/resources/examples/titus-cluster-with-test-container.yml

This PR has two changes:
1. Add a test that parses delivery config with `verifyWith`
2. Use Spring framework to instantiate the beans necessary for configuring the Jackson deserialization
The motivation for 2 is to help us catch potential incorrect Spring configuration issues, by having the delivery-config-loading tests execute the same startup code as keel uses when it starts up on its own. The downside is that these tests will run a little slower.
I had to explicitly enable the ec2 and titus plugins in the application.properties used by the tests so that the ec2 and titus resource handlers and spec migrators would register the appropriate types with the Jackson object mapper.

chore(tests): add verifyWith parsing test, use spring for plumbing

---

keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/DeliveryConfigRepositoryTests.kt
keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/VerificationRepositoryTests.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlDeliveryConfigRepository.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/deliveryconfigs/deliveryconfigs.kt
keel-sql/src/main/resources/db/changelog/20201218-add-environment-verify-with.yml
keel-sql/src/main/resources/db/databaseChangeLog.yml
keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/SqlDeliveryConfigRepositoryTests.kt
keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/SqlVerificationRepositoryTests.kt

Managed to neglect this in previous PR. I had assumed there was a single JSON column that captured all of the Environment data.

Persist Environment.verifyWith property

---

keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/VerificationRepositoryTests.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlVerificationRepository.kt
keel-sql/src/main/resources/db/changelog/20201219-add-artifact-unique-index.yml
keel-sql/src/main/resources/db/databaseChangeLog.yml
keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/SqlVerificationRepositoryTests.kt

I incorrectly assumed that `name` / `type` was a unique index on `delivery_artifact` but it is not. I've changed the query to use `delivery_config_name` and `reference` instead. I also upgraded that index to a unique one as it was not before, but it should be.

fix sub-query that did not return a unique row

---

keel-sql/src/main/resources/db/changelog/20201220-fix-verification-state-columns.yml
keel-sql/src/main/resources/db/databaseChangeLog.yml

Dumb copy 'n paste error. The `artifact_version` column is not a ULID.

fix incorrect column type in verification_state

---

keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlVerificationRepository.kt
keel-sql/src/main/resources/db/changelog/20201221-shorten-environment-last-verified-pk.yml
keel-sql/src/main/resources/db/databaseChangeLog.yml

If the delivery config failed to load it would roll back the transaction and cause the verification loop to get stuck.

still update environment_last_verified if delivery config load fails

---

keel-titus-api/src/main/kotlin/com/netflix/spinnaker/keel/api/titus/TestContainerVerification.kt
keel-titus-plugin/keel-titus-plugin.gradle.kts
keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/titus/batch/ContainerJobConfig.kt
keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/titus/verification/TestContainerVerificationEvaluator.kt
keel-titus-plugin/src/test/kotlin/com/netflix/spinnaker/keel/titus/verification/TestContainerVerificationEvaluatorTests.kt

Our test suite fails because it runs using its own application rather than as part of keel.

allow specification of application for test container cluster

---

keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/Environment.kt
keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/DeliveryConfigRepositoryTests.kt
keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/VerificationRepositoryTests.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/core/api/SubmittedDeliveryConfig.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/serialization/SubmittedEnvironmentDeserializer.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/constraints/DependsOnConstraintEvaluatorWithVerificationsTests.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/verification/VerificationRunnerTests.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlDeliveryConfigRepository.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/deliveryconfigs/deliveryconfigs.kt

The delivery config supports specifying multiple verificiations. Here's a hypothetical example with two verifications, `test-container` and `wizbang`.
```
environments:
- name: staging
verifyWith:
- type: test-container
repository: acme/mytests
tag: stable
- type: wizbang
power: max
```
We expect that there will be scenarios where users will want the verifications to execute sequentially, in the order in which they are specified in the delivery config.
Currently, keel internally represents the collection of verifications as a set, so the ordering is lost.
Use a list instead of a set so the ordering in the delivery config is preserved.

feat(delivery-config): use list instead of set for verifications

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/core/api/EnvironmentSummary.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/ApplicationControllerTests.kt

Deck makes the following API call to populate the environments view:
```
/application/{application}?entities=resources&entities=artifacts&entities=environments
```
The above API call needs to expose information about the state of verifications in order for Deck to display information about the state of verifications in the environments view.
With this PR, each entry in the list of environments is augmented with information about which verifications are specified in the delivery config.
Here's an example (partial) response:
```json
"environments": [
{
"name": "staging",
"verifications": [
{
"type": "test-container",
"id": "test-container:acme/end-to-end-tests:stable"
}
]
}
]
```
In a future PR, the `artifacts` section of the API response will be augmented to show information about the …

feat(api): start to add verification info

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ResourceRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/services/ResourceStatusService.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/services/ResourceStatusServiceTests.kt

Back end for https://github.com/spinnaker/deck/pull/8836
Introducing a new status called "waiting" for when a resource was created and then has an resource check unresolvable status. This happens primarily (maybe only) to clusters when there is no approved image. I am updating the status so new customers don't immediately see an error.
I'll re-evaluate this in the future if it turns out that other resources w/o artifacts also hit this condition.

feat(status): add waiting status

---

keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/constraints/ConstraintStatus.kt
keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/plugins/VerificationEvaluator.kt
keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/verification/VerificationRepository.kt
keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/VerificationRepositoryTests.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/constraints/DependsOnConstraintEvaluator.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/telemetry/TelemetryEvent.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/verification/VerificationRunner.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/constraints/DependsOnConstraintEvaluatorTests.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/constraints/DependsOnConstraintEvaluatorWithVerificationsTests.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/verification/VerificationRunnerTests.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlVerificationRepository.kt
keel-sql/src/main/resources/db/changelog/20210111-update-verification-status-enum.yml
keel-sql/src/main/resources/db/databaseChangeLog.yml
keel-sql/src/main/resources/jooqConfig.xml
keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/titus/verification/TestContainerVerificationEvaluator.kt
keel-titus-plugin/src/test/kotlin/com/netflix/spinnaker/keel/titus/verification/TestContainerVerificationEvaluatorTests.kt

In the interests of keeping things small, I thought I'd break this work up. First step is to re-use the enum we already use for constraints. I'm contemplating renaming it but haven't decided to what yet.

use existing ConstraintStatus enum for verifications

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/services/ResourceStatusService.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/services/ResourceStatusServiceTests.kt

Ignore application-wide pausing events (especially when they predate the resource creation) when figuring out if a resource is waiting.

fix(waiting): account for pausing

---

keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ApplicationLoadBalancerHandler.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/ApplicationLoadBalancerHandlerTests.kt

This is an alternate implementation to #1736 where I'm not changing the ALB spec model, just amending how we pass the cert to Orca.

pass list of certificates to Orca rather than single certificateArn

---

keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/titus/EnvironmentVariablesResolver.kt
keel-titus-plugin/src/test/kotlin/com/netflix/spinnaker/keel/titus/EnvironmentVariablesResolverTests.kt

We now add a `SPINNAKER_ACCOUNT` env variable for titus (https://github.com/spinnaker/clouddriver/pull/5185/files). This PR introduces a resolver to add it to specs so that we don't diff forever on it.

fix(titus): add new env variable

---

keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/VerificationRepositoryTests.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlVerificationRepository.kt
keel-sql/src/main/resources/db/changelog/20210114-verification-state-task-list.yml
keel-sql/src/main/resources/db/databaseChangeLog.yml
keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/titus/verification/TestContainerVerificationEvaluator.kt
keel-titus-plugin/src/test/kotlin/com/netflix/spinnaker/keel/titus/verification/TestContainerVerificationEvaluatorTests.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/VerificationController.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/VerificationControllerTests.kt

- support persistence of multiple task ids in verification state metadata

Allow users to retry verification tasks

---

keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/keel/bakery/constraint/ImageExistsConstraintEvaluator.kt
keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/keel/bakery/telemetry/BakeryTelemetryListener.kt

We saw a period of time where this was occurring much more frequently than expected. Adding a counter so that we can alert off this.

chore(ops): add missing image regions counter

---

keel-orca/src/test/kotlin/com/netflix/spinnaker/keel/orca/ClusterDeployStrategyTests.kt
keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/titus/TitusClusterHandler.kt

We were passing `"Amazon"` instead of `"Titus"` for `interestingHealthProviderNames` in the Titus deploy stage. This fixes that and adds a small test.

fix(titus): Fix interestingHealthProviderNames in deploy stage

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/verification/VerificationRunner.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/verification/VerificationRunnerTests.kt

#1740 allowed users to request a verification be retried but they did not actually run again.

re-run verifications if user requests

---

keel-artifact/src/main/kotlin/com/netflix/spinnaker/keel/artifacts/DockerArtifactSupplier.kt

We're occasionally getting "stuck" instances where all 64 threads in the DefaultDispatcher-worker pool are blocked waiting. 
The `DockerArtifactSupplier.getLatestArtifact` method has a `runWithIoContext` block that calls `findArtifactVersions`, which itself has another `runWithIoContext` block where it makes a call to the `CloudDriverService.findDockerImages` suspend function.
I believe the problem occurs when the coroutines/threads get scheduled a certain way:
1. The `ArtifactListener.syncArtifactVersions` scheduled method fires, running on one of the threads in the worker thread pool.
2. This method retrieves *N* Docker artifacts from the repository, where N>64 (64 being the size of the worker thread pool) .
3. This method launches a new coroutine for each artifact, which calls …

fix(artifacts): Don't nest runWithIoContext

---

keel-ec2-api/src/main/kotlin/com/netflix/spinnaker/keel/api/ec2/SecurityGroupRule.kt

In #1739, I added a `description` property to `SecurityGroupRule`, which was needed to identify security groups reported by CloudDriver associated with a Netflix IP Object in the internal implementation. However, it looks like several of our applications had managed security group rules that were managed by Keel (probably migrated apps), but because there's no such property in the corresponding delivery configs, we could never resolve the delta and kept trying indefinitely.
The fix in this PR is to ignore that property when diffing. I've also moved the property out of the base abstract class and into the `CidrRule` sub-class, which is the only one we care about in the internal implementation.
I've tested this change against the following delivery config and Keel behaves as expected: …

fix(diff): Ignore CidrRule description when diffing

---

keel-ec2-api/src/main/kotlin/com/netflix/spinnaker/keel/api/ec2/SecurityGroupRule.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/api/ec2/SecurityGroupDiffTests.kt

It turns out that the [diff library](https://github.com/SQiShER/java-object-diff/) we use looks at object equality when determining changes in collections, so even though the `description` property of `CidrRule` was being excluded from the comparison, the entire object was considered different in the collection when there was a difference in the value of that property, due to the default implementation of `equals()` by data classes, which compares all fields.
This explains why we saw this kind of diff, where all the properties appear removed/added with the exact same values:
I opened an issue for the library here: https://github.com/SQiShER/java-object-diff/issues/216. In the meantime, the workaround is to override `hashCode()` and `equals()` in `CidrRule` to also ignore the `description` …

fix(diff): Workaround for diff library's handling of SecurityGroup.inboundRules

---

keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/config/EC2Config.kt

Complement to #1739. Annotates the `SecurityGroupHandler` with `@ConditionalOnMissingBean` so that we can register the Netflix implementation in its place.

feat(ec2): Make SecurityGroupHandler conditional on missing bean

---

build.gradle.kts
keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/CloudDriverCache.kt
keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/CloudDriverService.kt
keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/MemoryCloudDriverCache.kt
keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/model/Certificate.kt
keel-clouddriver/src/test/kotlin/com/netflix/spinnaker/keel/clouddriver/MemoryCloudDriverCacheTest.kt
keel-core/keel-core.gradle.kts
keel-ec2-api/src/main/kotlin/com/netflix/spinnaker/keel/api/ec2/ApplicationLoadBalancerSpec.kt
keel-ec2-api/src/main/kotlin/com/netflix/spinnaker/keel/api/ec2/ec2.kt
keel-ec2-api/src/main/kotlin/com/netflix/spinnaker/keel/api/ec2/old/ApplicationLoadBalancerV1Spec.kt
keel-ec2-api/src/main/kotlin/com/netflix/spinnaker/keel/api/ec2/old/ApplicationLoadBalancerV1_1Spec.kt
keel-ec2-plugin/keel-ec2-plugin.gradle.kts
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/jackson/KeelEc2ApiModule.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/migrators/ApplicationLoadBalancerV1_1ToV1_2Migrator.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resolvers/ApplicationLoadBalancerDefaultsResolver.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resolvers/NetworkResolver.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ApplicationLoadBalancerHandler.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resolvers/NetworkResolverTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/ApplicationLoadBalancerHandlerTests.kt
keel-orca/keel-orca.gradle.kts
keel-titus-plugin/keel-titus-plugin.gradle.kts
keel-web/src/test/resources/examples/alb-example.yml

Instead of requiring users to specify the certificate ARN, we can resolve that from Clouddriver so users can reference the cert by name. This PR adds a new ALB spec version.

reference certificate by name in ALB spec

---

keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/CloudDriverService.kt
keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/MemoryCloudDriverCache.kt
keel-clouddriver/src/test/kotlin/com/netflix/spinnaker/keel/clouddriver/MemoryCloudDriverCacheTest.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/caffeine/CacheFactory.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/integration/AuthPropagationTests.kt

Some CloudDriver endpoints return all data at once, rather than a specific item. This PR updates our CloudDriver caches to take that into account. This should result in more efficient cache utilization as we won't keep making the same CloudDriver call the first time each key is hit -- we'll make the call just once for the first key.

use bulk caches where appropriate

---

keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/LifecycleEventRepositoryTests.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlLifecycleEventRepository.kt

@luispollo recently discovered that if you're exicitedly waiting for a build or bake to show up, and you click the button too fast, the link is broken. This happens because the first event we receive usually has a "link" that is malformed. the individual monitors know how to translate that into a clickable link (it's designed like this so that we don't have to inject the base spinnaker URL everywhere). This PR updates our logic so that if we end up having one of these incomplete links we don't show it to the user.

fix(lifecycle): only show event if it has a valid link

---

keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlDeliveryConfigRepository.kt
keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/MigratorErrorTests.kt

Prior to this change any exception thrown trying to load delivery configs from the database as part of the `DeliveyrConfigRepository.itemsDueForCheck` method would roll back the timestamp update to indicate when that delivery config was last checked. That would mean we'd get stuck trying to read the same one over and over. Specifically the issue was observed due to a failing `SpecMigrator` which is what the test in this PR simulates.

Fix stuck promotion checks

---

keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/ApplicationController.kt

We use "mark as bad" in the UI for the concept of vetoing an artifact. I've noticed that it's continually hard to identify the right endpoint to use. I created a "../mark/bad" endpoint to help fix this.
Also, the "un-veto" or "mark as good" endpoint currently breaks when artifact references have a slash in them. I've created a "../mark/good" endpoint with the same semantics as the "../mark/bad" endpoint to get around this (I already tried messing with the retrofit and spring configuration to allow slashes, but I couldn't get it to work). I feel like it's not technically correct REST semantic wise (we are 'deleting' a veto), but it seems reasonable and consistent with how we talk about what we are doing.

chore(veto): new endpoints for marking bad/good

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/constraints/AllowedTimesConstraintEvaluator.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/core/api/ArtifactSummary.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/core/api/TimeWindowConstraint.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/services/ApplicationService.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/constraints/AllowedTimesConstraintEvaluatorTests.kt

We need a consistent representation of the allowed-times constraint (that doesn't rely on words) to power UI visualization of it. 
Before:
```
{
"type": "allowed-times",
"currentlyPassing": false,
"attributes": {
"windows": [
{
"days": "Monday-Friday",
"hours": "9-16"
}
]
}
```
After:
```{
"type": "allowed-times",
"currentlyPassing": true,
"attributes": {
"windows": [
{
"days": [
1,
2,
3,
4,
5
],
"hours": [
9,
10,
11,
12,
13,
14,
15,
16
]
}
]
}
}```

chore(allowed-times): consistent numeric representation

---

keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/CloudDriverCache.kt
keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/MemoryCloudDriverCache.kt
keel-clouddriver/src/test/kotlin/com/netflix/spinnaker/keel/clouddriver/MemoryCloudDriverCacheTest.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/caffeine/CacheLoadingException.kt
keel-lemur/src/main/kotlin/com/netflix/spinnaker/config/LemurConfiguration.kt
keel-lemur/src/main/kotlin/com/netflix/spinnaker/keel/lemur/LemurCertificateResolver.kt
keel-lemur/src/test/kotlin/com/netflix/spinnaker/keel/lemur/LemurCertificateResolverTests.kt
keel-retrofit/src/main/kotlin/com/netflix/spinnaker/keel/retrofit/Exceptions.kt

Just wraps a cache around the calls to Lemur added in #1767

use a cache to reduce repetitive Lemur calls

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/services/ApplicationService.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/api/ec2/export/ClusterExportTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/ApplicationLoadBalancerHandlerTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClassicLoadBalancerHandlerTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandlerTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/OrcaTaskLauncherTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/SecurityGroupHandlerTests.kt
keel-orca/src/main/kotlin/com/netflix/spinnaker/keel/model/OrcaNotification.kt
keel-orca/src/main/kotlin/com/netflix/spinnaker/keel/orca/OrcaTaskLauncher.kt
keel-slack/src/main/kotlin/com/netflix/spinnaker/keel/slack/NotificationEventListener.kt
keel-titus-plugin/src/test/kotlin/com/netflix/spinnaker/keel/titus/resource/TitusClusterExportTests.kt
keel-titus-plugin/src/test/kotlin/com/netflix/spinnaker/keel/titus/resource/TitusClusterHandlerTests.kt

1. fixed broken links and empty usernames.
2. wrapping orca notifications with a fast property, so we can finish working on + testing out the new integration and then remove it completely. The missing piece in the puzzle is interactive notifications (aka manual judgments).

fix(slack): small bug fixes + first step in deprecating notifications coming from orca

---

.github/workflows/periodic_release.yml

Adds a new GitHub Action triggered on a cron schedule to create a weekly release, so that OSS users can pull in the latest changes as a dependency during installation.
I couldn't think of a way to test this locally. If you have any ideas, please let me know.
Cc: @nimakaviani

chore(release): Setup weekly releases for the benefit of OSS users

---

.github/workflows/periodic_release.yml

Turns out you don't need to write the version to the file as a workaround, the action can determine it from tags.

fix(release): Fix weekly release

---

build.gradle.kts
gradle.properties
keel-sql/src/test/resources/testcontainers.properties

Upgrades `testcontainers` to 1.15.1 to fix the following error in the builds:
```
com.github.dockerjava.api.exception.NotFoundException: Status 404: {"message":"No such image: testcontainers/ryuk:0.3.0"}
at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:241)
```

fix(test): Bump testcontainers version

---

keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/keel/bakery/artifact/ImageHandler.kt
keel-bakery-plugin/src/test/kotlin/com/netflix/spinnaker/keel/bakery/artifact/ImageHandlerTests.kt

We've been getting alerts for `NoKnownArtifactVersions` exceptions bubbling up all the way to the root exception handler from `ImageHandler`. This PR modifies the behavior to handle the exception gracefully by logging it and returning early.

fix(baking): Handle no versions gracefully in ImageHandler

---

keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/CombinedRepositoryTests.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/KeelRepository.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlResourceRepository.kt

**Problem**
We're consistently seeing resources being created when upserting a delivery config and the matching `ResourceCreated` events failing to persist. There's a race condition between those two flows because the first runs a transaction to persist all the records associated with the delivery config, while the second is triggered asynchronously and attempts to read the UID of the resource to create the event record.
**Proposed solution**
This PR replaces the asynchronous events published in `CombinedRepository.upsertResource` (which is only used in this particular code path) with repository calls to persist the event records as part of the transaction in `CombinedRepository.upsertDeliveryConfig`.
**Other alternatives considered**
I've considered:
* Doubling the number of read retries …

fix(events): Fix race condition persisting resource events

---

keel-clouddriver/src/test/kotlin/com/netflix/spinnaker/keel/clouddriver/MemoryCloudDriverCacheTest.kt

Some tests are failing intermittently when run in GitHub Actions, which blocks PR merges.
Attempts to diagnose the issue so far have been unsuccessful.
Mark these tests as disabled for now so that they don't block development.

chore(tests): disable flaky cert cache tests

---

keel-clouddriver/src/test/kotlin/com/netflix/spinnaker/keel/clouddriver/MemoryCloudDriverCacheTest.kt

Temporarily run flaky tests 1000 times with additional pause to see if that is sufficient to correct the race condition.

try to eliminate flakiness in cache tests

---

keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/verification/VerificationRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/core/api/ArtifactSummary.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/services/ApplicationService.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/services/ApplicationServiceTests.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/services/ComparableLinksTests.kt

Provide the UI with information about the state of verifications for artifact versions in each environment. (For example, what verifications have been run against keel-0.850.0-h1020.a525f99 in the prestaging environment)?
Note: follow-up to PR #1777. Much of the description is copied from there.
In the `/application/{application}` endpoint (called by deck in the environments view), add additional fields to artifact version objects which encode verification summary notification.
In *jq* notation, these verification summaries are found in: `artifacts[].versions[].environments[].verifications`.
For the `fnord` app, the API call would be:
http://gate/managed/application/fnord?entities=resources&entities=artifacts&entities=environments
The  output would looke like this:
```json
{
"artifacts": …
```

feat(api): show verifications in api

---

keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/CloudDriverService.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/api/plugins/BaseClusterHandler.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/api/plugins/CurrentImages.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/telemetry/TelemetryEvent.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/verification/ImageFinder.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/verification/VerificationRunner.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/verification/VerificationRunnerTests.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/ImageTagger.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandler.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/ImageTaggerTests.kt
keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/titus/TitusClusterHandler.kt

This pr supports an experiment: a hook point that allows managed delivery to hand off to pipelines. 
Right before a verification starts the verification runner finds all the images that are currently in an environment. This is done by calling the cluster handlers (we ignore other resources) and getting the image that's running in that cluster (using the `current` function). We save that in the verification metadata.
If the verification passes, we dig into that metadata and issue a "tag image" job for each ami.
This is meant to be a quick and dirty experiment to allow our partners (danny) to test out some new templates. If it turns out that handing off between md and pipelines is useful, I might implement v2 of this in a different way.

feat(ec2): tag image after verification

---

keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/DeliveryConfigRepositoryTests.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/CombinedRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/DeliveryConfigRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/KeelRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/services/ApplicationService.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/services/ApplicationServiceTests.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlDeliveryConfigRepository.kt

When someone vetos an artifact or pins an artifact (or deletes either of those) we want to make sure that we reflect this really quickly. It's a bad experience to have to wait a minute for that change to get picked up. This PR triggers a recheck of all the environments in a config every time one of those things happens. This means that the desired version for each resource gets reflected more quickly. 
My goal is to make the mark-as-bad -> rollback action happen as quickly as possible so the UI feels more responsive.

chore(veto/pin): reflect new desired artifact more quickly

---

keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/VerificationRepositoryTests.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlArtifactRepository.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlVerificationRepository.kt

This fixes two bugs in the API used by the environments view that displays verifications data.
Two separate cases weren't being handled properly
* when the artifact reference does not match artifact name
* when the list of verification contexts is empty in the `getStatesBatch` call.
When querying the artifact repository for a list of published artifact versions, we now add the artifact references by copying each element of the list. 
This isn't the most efficient way of doing this, but code-wise it was the smallest change.
Kotlin's `reduce` throws an exception if you give it an empty list. Change to using `reduceOrNull` and then do null handling.
Note: You'll want to hide whitespace when looking at the diff.

fix(api): verification summary issues

---

keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/Resource.kt
keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/CombinedRepositoryTests.kt
keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/DeliveryConfigRepositoryTests.kt
keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ResourceRepositoryTests.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/actuation/ResourceActuator.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/events/ResourceEvent.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/CombinedRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/KeelRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ResourceRepository.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/telemetry/TelemetryListenerTests.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlResourceRepository.kt
keel-sql/src/main/resources/db/changelog/20210208-versioned-resources.yml
keel-sql/src/main/resources/db/databaseChangeLog.yml
keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/SqlResourceRepositoryPeriodicallyCheckedTests.kt
keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/SqlResourceRepositoryTests.kt
keel-test/src/main/kotlin/com/netflix/spinnaker/keel/test/Resources.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/DeliveryConfigControllerTests.kt

The aim of this PR is to start the implementation of versioned environments by making resources versioned.
* Each resource `id` may have 1..n versions
* The combination of `id` and `version` is unique
* Each version has a unique `uid`
* The resource with the highest `version` for a given `id` is the newest
* For now we will always deal with the newest version, but in future an environment version will reference particular resource versions
To-do

Versioned resources

---

keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/verification/VerificationRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/services/ApplicationService.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/telemetry/TelemetryEvent.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/telemetry/TelemetryListener.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/VerificationController.kt

Environments view was blowing up for a test app in our staging environment because the `verification_state` table had an invalid verification id in one of the entries.
The invalid data looked like this: `spkr/mytest/stable` where the valid id was `spkr/mytest:stable`.
We had changed the convention for the id a while back from `/` to `:` for delimiting the tag of the container, but there was some data that hadn't been updated.
While this could have been fixed by just repairing the data in the database, having the environments view break entirely because of one invalid verificiations record is an undesirable user experience.
Explicitly detect and handle invalid verification ids.
The `VerificationContext.verification(id: String)` function now returns a null if the id doesn't exist, which …

feat(verif): more robust handling of invalid verification id

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/telemetry/TelemetryListener.kt

While we were creating spectator counters for verification metrics, we weren't actually incrementing them, so no metrics were reported.
Increment the danged counters.

fix(metrics): add missing increments

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/artifacts/ArtifactVersionLinks.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/services/ComparableLinksTests.kt

git commit links show the diff in the UI. The PR creates a pass through
for git commitLink so we dont need to generate a compareLink for it.

feat(CiBuild): add support for git commits

---

keel-bakery-plugin/src/test/kotlin/com/netflix/spinnaker/keel/bakery/artifact/BakeryLifecycleMonitorTests.kt

When tests fail on GitHub Actions, I search for the string `" failed"` to jump to the failing test lines.
When I do that, the first search hit is a successful test that has the string `"failed"` in its description.
```
BakeryLifecycleMonitorTests publishes failed event and marks failure PASSED
```
Change the test description text from `failed` to `fail(ed)` so it doesn't match a `failed` string search.

chore(test): rename test label so 'failed' doesn't appear

---

keel-slack/src/main/kotlin/com/netflix/spinnaker/keel/slack/NotificationEventListener.kt
keel-slack/src/main/kotlin/com/netflix/spinnaker/keel/slack/handlers/GitDataGenerator.kt
keel-slack/src/main/kotlin/com/netflix/spinnaker/keel/slack/handlers/ManualJudgmentNotificationHandler.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/SlackAppController.kt

This PR is fixing errors coming from slack when the user is clicking on an unactionable button, like "More":
Prior to this fix, only actionable buttons followed a convention for `actionId` (which is the button identifier), and all other buttons didn't. 
For example, when the user clicks on `approve` within the `manual_judgement` notification, the action id is set to be "{constraintId}:PASS:MANUAL_JUDGMENT". Then we parse it and act as needed.
This fix will add the right string pattern for action id (like "button:url:diff") for each button, so that keel can `ack` all action buttons and we won't show errors.

fix(slack): fixing unactionable buttons errors

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ArtifactRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/CombinedRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/KeelRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/services/ApplicationService.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/services/ApplicationServiceTests.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/services/ComparableLinksTests.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlArtifactRepository.kt

This pr batch loads artifact evironment version data which was previously loaded by doing 3 SQL queries per artifact version requested. So, if we have 1 artifact in one environment and we load 30 versions for the environments UI, this takes 30*3 = 90 SQL queries and reduces it to 3.
I could further optimize this API by bulk loading constraints data (we are also making 1 SQL query per version and environment also) but I decided not to do that in this PR.
I also created a context object for the data loaded (like Luis had previously suggested) because I was adding even more data to each function.

fix(api): remove 3 sql queries per artifact version

---

keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/Resource.kt
keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/CombinedRepositoryTests.kt
keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/DeliveryConfigRepositoryTests.kt
keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ResourceRepositoryTests.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/actuation/ResourceActuator.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/events/ResourceEvent.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/jackson/mixins/ResourceMixin.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/CombinedRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/KeelRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ResourceRepository.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/telemetry/TelemetryListenerTests.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlDeliveryConfigRepository.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlResourceRepository.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlUnhappyVetoRepository.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlUnhealthyRepository.kt
keel-sql/src/main/resources/db/changelog/20210208-versioned-resources.yml
keel-sql/src/main/resources/db/databaseChangeLog.yml
keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/SqlDeliveryConfigRepositoryPeriodicallyCheckedTests.kt
keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/SqlNotificationRepositoryTests.kt
keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/SqlResourceRepositoryPeriodicallyCheckedTests.kt
keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/SqlResourceRepositoryTests.kt
keel-test/src/main/kotlin/com/netflix/spinnaker/keel/test/Resources.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/DeliveryConfigControllerTests.kt

One of the crucial things I was missing was that version a) needed to be ignored by JSON serialization and b) would not be present when updating resources in any un-modified resources. I'm going to add some test coverage around multiple resource versions being present and then this can go back in.

versioned resources with some fixes

---

keel-slack/src/main/kotlin/com/netflix/spinnaker/keel/slack/NotificationEventListener.kt
keel-slack/src/main/kotlin/com/netflix/spinnaker/keel/slack/SlackNotificationEvent.kt
keel-slack/src/main/kotlin/com/netflix/spinnaker/keel/slack/handlers/GitDataGenerator.kt
keel-slack/src/main/kotlin/com/netflix/spinnaker/keel/slack/handlers/ManualJudgmentNotificationHandler.kt

This PR will add a warning to the manual judgment notification, in case there's a pinned version in the environment.
(As a reminder, if there's a pinned version, even if the user will click on `approve`, nothing will happen).
It will look like this:

feat(slack): add a warning if there's a pinned version

---

keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/DeliveryConfigRepositoryTests.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlDeliveryConfigRepository.kt

Deleting a delivery config would leave behind non-current versions of resources

Fix orphaned old resource versions

---

keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/actuation/TaskLauncher.kt
keel-orca/src/main/kotlin/com/netflix/spinnaker/keel/model/OrchestrationRequest.kt
keel-orca/src/main/kotlin/com/netflix/spinnaker/keel/orca/OrcaTaskLauncher.kt
keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/titus/verification/TestContainerVerificationEvaluator.kt

Orca allows you to pass a correlation id when launching a task, which (I believe) is designed to support idempotently launching tasks.
Specifically, if you try to launch a task twice with the same correlation ID, orca will check to see if there is already a (not yet completed) task with the same correlation id. If so, orca will just hand back the execution ULID of the first task instead of launching a new one.
Keel uses a correlation id when launching the orca task associated with executing a verification, looks like this:
```kotlin
correlationId = "${supportedVerification.first}:${context.deliveryConfig.application}.${context.environmentName}"
```
If a new deployment into an environment happens while a verification is
still running, when keel goes to launch a new verification, it will …

fix(verif): don't set correlation id in orca task

---

keel-front50/src/main/kotlin/com/netflix/spinnaker/keel/front50/Front50Service.kt
keel-front50/src/main/kotlin/com/netflix/spinnaker/keel/front50/model/Application.kt

Enablement work for an internal PR to report on Managed Delivery onboarding, which leverages metadata persisted in Front50.

feat(reports): Add Front50 API to retrieve all apps + fields in Application model

---

keel-clouddriver/src/test/kotlin/com/netflix/spinnaker/keel/clouddriver/MemoryCloudDriverCacheTest.kt
keel-titus-api/src/main/kotlin/com/netflix/spinnaker/keel/api/titus/TestContainerVerification.kt
keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/titus/batch/ContainerJobConfig.kt
keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/titus/verification/TestContainerVerificationEvaluator.kt
keel-titus-plugin/src/test/kotlin/com/netflix/spinnaker/keel/titus/verification/TestContainerVerificationEvaluatorTests.kt

Currently, the container image specified in a `verifyWith` section is identified by "repository" and "tag" fields, for example:
```
verifyWith:
- type: test-container
repository: acme/mytests
tag: stable
...
```
However, `repository`, while used by the spinnaker UI, isn't standard industry terminology. Instead, people generally use the term "image". In addition, the common convention for dealing with tags is to append them to the end of the image name.
Enable users to specify the image name and tag using a field named `image`.
```
verifyWith:
- type: test-container
image: acme/mytests:stable
```
Note: to avoid breaking existing apps, this PR supports both the new and old syntaxes.  However, the older syntax should be considered deprecated, and we are going to remove it once we track down …

feat(verif): in delivery config, use "image" instead of "repository/tag"

---

keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/SecurityGroupHandler.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/SecurityGroupOverrideTests.kt

Merges `inboundRules` from region overrides with the common `inboundRules` rather than replacing them.

merge override inbound rules instead of replacing

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/services/ApplicationService.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/services/ApplicationServiceTests.kt

We hit an issue (documented as as #1821) where the batch verification query was throwing an exception, which broke the view.
Degrade gracefully by catching the exception, logging the error, and continuing on as if there is no verification info to display.
This ensures that the UI remains functional even if that particular query breaks.

fix(api): don't blow up the api if can't query for verifications

---

keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ResourceRepositoryTests.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlResourceRepository.kt

This reverts commit 17dad4a103ba2c3dbe5b338dad13f96287506f6a.

Revert "fix(events): resource history should include events for all versions (#1823)"

---

keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/DeliveryConfigRepositoryTests.kt
keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ResourceRepositoryTests.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/actuation/EnvironmentPromotionChecker.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/CombinedRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/KeelRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ResourceRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/services/ApplicationService.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/actuation/EnvironmentPromotionCheckerTests.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/services/ApplicationServiceTests.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlResourceRepository.kt

We've gotten some user reports of things feeling slow and not responsive. We've also gotten reports like "what are you waiting for??". This pr hopes to make deployment happen much faster after a new version is "approved" for an environment (pin, unpin, mark as bad, and also new versions).
This pr introduces a "recheck resources in an environment" function that clears the "last checked" time for all resources in an environment. This makes them immediately due for check. My hope is this will mean we spend almost 0 seconds in the "approved" state. (unless your application is paused, which means that versions will stay in the approved state until you un pause).
Hopefully this is a big performance-feel win for a minimal amount of effort.

chore(perf): speed up resource checking after new version is approved

---

keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/VerificationController.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/VerificationControllerTests.kt

I have also done this, accidentally. And it is no bueno. If the URL value might have a slash it needs to go into the request body.

fix(verification): you can't have a path variable with a slash

---

keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/DeliveryConfigRepositoryTests.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/core/api/ApplicationSummary.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlDeliveryConfigRepository.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/deliveryconfigs/deliveryconfigs.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/AdminControllerTests.kt

Adds the following fields to `ApplicationSummary`, in support of reporting internally at Netflix:
- `createdAt`: the `Instant` at which the corresponding `DeliveryConfig` was created. This field is derived from `delivery_config.uid` (which is a ULID).
- `resourceCount`: count of resources in the `DeliveryConfig` at the time of querying.

feat(reports): Add fields to ApplicationSummary in support of reporting

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/events/ApplicationEvent.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/events/PersistentEvent.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/events/ResourceEvent.kt

The goal is to remove the allow-list from the frontend, and allow backend changes without the need to update the frontend.
https://github.com/spinnaker/deck/blob/5a9768bc6db2f527a73d6b1f5fb3120c101e094b/app/scripts/modules/core/src/managed/resourceHistory/ManagedResourceHistoryModal.tsx#L34

feat(api): add displayName and level to events history

---

keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/keel/bakery/artifact/ImageHandler.kt
keel-bakery-plugin/src/test/kotlin/com/netflix/spinnaker/keel/bakery/artifact/ImageHandlerTests.kt

Include the version in the correlation id we send to orca so we can bake two different versions at once. This fixes the annoying situation where you push two versions in quick succession but we bake them serially instead of in parallel.

fix(bake): use artifact version in correlation id

---

keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/VerificationRepositoryTests.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlVerificationRepository.kt

If a delivery config contains an artifact reference and environment that both happen to have the same name (e.g., an artifact reference named `"dev"` and an environment named `"dev"`), then the [`SqlVerificationRepository.getStatesBatch`][1] method throws a SQLSyntaxErrorException.
For details, see #1821
Add field aliases to prevent the name collision.
[1]: https://github.com/spinnaker/keel/blob/d87062779779c383685a2f495c1ce2dc719dbf6f/keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlVerificationRepository.kt#L183-L241

fix(db): handle verif query when artifact ref and env name are the same

---

keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ResourceRepositoryTests.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlDeliveryConfigRepository.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlResourceRepository.kt
keel-sql/src/main/resources/db/changelog/20210226-generate-event-columns.yml
keel-sql/src/main/resources/db/databaseChangeLog.yml
keel-sql/src/main/resources/jooqConfig.xml

Because of the poor performance of the initial attempt at this functionality, this PR includes revisions to the way the `event` table is structured. The most important is that `event.ref` will now be the `id` of a resource for rows where `scope = 'RESOURCE'`. In addition I re-ordered the columns for better indexing performance, and now derive the `ref`, `application`, and `timestamp` columns from `json` rather than requiring us to explicitly insert data. For now these are implemented as duplicate columns but I'll follow up with another PR to remove the old ones once this change is live.

Ensure events for all version of a resource are included in history

---

keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/jackson/DefaultSecurityGroupRuleDeserializer.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/SecurityGroupHandler.kt

Problem: we want to customize the behavior of `SecurityGroupHandler.export` in Netflix's internal implementation to support IP Objects, but there's not a currently good place to hook in to the default implementation to achieve that.
This PR extracts part of the logic in the `export` method into a new `protected` method that can be overridden by sub-classes to transform the `SecurityGroup` objects as needed before the default implementation calculates the default and override properties of the `SecurityGroupSpec`.
The only behavior changes in this PR are:
1. Simplification of how to select the `SecurityGroupRuleDeserializer` bean.
2. Export now picks the security group with the fewest inbound rules as the "base" for the properties at the top-level of the spec, to account for how we merge …

refactor(export): Refactor security group export to facilitate customization by sub-classes

---

build.gradle.kts
gradle.properties
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandler.kt
keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/tx/DeliveryConfigTransactionTests.kt

Bumps kork to pick up https://github.com/spinnaker/kork/pull/850 and aligns Kotlin version in keel.

chore(deps): Bump kork and Kotlin

---

keel-sql/src/main/kotlin/com/netflix/spinnaker/config/SqlConfiguration.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlVerificationRepository.kt
keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/SqlApproveOldVersionTests.kt
keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/SqlCombinedRepositoryTests.kt
keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/SqlVerificationRepositoryTests.kt

Use a locking read to eliminate a race condition in a database transaction related to checking verifications.
We've seen cases where two nodes check the same environments for verification within about the same second, even though verification checks are only supposed to have for an environment once a minute.
Here's an example of timestamps from two keel instances checking the same environments:
```
02/23/2021 12:46:35.613 -0800
02/23/2021 12:46:35.869 -0800
```
I belive the problem is related to the database consistency level used in the [SqlVerificationRepository.nextEnvironmentsForVerification][1] check. This is a databasde anomaly known as *phantom reads*.
See #1832 for details.
This PR adds a [`LOCK IN SHARE MODE`][2] directive to the relevant select statement to ensure that phantom …

fix(db): add read lock to avoid phantom read

---

keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/verification/VerificationRepository.kt
keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/VerificationRepositoryTests.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/constraints/PendingVerificationsConstraintEvaluator.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/core/api/PendingVerificationsConstraint.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/verification/VerificationRunner.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/constraints/PendingVerificationsConstraintEvaluatorTests.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/verification/VerificationRunnerTests.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlVerificationRepository.kt

If a previous deployment has verifications still running, this PR makes it so that promotion of a new version will be delayed.
Relevant to #1831

Delay promotion if verifications are still running

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/actuation/CheckScheduler.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/actuation/ResourceActuator.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/logging/TracingSupport.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/verification/VerificationRunner.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/ExportController.kt

Follow-up to #1841. Following the discussion and recommendations in https://github.com/Kotlin/kotlinx.coroutines/issues/985, this PR adds an empty `MDCContext` to all top-level coroutine scopes where `withTracingContext` is used, in an attempt to remove left-over `X-SPINNAKER-RESOURCE-ID`s when switching threads.
Hopefully fixes #1122.

fix(tracing): Ensure clean MDC context at top coroutine scopes

---

keel-bakery-plugin/keel-bakery-plugin.gradle.kts
keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/keel/bakery/BaseImageCache.kt
keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/keel/bakery/DefaultBaseImageCache.kt
keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/keel/bakery/UnknownBaseImage.kt
keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/keel/bakery/artifact/BakeStage.kt
keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/keel/bakery/artifact/BakeryLifecycleMonitor.kt
keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/keel/bakery/constraint/ImageExistsConstraintEvaluator.kt
keel-bakery-plugin/src/test/kotlin/com/netflix/spinnaker/keel/bakery/artifact/BakeryLifecycleMonitorTests.kt
keel-bakery-plugin/src/test/kotlin/com/netflix/spinnaker/keel/bakery/constraint/ImageExistsConstraintEvaluatorTests.kt
keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/ImageService.kt
keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/BakedImageRepositoryTests.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/artifacts/BakedImage.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/BakedImageRepository.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/NoImageFound.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resolvers/ImageResolver.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resolvers/ImageResolverTests.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/config/SqlConfiguration.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlBakedImageRepository.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlLifecycleEventRepository.kt
keel-sql/src/main/resources/db/changelog/202010303-baked-images.yml
keel-sql/src/main/resources/db/databaseChangeLog.yml
keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/SqlBakedImageRepositoryTests.kt

*Summary*
Currently, there is a delay between baking and deploying because we wait for the baked image to appear in the clouddriver cache (this is where we get all our data about what exists in the world). Bake and deploy pipelines don't have this delay because the deploy stage grabs the ami id from the bake stage.
In order to bring this lightning fast speed to keel, we need to store the ami information from the bake task we launch in order to use it right away. This allows us to deploy before the ami is seen in clouddriver's cache.
*Background knowledge*
We have an implicit constraint `ImageExistsConstraint` that prevents a debian artifact version from being approved in an environment before an image exists for that version. This is the thing that ultimately makes the delay. I modified …

fix(perf): eliminate caching delay between bake and deploy

---

keel-sql/src/main/resources/db/changelog/20210305-embiggen-reason-column.yml
keel-sql/src/main/resources/db/databaseChangeLog.yml

Deck allows any length of comment and users get an error if they enter more than 255 characters.

veto comment can be longer than 255 characters

---

keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlDeliveryConfigRepository.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlResourceRepository.kt
keel-sql/src/main/resources/db/changelog/20210302-drop-old-event-columns.yml
keel-sql/src/main/resources/db/databaseChangeLog.yml

Cleans up duplicate columns left by #1828 to enable us to roll back.

clean up duplicate columns on event table

---

keel-slack/src/main/kotlin/com/netflix/spinnaker/keel/slack/NotificationEventListener.kt
keel-slack/src/main/kotlin/com/netflix/spinnaker/keel/slack/SlackNotificationEvent.kt
keel-slack/src/main/kotlin/com/netflix/spinnaker/keel/slack/callbacks/ManualJudgmentCallbackHandler.kt
keel-slack/src/main/kotlin/com/netflix/spinnaker/keel/slack/handlers/GitDataGenerator.kt
keel-slack/src/main/kotlin/com/netflix/spinnaker/keel/slack/handlers/PausedNotificationHandler.kt
keel-slack/src/main/kotlin/com/netflix/spinnaker/keel/slack/handlers/PinnedNotificationHandler.kt
keel-slack/src/main/kotlin/com/netflix/spinnaker/keel/slack/handlers/UnpinnedNotificationHandler.kt

Updating the notifications based on gregs updated designs.
This biggest change is in the unpin notification, where we now show the pin reason and who pinned it. We also don't cross out the commit in the manual judgment after someone has taken action.

feat(slack): updating notifications based on user feedback

---

keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/artifacts/DeliveryArtifact.kt
keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ApplicationSummaryGenerationTests.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/artifacts/DebianArtifact.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/artifacts/NpmArtifact.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/ArtifactUtils.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlArtifactRepository.kt

**Problem**
In #1848, I made [a change](https://github.com/spinnaker/keel/pull/1848/files#diff-9f58dc9351553d788680e001e102b4f871451189100572f06de9dc554acab0ebR198-R200) to the `ArtifactUtils.shouldInclude` function to account for the fact that I made `DockerArtifact.tagVersionStrategy` nullable. This function is called when building environment and artifact summaries for the UI to filter out docker tags that don't match the tag version strategy. However, when the artifact is filtered by source (branch, PR), that filter should not apply, but was incorrectly excluding all versions.
**Solution**
This PR fixes the bug in that function and replaces the condition with a more explicit check on `DockerArtifact.filteredBySource`.

fix(artifacts): Fix Docker artifact exclusion filter by tag

---

keel-slack/src/main/kotlin/com/netflix/spinnaker/keel/slack/handlers/ArtifactDeploymentNotificationHandler.kt
keel-slack/src/main/kotlin/com/netflix/spinnaker/keel/slack/handlers/GitDataGenerator.kt
keel-slack/src/main/kotlin/com/netflix/spinnaker/keel/slack/handlers/LifecycleEventNotificationHandler.kt
keel-slack/src/main/kotlin/com/netflix/spinnaker/keel/slack/handlers/ManualJudgmentNotificationHandler.kt
keel-slack/src/main/kotlin/com/netflix/spinnaker/keel/slack/handlers/MarkAsBadNotificationHandler.kt
keel-slack/src/main/kotlin/com/netflix/spinnaker/keel/slack/handlers/PinnedNotificationHandler.kt
keel-slack/src/main/kotlin/com/netflix/spinnaker/keel/slack/handlers/UnpinnedNotificationHandler.kt
keel-slack/src/main/kotlin/com/netflix/spinnaker/keel/slack/handlers/VerificationCompletedNotificationHandler.kt

Large commit messages were driving me crazy. This pr hides characters > 100 (configurable, but I picked 100 for now) behind a little "Show full commit" modal. Will add some photos shortly.
I wish I could make this code a bit nicer, but I could not figure out how to do the correct slack things in one function. So it's two for now. 
Deployd notification and a glimpse of the popup:
(there is an "Ok" button and a "close" button because I'm hacking the confirmation dialog page. If anyone knows how to just launch a modal let me know!)
pinned:
example of a message that isn't too long:

feat(slack): hide long commit msgs, show in modal

---

keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/keel/bakery/artifact/BakeryLifecycleMonitor.kt
keel-bakery-plugin/src/test/kotlin/com/netflix/spinnaker/keel/bakery/artifact/BakeryLifecycleMonitorTests.kt
keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/ImageService.kt

This causes continual rebaking because the base_ami_name of the image we bake does not match the one this bit of code finds by looking up the base image by id.

get the base image name, not the base image's base image name

---

keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/keel/bakery/artifact/ImageHandler.kt
keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/ImageService.kt
keel-clouddriver/src/test/kotlin/com/netflix/spinnaker/keel/clouddriver/ImageServiceTests.kt

This is pretty hacky and I'd like to reconsider how we determine if we need to bake or not, but this fix should get us unblocked in the meantime.

only consider images with the same base os when checking if we need to bake

---

keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/constraints/StatefulConstraintEvaluator.kt
keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/constraints/StatelessConstraintEvaluator.kt
keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/plugins/ConstraintEvaluator.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/actuation/EnvironmentConstraintRunner.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/actuation/EnvironmentPromotionChecker.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/constraints/AllowedTimesConstraintAttributes.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/constraints/AllowedTimesConstraintEvaluator.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/constraints/DependsOnConstraintAttributes.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/constraints/DependsOnConstraintEvaluator.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/core/api/ArtifactSummary.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/services/ApplicationService.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/actuation/EnvironmentPromotionCheckerTests.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/constraints/AllowedTimesConstraintEvaluatorTests.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/constraints/DependsOnConstraintEvaluatorTests.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/constraints/DependsOnConstraintEvaluatorWithVerificationsTests.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/config/KeelConfigurationFinalizer.kt

**Problem**
Stateless constraint status is always evaluated on the fly. So if you have an `allowed-times` constraint, we will evaluate whether it passes at this exact moment. That's fine when we haven't approved an artifact. But, when we've approved an artifact, that constant evaluation becomes misleading if you were to look at the non-existant UI at a time when the constraint doesn't pass.
**Solution** 
I'm saving the constraint status to the database when an artifact version is approved (`EnvironmentPromotionChecker`). We only approve a version when all constraints pass. So, at that moment we can capture the state of all the stateless constraints and save it.
**Implementation details**
You can think of the constraints like this:
- Stateful constraints need to check database information …

feat(constraints): freeze status of stateless constraints when artifact approved

---

keel-slack/src/main/kotlin/com/netflix/spinnaker/keel/slack/callbacks/ManualJudgmentCallbackHandler.kt

This week I added a feature to hide long commits in a pop up. Apparently, when we update the manual judgment notification we scrape the text from the original message and re-add it to the notification with the updated image and title. I broke that.
This PR takes a stab at fixing it, and also logs the exception we get so I can try and really fix it.

fix(mj + slack): log exception, guess at fixing

---

keel-slack/src/main/kotlin/com/netflix/spinnaker/keel/slack/callbacks/ManualJudgmentCallbackHandler.kt

I was close (thankfully) but needed two tweaks. I needed to remove the mj buttons, and also move the fallback text (the thing that says who did what) to the bottom after the link to the artifact.

fix(mj): remove buttons, change text location

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/events/NotificationEvent.kt
keel-slack/src/main/kotlin/com/netflix/spinnaker/keel/slack/NotificationEventListener.kt
keel-slack/src/main/kotlin/com/netflix/spinnaker/keel/slack/SlackNotificationEvent.kt
keel-slack/src/main/kotlin/com/netflix/spinnaker/keel/slack/handlers/DeliveryConfigNotificationHandler.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/DeliveryConfigController.kt
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/DeliveryConfigControllerTests.kt

Only send a notification to users if the config they submit is different than what we have. Using a simple object comparison for now, will re-evaluate if this doesn't work for some use cases.
Updating notification text to say "created" if the config is new, or "updated" if it's not new.

fix(notification): only send delivery config changed if changed

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/enforcers/EnvironmentExclusionEnforcer.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/actuation/IntermittentFailureTests.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/actuation/ResourceActuatorTests.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/enforcers/EnvironmentExclusionEnforcerTest.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/verification/VerificationRunnerTests.kt

Use a percentile timer to record the time spent doing the EnvironmentExclusionEnforcer checks, so we can identify if this code leads to performance issues.
Other than the timer, this PR doesn't introduce any (intended) changes in behavior.

chore(env): add timer for envt exclusion checks

---

keel-slack/src/main/kotlin/com/netflix/spinnaker/keel/slack/handlers/GitDataGenerator.kt

Turns out the confirm dialog can only handle 300 characters. I'm going to look into using an actual modal, but truncating for now so notifications aren't failing to send.

fix(slack): truncate long commits to 300 chars

---

keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/constraints/ConstraintState.kt
keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/DeliveryConfigRepositoryTests.kt
keel-orca/src/test/kotlin/com/netflix/spinnaker/keel/constraints/CanaryConstraintEvaluatorTests.kt
keel-orca/src/test/kotlin/com/netflix/spinnaker/keel/constraints/PipelineConstraintEvaluatorTests.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlDeliveryConfigRepository.kt
keel-sql/src/main/resources/db/changelog/20210316-update-env-artifact-constr.yml
keel-sql/src/main/resources/db/databaseChangeLog.yml

An artifact version isn't unique across artifacts, but an artifact reference is unique within a delivery config. This pr addresses a longstanding bug where we didn't have the artifact reference as part of the unique constraint on the `environment_artifact_constraint` table.
We've been recording artifact reference in the database since august. In this pr I'm deleting all columns where artifact reference is null. I think this is fine since the data is months old. I tested the migrations locally and it worked just fine (I inserted one row where the artifact reference was null)!

fix(constraints): require artifact reference in constraint state

---

keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/verification/VerificationRepository.kt
keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/VerificationRepositoryTests.kt
keel-core/keel-core.gradle.kts
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/actuation/ResourceActuator.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/enforcers/EnvironmentExclusionEnforcer.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/actuation/IntermittentFailureTests.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/actuation/ResourceActuatorTests.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/enforcers/EnvironmentExclusionEnforcerTest.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/verification/VerificationRunnerTests.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlVerificationRepository.kt

Implement the EnvironmentExclusionEnforcer.ensureNoActiveVerifications method. This is progress towards the work started in #1865.
* EnvironmentExclusionEnforcer.ensureNoActiveVerifications is now implemented
* new SqlVerificationRepository.countVerifications method
* EnvironmentExclusionEnforcer.withActuationLease now runs checks inside of IO dispatcher
* Change how spectator (atlas) timer is called. I was previously passing a function to spectator, but now instead I'm using traditional start/end timestamps for invoking the timer.
* Switch from the experimental `runBlockingTest` to the regular `runBlocking` in test code

chore(env): implement ensureNoActiveVerifications

---

keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/config/BakeryConfiguration.kt
keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/keel/bakery/artifact/ImageHandler.kt
keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/keel/bakery/constraint/ImageExistsConstraintEvaluator.kt
keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/keel/bakery/telemetry/BakeryTelemetryListener.kt
keel-bakery-plugin/src/test/kotlin/com/netflix/spinnaker/keel/bakery/artifact/ImageHandlerTests.kt
keel-bakery-plugin/src/test/kotlin/com/netflix/spinnaker/keel/bakery/constraint/ImageExistsConstraintEvaluatorTests.kt
keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/ImageService.kt
keel-clouddriver/src/test/kotlin/com/netflix/spinnaker/keel/clouddriver/ImageServiceTests.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/constraints/CanaryConstraintDeployHandler.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/constraints/Ec2CanaryConstraintDeployHandler.kt
keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resolvers/ImageResolver.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/api/ec2/constraints/Ec2CanaryConstraintDeployHandlerTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resolvers/ImageResolverTests.kt
keel-orca/src/main/kotlin/com/netflix/spinnaker/keel/constraints/CanaryConstraintEvaluator.kt
keel-orca/src/test/kotlin/com/netflix/spinnaker/keel/constraints/CanaryConstraintEvaluatorTests.kt

This PR ensures we always specify the base OS when looking for latest AMIs for a particular package. There are 4 situations where this is relevant:
1. when we check to see if something is already baked before launching a bake task
2. the implicit constraint that checks an appropriate AMI exists before promoting an artifact version to an environment
3. when materializing the desired state of a cluster
4. when launching a canary
In all those scenarios we want to be sure that we're selecting an image with the correct base OS according to the artifact definition in the delivery config. If a user updates their delivery config to use a new base OS we want to consider that a delta, re-bake, and re-deploy.
This also simplifies the logic around determining if we need to bake an AMI as there are …

Disambiguate base OS of AMIs

---

keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/constraints/StatefulConstraintEvaluator.kt
keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/constraints/StatelessConstraintEvaluator.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/constraints/AllowedTimesConstraintEvaluator.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/constraints/DependsOnConstraintEvaluator.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/constraints/ManualJudgementConstraintEvaluator.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/constraints/StatefulConstraintEvaluatorTests.kt
keel-orca/src/main/kotlin/com/netflix/spinnaker/keel/constraints/CanaryConstraintEvaluator.kt
keel-orca/src/main/kotlin/com/netflix/spinnaker/keel/constraints/PipelineConstraintEvaluator.kt

As seen previously with `ResourceHandler` (#1404), the plugin framework cannot proxy abstract classes. This PR converts `StatefulConstraintEvaluator` and `StatelessConstraintEvaluator` to interfaces to allow for 3rd-party extensions.

fix(plugins): Convert StatefulConstraintEvaluator and StatelessConstraintEvaluator to interfaces

---

keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/constraints/ConstraintState.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/core/api/ManualJudgementConstraint.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/constraints/ManualJudgementConstraintEvaluatorTests.kt

Timing out a manual judgement is left over from the pipeline implementation. with pipelines, we didn't want a stage running indefinitely. But MD doesn't have that technical constraint. So, let's just not time out manual judgements. It's frustrating and confusing to users and isn't getting us anything.
I've changed the default to be no time out. is that an appropriate default, or should we have a timeout as default?

feat(mj) don't time out manual judgement

---

keel-slack/src/main/kotlin/com/netflix/spinnaker/keel/slack/callbacks/CommitModalCallbackHandler.kt
keel-slack/src/main/kotlin/com/netflix/spinnaker/keel/slack/callbacks/ManualJudgmentCallbackHandler.kt
keel-slack/src/main/kotlin/com/netflix/spinnaker/keel/slack/handlers/GitDataGenerator.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/SlackAppController.kt

Launch an actual modal with the actual full commit (well, 2000 characters of it) instead of hacking the "close" dialog.

fix(slack): launch a modal with the full commit

---

keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/ArtifactController.kt

When a user builds a deb package locally, the build number is set to LOCAL. These builds are not tracked by the artifact metadata service. 
For local builds, keel logs an ERROR level log message when it fails to retrieve the metadata.
When  keel tries and fails to retrieve artifact metadata for a local build, log at info level instead.
We could detect that it's a LOCAL build and not even make the artifact metadata call in the first place. The current implementation feels a little safer because there's no risk of not calling the service.

chore(artifacts): don't treat missing metadata on local artifact build as an error

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/events/ResourceEvent.kt

Getting the following error when viewing the environment for an app where a verification blocked actuation in the event history:
```
com.fasterxml.jackson.databind.exc.InvalidTypeIdException:
Could not resolve type id 'VerificationBlockedActuation' as a subtype of PersistentEvent
```
Register the type so that jackson knows about it.

fix(events): Add VerificationBlockedActuation

---

keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/Environment.kt
keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ResourceRepositoryPeriodicallyCheckedTests.kt
keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ResourceRepositoryTests.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlArtifactRepository.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlDeliveryConfigRepository.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlResourceRepository.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlVerificationRepository.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/deliveryconfigs/deliveryconfigs.kt
keel-sql/src/main/resources/db/changelog/20210322-environment-version-table.yml
keel-sql/src/main/resources/db/changelog/20210325-latest-environment-view.yml
keel-sql/src/main/resources/db/changelog/20210331-fix-environment-resource-pk.yml
keel-sql/src/main/resources/db/changelog/20210331-fix-resource-with-metadata-view.yml
keel-sql/src/main/resources/db/databaseChangeLog.yml
keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/EnvironmentVersioningTests.kt
keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/LegacySpecUpgradeTests.kt
keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/SqlResourceRepositoryPeriodicallyCheckedTests.kt
keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/SqlResourceRepositoryTests.kt
keel-test/src/main/kotlin/com/netflix/spinnaker/keel/test/DeliveryConfigs.kt

A new version of an environment is created whenever a resource in that environment changes. There are currently no user-facing implications, but this is laying the groundwork for using environment versions rather than artifact versions to drive promotion.

Version environments when a resource changes

---

docs/configuration.md
docs/database.md
docs/environment-exclusion/environment-leases.md
docs/environment-exclusion/metrics.md
docs/environment-exclusion/overview.md
docs/environment-exclusion/resource-actuation.md
docs/environment-exclusion/verifications.md
keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ArtifactRepositoryTests.kt
keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/EnvironmentLeaseRepositoryTests.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/config/EnvironmentExclusionConfig.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/actuation/CheckScheduler.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/actuation/ResourceActuator.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/enforcers/EnvironmentExclusionEnforcer.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/exceptions/ActiveLeaseExists.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/exceptions/EnvironmentCurrentlyBeingActedOn.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ArtifactRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/EnvironmentLeaseRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/Lease.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/actuation/IntermittentFailureTests.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/enforcers/EnvironmentExclusionEnforcerTest.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/verification/VerificationRunnerTests.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/config/SqlConfiguration.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlArtifactRepository.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlEnvironmentLeaseRepository.kt
keel-sql/src/main/resources/db/changelog/20210331-add-environment-lease-repository.yml
keel-sql/src/main/resources/db/databaseChangeLog.yml
keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/SqlEnvironmentLeaseRepositoryTests.kt

Introduce environment leases to prevent concurrent verifcations or verifications concurrent with deployments.
See new docs for details.

fix(verif): use env lease to address race condition

---

keel-core-test/src/main/kotlin/com/netflix/spinnaker/time/MutableClock.kt

Occasionally, we see an SQL test failure that looks like this:
```
SqlCombinedRepositoryTests individual resources are persisted FAILED
org.jooq.exception.DataAccessException: SQL [insert into `keel`.`event` (`uid`, `scope`, `json`) values (?, ?, ?)]; Incorrect datetime value: '2021-04-03T19:06:08Z' for function str_to_date
Caused by: java.sql.SQLException: Incorrect datetime value: '2021-04-03T19:06:08Z' for function str_to_date
```
This happens when the fractional second component of the serialized Instant object is *exactly* zero. In that case, the string representation doens't have a fractional second component. This causes the mysql str_to_date function to fail, because it expects a fractional component to be there.
In the MutableClock class, which is used for generating Instant …

    fix(test): fix occasional failing sql test

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ArtifactRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/CombinedRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/KeelRepository.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/services/AdminService.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/services/AdminServiceTests.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlArtifactRepository.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/AdminController.kt

In the process of implementing checks to prevent concurrent verifications running in the same environment, or verifications running at the same time as a deployment in an environment.
The enforcement checks can block verifications or deployments if a verification gets stuck in a PENDING state or a deployment gets stuck in a DEPLOYING state.
Provide admin APIs that allow an operator to force:
* an environment artifact version to SKIPPED state
* a verification into OVERRIDE_FAIL state

feat(admin): api to force skip and fail

---

keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/Environment.kt
keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/Resource.kt
keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/DeliveryConfigRepositoryTests.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/persistence/CombinedRepository.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlDeliveryConfigRepository.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlResourceRepository.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlUnhappyVetoRepository.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlUnhealthyRepository.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/deliveryconfigs/deliveryconfigs.kt
keel-sql/src/main/resources/db/changelog/20210404-resource-version-table.yml
keel-sql/src/main/resources/db/changelog/20210409-resource-version-foreign-keys.yml
keel-sql/src/main/resources/db/databaseChangeLog.yml
keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/EnvironmentVersioningTests.kt

Refactors resource versioning so that there's a separate `resource_version` table with a many-to-one relationship with `resource`. This is closer to how environment versioning works which should be less confusing. It also reduces some associated code complexity.

Refactor resource versioning

---

keel-artifact/src/main/kotlin/com/netflix/spinnaker/keel/artifacts/DockerArtifactSupplier.kt
keel-artifact/src/test/kotlin/com/netflix/spinnaker/keel/artifacts/DockerArtifactSupplierTests.kt
keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/CloudDriverService.kt

This fixes an issue where Docker images returned from clouddriver does not contain metadata from labels. This causes Docker artifact versions to not have build information when new versions are added by [`syncArtifactVersions` ](https://github.com/spinnaker/keel/blob/eeaad1dbc1a80cb715684181a28d67b956727ff2/keel-artifact/src/main/kotlin/com/netflix/spinnaker/keel/artifacts/ArtifactListener.kt#L170 )before being processed by echo events. An artifact version processed by echo events do not add metadata if the version already exists in DB.
Clouddriver requires the `includeDetails=true` [query string ](https://github.com/spinnaker/clouddriver/blob/c17bd4b182eb3ea6b300d8d3fe09299e5abf9c12/clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/controllers/DockerRegi …

fix(docker): use includeDetails query string when getting docker images

---

keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/constraints/StatefulConstraintEvaluator.kt
keel-api/src/main/kotlin/com/netflix/spinnaker/keel/api/plugins/ConstraintEvaluator.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/events/ConstraintStateChangedRelay.kt
keel-core/src/main/kotlin/com/netflix/spinnaker/keel/services/ApplicationService.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/events/ConstraintStateChangedRelayTests.kt

Problem: plugin implementations of `StatefulConstraintEvaluator` may be interested in constraint state changes, but currently there's no contract defined on the interface to call them back when that happens. We've attempted to use the Spring `@EventListener` machinery with a `@PluginComponent` in the plugin but the callback method was not called, so we need an alternative solution.
Solution: this PR introduces a new `onConstraintStateChanged` method in `StatefulConstraintEvaluator` which receives a `ConstraintStateChanged` event when a stateful constraint's state is changed via the REST API.

feat(plugins): Add callback API for constraint state changes

---

keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlDeliveryConfigRepository.kt
keel-sql/src/main/resources/db/changelog/20210409-add-version-timestamps.yml
keel-sql/src/main/resources/db/changelog/20210413-environment-features-per-version.yml
keel-sql/src/main/resources/db/databaseChangeLog.yml
keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/EnvironmentVersioningTests.kt

Create a new environment version if constraints, notifications, or verifications change. Maintain history of those properties.

Version environment on changes

---

keel-sql/src/test/kotlin/com/netflix/spinnaker/keel/sql/TestContainer.kt

Builds in GitHub actions are failing due to:
```
The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
at com.netflix.spinnaker.keel.sql.EnvironmentVersioningTests.<init>(EnvironmentVersioningTests.kt:47)
Caused by: javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)
at com.netflix.spinnaker.keel.sql.EnvironmentVersioningTests.<init>(EnvironmentVersioningTests.kt:47)
```
According to [this file](https://github.com/spinnaker/keel/blob/57ef8a89cf39128c44c9baba5430e8e130c2f0f3/keel-sql/keel-sql.gradle.kts#L141), the intention seems to be to disable SSL in tests.
Note that this is happening in the image used by GitHub actions only and I have not been …

fix(test): return connection string with ssl disabled in sql-tests

---

Dockerfile.compile
build-scripts/entrypoint.sh

Attempt at fixing a build issue reported here: https://spinnakerteam.slack.com/archives/CERACDPDZ/p1618879421016700
Specify the new bash script as Docker `ENTRYPOINT` instead of `CMD`.  If no arguments are passed, run the same command previously specified in the Dockerfile. Otherwise, run whatever is specified in args. 
Tested locally and it worked. I have no way of testing this in cloudbuild and there isn't a way to test it outside of the master branch. 
Background:
During deb build in cloudbuild, [arguments are specified](https://github.com/spinnaker/buildtool/blob/bbc00505b02314c9d17803cb22a615206036cf87/dev/buildtool/cloudbuild/debs.yml#L20) and `CMD` supplied in Dockerfile is ignored. Because of this mysqld is never started and build fails with:
```
Step #2 - "publishDeb": Caused by: …
```

fix(build): ensure keel is built with spinnaker buildtool

---

keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/config/BakeryConfiguration.kt
keel-bakery-plugin/src/main/kotlin/com/netflix/spinnaker/keel/bakery/artifact/ImageHandler.kt
keel-bakery-plugin/src/test/kotlin/com/netflix/spinnaker/keel/bakery/artifact/ImageHandlerTests.kt

Replace the hardcoded "test" account with dynamicConfigService.

fix(bakery): remove hardcoded account name

---

keel-core-test/src/main/kotlin/com/netflix/spinnaker/keel/persistence/ArtifactRepositoryTests.kt
keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlArtifactRepository.kt

Problem: if the user changes the name of an artifact, this breaks keel.
The problematic code is in the method: SqlArtifactRepository.register, and has to do with how mysql handles unique constraints.
Here is the problematic sequence of events in SqlArtifactRepository.register
1. Looks for a matching artifact record, but doesn't find it because the name is different.
2. Generates a new ulid because no matching artifact record
3. Does an insert-on-duplicate-update to upsert into the delivery_artifact table and ends up doing an update(!) even though the ulid is different, because there's a unique constraint on (delivery_config_name, reference) that matches(!!!).
4. Attempts to insert-on-duplicate-update into artifact_last_checked table with the new ulid, which does an insert, which violates …

fix(repo): handle artifact name change in delivery config

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/telemetry/TelemetryListener.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/telemetry/TelemetryListenerTests.kt

Context:
Keel is configured to use a ThreadPoolTaskExecutor as the implementation
for its ApplicationEventTaskExecutor, which is configured in
the EventsConfiguration class (and is not modified in this PR).
This is the executor that handles published spring events. It is
configured with a single thread in the pool.
It has a thread prefix of "event-pool-", which you can see in the logs.
Problem:
We aren't currently reporting metrics on this threadpool. I have a hunch
that it is this threadpool that is getting backed up and bottlenecking
us when we get an avalanche of submitArtifact events.
Change in this PR:
Inject ThreadPoolTaskExecutors into TelemetryListener and monitor them
using Spectator thread pool monitors, so we can capture metrics on this
thread pool.

chore(metrics): monitor threadpool of Spring ThreadPoolTaskExecutor

---

.github/workflows/build.yml
README.md
commit-diff.txt

Code coverage task was causing build to fail, and no one seemed to have ever cared about the coverage badge, so removing both.

chore(build): Remove failing code coverage task

---

keel-web/keel-web.gradle

this name change happened when switch to
groovy-based gradle was made. keel-web breaks creating
the docker image for keel.
Also apply the packaging for springboot configuration
location to populate properly in the run script.
It might be that https://github.com/spinnaker/keel/commit/858c078faafc268ee628172cb9d675e0d66c2c33 impacted the way we used to package keel. 
@luispollo @lorin

fix(keel-web): rename keel-web -> keel

---

.github/workflows/periodic_release.yml

There's no reason to make them pre-release.

chore(release): Make periodic releases final

---

keel-sql/src/main/kotlin/com/netflix/spinnaker/keel/sql/SqlDeliveryConfigRepository.kt

Record when a version became active
(cherry picked from commit bb03ab814e8d9c77462be3701e6d26cc53cd96d3)

chore(versioning): timestamp to indicate when a version went active

---

keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/titus/TitusClusterHandler.kt
keel-titus-plugin/src/test/kotlin/com/netflix/spinnaker/keel/titus/resource/TitusClusterScalingPolicyTests.kt

Titus scaling policies kinda require this dimension to be present, but since it's automagically set up to mirror the ASG name (with -vNNN) we should not expect users to specify it in MD config
(cherry picked from commit 66c009d6e0f200fdb3799b9cc5772bde439eb883)

fix(titus): ignore AutoScalingGroupName dimension in diff

---

keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandler.kt

we shouldn't be stripping this off
(cherry picked from commit 0c9f4b1e8bfa06a677ddba19d1165e3acd911b46)

fix(ec2): don't strip off nf-infrastructure

---

keel-web/src/main/kotlin/com/netflix/spinnaker/keel/rest/AdminController.kt
keel-web/src/main/kotlin/com/netflix/spinnaker/keel/services/AdminService.kt

Sometimes we fix a problem that was preventing us from finding metadata. i've updated the admin endpoint here to accept a max age so that we can trigger a backfill of older versions with the fixed code.
(cherry picked from commit 95fc97bc6ee6ad75a3b4eb696f58dd18f52c2b27)

chore(admin): give an age for backfilling

---

keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/titus/batch/ContainerJobConfig.kt

Problem:
Currently, Titus containers we use for verification jobs are allocated 2GB of
memory. We had an internal customer who wanted to run a verification job
that required more memory (4GB was enough for him).
Solution:
Change the default to 4GB for now. Longer-term, this should probably be
more configurable, either by user, or by property, but this seems like a
reasonable quick fix for now.
(cherry picked from commit 65b62f06a7ce328488f0af9ce43de3ae2ceb141e)

chore(titus): bump default container mem to 4GB

---

keel-ec2-plugin/src/main/kotlin/com/netflix/spinnaker/keel/ec2/ImageTagger.kt

We were creating a counter but we weren't incrementing it.
(cherry picked from commit 61e714432d8fd4710987ea1725747bfcbcf615df)

fix(ec2): increment image tag launch metric

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/lifecycle/LifecycleMonitorScheduler.kt

Problem:
We hit a transient issue that involved a huge spike in Java object allocation, long GC pauses, and a Java out-of-memory (OOM) error.
The stack trace involved the spectator PercentileTimer in the LifecycleMonitorSchedule:
java.lang.OutOfMemoryError: Java heap space
at com.netflix.spectator.api.ArrayTagSet.addAll(ArrayTagSet.java:144)
at com.netflix.spectator.api.DefaultId.withTags(DefaultId.java:68)
at com.netflix.spectator.api.DefaultId.withTags(DefaultId.java:27)
at com.netflix.spectator.api.histogram.PercentileTimer$Builder.build(PercentileTimer.java:180)
at com.netflix.spinnaker.keel.lifecycle.LifecycleMonitorScheduler.recordDuration(LifecycleMonitorScheduler.kt:118)
at com.netflix.spinnaker.keel.lifecycle.LifecycleMonitorScheduler.invokeMonitoring(LifecycleMonitorScheduler.kt: …

fix(metrics): don't use percentile timer

---

keel-titus-plugin/src/main/kotlin/com/netflix/spinnaker/keel/titus/TitusClusterHandler.kt
keel-titus-plugin/src/test/kotlin/com/netflix/spinnaker/keel/titus/resource/TitusClusterScalingPolicyTests.kt

(cherry picked from commit 19c615c4fe51fa16a5e881c8885a5add413547b5)

feat(scaling): automatically add a AutoScalingGroupName dimension to Titus target tracking policies

---

keel-notifications/src/main/kotlin/com/netflix/spinnaker/keel/notifications/slack/handlers/PluginNotificationHandler.kt

(cherry picked from commit 2fa25613d1b8596c3adc255fa9ac89af47a48159)

fix(notification): Use the correct emoji for pluginNotification PASS/FAIL

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/scm/codeEvents.kt

(cherry picked from commit 81665044f6ebfbd7df8ea2bcd4ecc5c2cbdbe9a1)

chore(scm): Add missing rocket code events to known list

---

keel-artifact/src/main/kotlin/com/netflix/spinnaker/keel/artifacts/ArtifactListener.kt

Use normalized version when comparing latest available artifact and the current artifact from the DB.

fix(artifacts): use normalized artifact versions

---

gradle.properties
keel-ec2-plugin/keel-ec2-plugin.gradle
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClassicLoadBalancerHandlerTests.kt
keel-ec2-plugin/src/test/kotlin/com/netflix/spinnaker/keel/ec2/resource/ClusterHandlerTests.kt
keel-titus-plugin/keel-titus-plugin.gradle

This fixes test failures in https://github.com/spinnaker/keel/pull/2006
Root cause seems to be due to this change in strikt: https://github.com/robfletcher/strikt/commit/2ff8361476da86da4fd2ab1a80f103375e769c31
When `Assertion.Builder<DiffNode>.path` is called, it creates a `Assertion.Builder<NodePath>` object. This object does not have any assertions and is left alone. This was not a problem before strikt 0.31.0 because it did not care about assertion builder objects left in pending state. 
Starting version 0.31.0, any assertion builder in pending state raises `IncompleteAssertion` exception and thus this was failing. So the fix is to attach an assertion to it.

chore(dependencies): bump kork version

---

keel-core/src/main/kotlin/com/netflix/spinnaker/keel/artifacts/ArtifactVersionLinks.kt
keel-core/src/test/kotlin/com/netflix/spinnaker/keel/services/ComparableLinksTests.kt
keel-echo/src/test/kotlin/com/netflix/spinnaker/keel/echo/ManualJudgementNotifierTests.kt
keel-notifications/src/test/kotlin/com/netflix/spinnaker/keel/notifications/slack/handlers/GitDataGeneratorTests.kt
keel-test/src/main/kotlin/com/netflix/spinnaker/keel/services/versionLinksUtils.kt

Signed-off-by: Jesse Sanford <jesse.sanford@autodesk.com>
Adds support for github enterprise. Currently the gui shows up broken because it doesn't understand URLs that don't contain "github". This will allow those as long as they are "mapped to github" in the list of scm accounts.

fix(artifacts): Add support for github enterprise

---

.github/workflows/build.yml
.github/workflows/pr.yml
.github/workflows/release.yml

to try to avoid errors like:
```
ApplicationControllerTests initializationError FAILED
org.junit.jupiter.api.extension.ParameterResolutionException: Failed to resolve parameter [org.springframework.test.web.servlet.MockMvc arg0] in constructor [public com.netflix.spinnaker.keel.rest.ApplicationControllerTests(org.springframework.test.web.servlet.MockMvc,com.fasterxml.jackson.databind.ObjectMapper)]: Failed to load ApplicationContext
Caused by: java.lang.IllegalStateException: Failed to load ApplicationContext
Caused by: org.springframework.beans.factory.BeanDefinitionStoreException: Failed to process import candidates for configuration class [springfox.documentation.swagger2.configuration.Swagger2DocumentationConfiguration]; nested exception is java.lang.OutOfMemoryError: Java heap space …
```

chore(ci): give gradle more memory

---

.github/workflows/build.yml
.github/workflows/pr.yml
.github/workflows/release.yml

https://github.com/spinnaker/keel/runs/6117954393?check_suite_focus=true failed with:
```
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "default housekeeper"
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "slack-api-client-metrics-memory:38741d9e-worker-32"
*** java.lang.instrument ASSERTION FAILED ***: "!errorOutstanding" with message can't create name string at src/java.instrument/share/native/libinstrument/JPLISAgent.c line: 827
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "slack-api-client-metrics-memory:607a9eaa-worker-34"
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "default housekeeper"
Exception: …
```

chore(ci): give gradle yet more memory (6g)

---

keel-igor/src/test/kotlin/com/netflix/spinnaker/keel/services/ArtifactMetadataServiceTests.kt
keel-igor/src/test/kotlin/com/netflix/spinnaker/keel/services/DeliveryConfigImporterTests.kt
keel-web/keel-web.gradle
keel-web/src/test/kotlin/com/netflix/spinnaker/keel/rest/DeliveryConfigControllerTests.kt

This PR removes the last few remaining references to retrofit1 and `RetrofitError`. Only tests are affected.

refactor(retrofit): removed last few remaining references to retrofit1
